url: https://www.emfink.net
baseurl: /PRcasebook
title: Professional Responsibility
description:  An Open-Source Casebook
name: Eric M. Fink

last_updated: 20 July 2022 # leave blank if you don't want to display last updated

author: Eric M. Fink
position: Associate Professor
institution: Elon Law School
street: 201 North Greene Street
city: Greensboro
state: North Carolina
zip: '27401'
email: efink@elon.edu
phone: 336-279-9334
web: emfink.net/ElonLaw


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
