# Conflicts of Interest

## Conflicts Between Current Clients

#### @MRPC17

::: legalcode
##### Conflict of Interest: Current Clients

-   \(a\) Except as provided in paragraph (b), a lawyer shall not represent a client if the representation involves a concurrent conflict of interest. A concurrent conflict of interest exists if:
    -   \(1\) the representation of one client will be directly adverse to another client; or
    -   \(2\) there is a significant risk that the representation of one or more clients will be materially limited by the lawyer's responsibilities to another client, a former client or a third person or by a personal interest of the lawyer.
-   \(b\) Notwithstanding the existence of a concurrent conflict of interest under paragraph (a), a lawyer may represent a client if:
    -   \(1\) the lawyer reasonably believes that the lawyer will be able to provide competent and diligent representation to each affected client;
    -   \(2\) the representation is not prohibited by law;
    -   \(3\) the representation does not involve the assertion of a claim by one client against another client represented by the lawyer in the same litigation or other proceeding before a tribunal; and
    -   \(4\) each affected client gives informed consent, confirmed in writing.
:::

#### @ReDresserIndusInc_5thCir1992

In this petition for a writ of mandamus, we determine whether a law firm may sue its own client, which it concurrently represents in other matters. In a word, no; and most certainly not here, where the motivation appears only to be the law firm's self-interest. We therefore grant the writ, directing the district judge to disqualify counsel.

[I]{.casesection}

The material facts are undisputed. This petition arises from a consolidated class action antitrust suit brought against manufacturers of oil well drill bits. *Red Eagle Resources et al. v. Baker Hughes, et al.* (*"Drill Bits"*).

Dresser Industries, Inc., ("Dresser") is now a defendant in *Drill Bits,* charged---by its own lawyers---with conspiring to fix the prices of drill bits and with fraudulently concealing its conduct. Stephen D. Susman, with his firm, Susman Godfrey, is lead counsel for the plaintiff's committee. As lead counsel, Susman signed the amended complaint that levied these charges against Dresser, his firm's own client.

Susman Godfrey concurrently represents Dresser in two pending lawsuits. *CPS International, Inc. v. Dresser Industries, Inc.* is the third suit brought by CPS International, a company that claims Dresser forced it out of the compressor market in Saudi Arabia. CPS International initially sued Dresser for antitrust violations and tortious interference with a contract. The antitrust claim has been dismissed, but the tort claim is scheduled for trial. Susman Godfrey has represented Dresser throughout these actions, which commenced in 1985. During its defense of Dresser, Susman Godfrey lawyers have had relatively unfettered access to data concerning Dresser's management, organization, finances, and accounting practices. Susman Godfrey's lawyers have engaged in privileged communications with Dresser's in-house counsel and officers in choosing antitrust defenses and other litigation strategies. Susman Godfrey has also, since 1990, represented Dresser in *Cullen Center, Inc. v. W.R. Gray Co.,* a case involving asbestos in a Dresser building, which is now set for trial in Texas state court.

On October 24 and November 24, 1991, Susman Godfrey lawyers wrote Dresser informing it that Stephen Susman chaired the plaintiffs' committee in *Drill Bits,* that Dresser might be made a *Drill Bits* defendant, and that, if Dresser replaced Susman Godfrey, the firm would assist in the transition to new counsel. Dresser chose not to dismiss Susman Godfrey in *CPS* and *Cullen Center.*

Dresser was joined as a defendant in *Drill Bits* on December 2, 1991. Dresser moved to disqualify Susman as plaintiffs' counsel on December 13. Both Dresser and Susman Godfrey submitted affidavits and depositions to the district court, which, after a hearing, issued a detailed opinion denying the motion.

The district court noted that Southern District local rule 4B provides that the code of professional responsibility for lawyers practicing in that district is the Code of Responsibility of the State Bar of Texas. Although the court further noted that other district courts look to other codes in deciding motions to disqualify, nevertheless, it concluded that "Dresser's motion to disqualify Susman Godfrey is governed wholly by the Texas Disciplinary Rules of Professional Conduct." The court then focused on Texas Disciplinary Rule 1.06, which provides:

> \(b\) Except to the extent permitted in paragraph (c), a lawyer shall not represent a person if the representation of that person:

> > \(1\) involves a substantially related matter in which that person's interests are materially and directly adverse to the interests of another client of the lawyer or the lawyer's firm; or

> > \(2\) reasonably appears to be or become adversely limited by the lawyer's or law firm's responsibilities to another client or to a third person or by the lawyer's or law firm's own interests.

> \(c\) A lawyer may represent a client in the circumstances described in (b) if:

> > \(1\) the lawyer reasonably believes the representation of each client will not be materially affected; and

> > \(2\) each affected or potentially affected client consents to such representation after full disclosure.

The district court described the *Drill Bits* complaint as a civil antitrust case, thus somewhat softening Dresser's description of it as an action for fraud or criminal conduct. The court held, "as a matter of law, that there exists no relationship, legal or factual, between the *Cullen Center* case and the *Drill Bits* litigation," and that no similarity between *Drill Bits* and the *CPS* suits was material. The court concluded that "Godfrey's representation of the plaintiffs in the *Drill Bits* litigation does not reasonably appear to be or become adversely limited by Susman Godfrey's responsibilities to Dresser in the *CPS* and *Cullen Center* cases," and accordingly denied the motion to disqualify.

[II]{.casesection}

In evaluating a motion to disqualify, we interpret the controlling ethical norms governing professional conduct as we would any other source of law. When the facts are undisputed, district courts enjoy no particular advantage over appellate courts in formulating ethical rules to govern motions to disqualify. Thus, in the event an appropriate standard for disqualification is based on a state's disciplinary rules, a court of appeals should consider the district court's interpretation of the state disciplinary rules as an interpretation of law, subject essentially to *de novo* consideration.

[IV]{.casesection}

We apply specific tests to motions to disqualify counsel in circumstances governed by statute or the Constitution. When presented with a motion to disqualify counsel in a more generic civil case, however, we consider the motion governed by the ethical rules announced by the national profession in the light of the public interest and the litigants' rights. Our source for the standards of the profession has been the canons of ethics developed by the American Bar Association. We have applied particularly the requirement of canon 5 that a lawyer exercise "independent professional judgment on behalf of the client" and the admonition of canon 9 that lawyers should "avoid even the appearance of impropriety."

Our most far-reaching application of the national standards of attorney conduct to an attorney's obligation to avoid conflicts of interest is *Woods v. Covington County Bank,* (5th Cir.1976) (attorney in army reserve not barred from privately representing clients in securities matters he had investigated while on active duty). We held in *Woods* that standards such as the ABA canons are useful guides but are not controlling in adjudicating such motions. The considerations we relied upon in *Woods* were whether a conflict has (1) the appearance of impropriety in general, or (2) a possibility that a specific impropriety will occur, and (3) the likelihood of public suspicion from the impropriety outweighs any social interests which will be served by the lawyer's continued participation in the case.

We applied the *Woods* standard to a conflict that arose when an attorney brought a suit against a former client in *Brennan's Inc. v. Brennan's Restaurant, Inc.,* (5th Cir.1979). In *Brennan's,* the plaintiffs moved to have the court disqualify the attorney for the defendants because, prior to the litigation, the attorney had jointly represented both parties. We affirmed the disqualification of the attorney, holding that an attorney could not sue a former client in a matter substantially related to the representation of a former client. Similarly, in *Wilson P. Abraham Construction Corp. v. Armco Steel Corp.,* (5th Cir. 1977), we held that the court should bar an attorney from suing the co-defendant of a former client if the co-defendants and their attorneys exchanged information.

In *Woods*, *Wilson Abraham*, and *Brennan's*, we applied national norms of attorney conduct to a conflict arising after the attorney's prior representation had been concluded. Now, however, we are confronted with our first case arising out of concurrent representation, in which the attorney sues a client whom he represents on another pending matter. We thus consider the problem of concurrent representation under our framework in *Woods* as tailored to apply to the facts arising from concurrent representation.

We turn, then, to the current national standards of legal ethics to first consider whether this dual representation amounts to impropriety. Neither the ABA Model Rules of Professional Conduct nor the Code of Professional Responsibility allows an attorney to bring a suit against a client without its consent. This position is also taken by the American Law Institute in its drafts of the *Restatement of the Law Governing Lawyers.*

Unquestionably, the national standards of attorney conduct forbid a lawyer from bringing a suit against a current client without the consent of both clients. Susman's conduct violates all of these standards---unless excused or justified under exceptional circumstances not present here.

Exceptional circumstances may sometimes mean that what is ordinarily a clear impropriety will not, always and inevitably, determine a conflicts case. Within the framework we announced in *Woods,* Susman, for example, might have been able to continue his dual representation if he could have shown some social interest to be served by his representation that would outweigh the public perception of his impropriety. Susman, however, can present no such reason. There is no suggestion that other lawyers could not ably perform his offices for the plaintiffs, nor is there any basis for a suggestion of any societal or professional interest to be served. This fact suggests a rule of thumb for use in future motions for disqualification based on concurrent representation: However a lawyer's motives may be clothed, if the sole reason for suing his own client is the lawyer's self-interest, disqualification should be granted.

#### @RepresentationPurchaseForeclosedProperty_NCStateBar2013

Opinion examines the ethical duties of a lawyer representing both the buyer and the seller on the purchase of a foreclosure property and the lawyer’s duties when the representation is limited to the seller.

[Inquiry #1:]{.casesection}

Bank A foreclosed its deed of trust on real property and was the highest bidder at the sale. Bank A listed the property for sale. Buyer entered into a contract to purchase the property.

An addendum to the Offer to Purchase and Contract (“Contract”) signed by the parties states that the closing shall be held in Seller’s lawyer’s office by a date certain and that Seller, Bank A, “shall only pay those closing costs and fees associated with the transfer of the Property that local custom or practice clearly allocates to Seller and the Buyer shall pay all remaining fees and costs.” Bank B is providing financing for the transaction.

Seller chose Law Firm X to close the residential real estate transaction. Law Firm X did not participate in the foreclosure of the property prior to the sale; however, Law Firm X regularly does closings for properties sold by Bank A.

Law Firm X proposes to send Buyer a letter advising Buyer that it has been chosen as settlement agent and advising Buyer that it will be representing both parties in the transaction. Law Firm X will charge Buyer \$425 for the closing.

May Lawyer at Law Firm X participate in the joint representation of Buyer and Seller as contemplated by the Contract?

[Opinion #1:]{.casesubsection}

If a lawyer is named as the closing agent for a residential real estate transaction pursuant to an agreement such as the one set out above, the lawyer has a duty to ensure that he can comply with Rule 1.7 prior to accepting joint representation of the buyer and seller. When contemplating joint representation, a lawyer must consider whether the interests of the parties will be adequately protected if they are permitted to give their informed consent to the representation, and whether an independent lawyer would advise the parties to consent to the conflict of interest. Representation is prohibited if the lawyer cannot reasonably conclude that he will be able to provide competent and diligent representation to all clients. See Rule 1.7, cmt. \[15\]. As stated in comment \[29\] to Rule 1.7, the representation of multiple clients “is improper when it is unlikely that impartiality can be maintained.”

The Ethics Committee has previously concluded that, under certain circumstances, it may be acceptable for a lawyer to represent the borrower, the lender, and the seller in the closing of a residential real estate transaction. See, e.g. CPR 100, RPC 210. Joint representation may be permissible in a residential real estate closing because, in the usual transaction, the contract to purchase is entered into by the buyer and seller prior to the engagement of a lawyer. Therefore, the lawyer has no obligation to bargain for either party. Similarly, the buyer and the lender have agreed to the basic terms of the mortgage loan prior to the engagement of the closing lawyer. However, in CPR 100, the Ethics Committee specifically stated that:

> a lawyer having a continuing professional relationship with any party to the usual residential transaction, whether the seller, the lender, or the borrower, should be particularly alert to determine in his own mind whether or not there is any obstacle to his loyal representation of other parties to the transaction, and if he finds that there is, or if there is any doubt in his mind about it, he should promptly decline to represent any other party to the transaction.

In addition to the above determination, Rule 1.7 requires that the lawyer obtain any affected client’s informed consent to the joint representation and to confirm that consent in writing. Rule 1.7.

Comment \[6\] to Rule 1.0 (Terminology) provides that, to obtain “informed consent,” a lawyer must “make reasonable efforts to ensure that the client or other person possesses information reasonably adequate to make an informed decision.” Comment \[6\] clarifies that, ordinarily, this will require: (1) communication that includes a disclosure of the facts and circumstances giving rise to the situation; (2) any explanation reasonably necessary to inform the individual of the material advantages and disadvantages of the proposed course of conduct; and (3) a discussion of the individual’s options and alternatives.

To obtain Buyer’s “informed” consent in the instant scenario, Lawyer must: (1) explain the proposed scope of the lawyer's representation; (2) disclose Lawyer’s prior relationship with Seller; (3) explain the advantages and risks of common representation; and (4) discuss the options/alternatives Buyer has under the Contract, such as hiring his own lawyer at his own expense.

If the above requirements are met, Lawyer may proceed with the common representation. If Lawyer subsequently determines that he can no longer exercise his independent professional judgment on behalf of both clients, he must withdraw from the representation of both clients.

If Lawyer determines at the outset that the common representation will be adverse to the interests of either Buyer or Seller, or that his judgment will be impaired by loyalty to Seller, Lawyer may not represent both parties. Similarly, if Buyer does not consent to the joint representation, Lawyer may not represent both parties.

[Inquiry #2:]{.casesection}

Buyer notifies Lawyer at Law Firm X that he wants to have his own lawyer represent him at the closing. Therefore, Law Firm X intends to limit its representation to Seller. To clarify its role in the transaction, Lawyer sends Buyer an Independently Represented Buyer Acknowledgement to sign agreeing that, although Law Firm X was providing services necessary and incidental to effectuating a settlement of the transaction, including providing an opinion of title for the Buyer’s policy to the title insurance company chosen by and affiliated with Bank A, there will be no attorney-client relationship between Law Firm X and Buyer. Law Firm X informs Buyer that the charge for the closing will be reduced to \$325.

May Law Firm X limit its representation to Seller and charge Buyer \$325 for closing the real estate transaction?

[Opinion #2:]{.casesubsection}

Upon notice that Buyer wants to have his own lawyer represent him at the closing, Lawyer must first determine whether Buyer desires Law Firm X to continue to represent his interests in conjunction with his own lawyer. If Buyer desires Law Firm X to continue to represent his interests in the closing, then Law Firm X may continue to advise Buyer and the firm would not be required to adjust its fee.

If Buyer does not consent to the joint representation, Lawyer may limit his representation to Seller in the absence of a conflict of interest. Under the circumstances, it is incumbent upon Lawyer to clarify its role to Buyer. 2006 FEO 3 specifically holds that a lawyer may represent only the seller’s interests in a transaction and provide services as a title and closing agent, as required by the contract of sale. There must, however, be certain robust and thorough disclosures to the buyer.

Pursuant to 2006 FEO 3, Lawyer must “fully disclose to Buyer that Seller is his sole client, he does not represent the interests of Buyer, the closing documents will be prepared consistent with the specifications in the contract to purchase and, in the absence of such specifications, he will prepare the documents in a manner that will protect the interests of his client, Seller, and, therefore, Buyer may wish to obtain his own lawyer.” 2006 FEO 3.

If Lawyer limits his representation to Seller, Lawyer may not perform any legal services for Buyer. At the conclusion of the representation, Lawyer needs to consider the factors set out in Rule 1.5(a) and determine whether the fee of \$325 is clearly excessive for the services performed for Seller.

Whether the contract to purchase the property requires Buyer to pay Lawyer’s fee for representation of Seller is a legal question outside the purview of the Ethics Committee. However, a lawyer may be paid by a third party, including an opposing party, provided the lawyer complies with Rule 1.8(f) and the fee is not illegal or clearly excessive in violation of Rule 1.5(a). See RPC 196.

Similarly, Buyer’s authority to renegotiate the terms of the Contract pertaining to the selection of the closing lawyer, and/or the payment of the closing costs and fees associated with the closing, are outside the purview of the Ethics Committee.

[Inquiry #3:]{.casesection}

May Lawyer provide an opinion of title to the title insurance company for Buyer’s title insurance policy under the circumstances described in Inquiry #2?

[Opinion #3:]{.casesubsection}

In representing Seller, Law Firm X may provide an opinion on title to the title insurer sufficient and necessary to satisfy the requirements of the Contract and facilitate completion of the transaction on behalf of Seller. See CPR 100, RPC 210, 2006 FEO 3.

CPR 100 and RPC 210 provide that a lawyer who is representing the buyer, the lender, and the seller (or any one or more of them) may provide the title insurer with an opinion on title sufficient to issue a mortgagee title insurance policy, when the premium is paid by the buyer. CPR 100 further recommends that, because a buyer-borrower is usually inexperienced in the purchase of real estate and the securing of loans thereon, “any lawyer involved in the transaction, even though not representing the borrower, should be alert to inform the borrower of the availability of an owner's title insurance policy which is usually available to the borrower up to the amount of the loan at little or no expense to the borrower, and assist the borrower in obtaining an owner's title insurance policy.”

#### @RepresentationPartiesCommercialReal_NCStateBar2015

Opinion rules that common representation in a commercial real estate loan closing is, in most instances, a “nonconsentable” conflict meaning that a lawyer may not ask the borrower and the lender to consent to common representation.

[Background:]{.casesection}

In the standard closing of a commercial loan secured by real property (a “commercial loan closing”), the borrower and the lender have separate legal counsel. The borrower’s lawyer traditionally handles most aspects of the closing including the preparation of the settlement statement as well as the collection of funds, the payoffs, and the disbursements. The borrower understands that its lawyer represents its interests alone. Unlike a residential real estate closing in which the lender’s documents can rarely be modified once entered into by the borrower/buyer, it is common in a commercial loan closing for the borrower’s lawyer to be actively involved in negotiating provisions of the commitment letter that establishes the basic terms of the mortgage, and to also negotiate specific revisions to the loan documents to address material matters such as default, disbursement of insurance proceeds, permitted transfers, and indemnification.

A large regional bank recently changed its commercial loan closing policies to require all lawyers who close commercial loans with the bank to be employed by law firms that are “authorized” by the bank to close its loans. These lawyers are designated as “Bank’s Counsel.” Bank’s Counsel is asked by the bank to handle the entire closing including the title search, title certification, and the holding and disbursing of the closing funds.

Lawyers who traditionally represent the borrower in a commercial loan closing are concerned about this policy for a number of reasons including the following:

-   Having closing funds delivered to the lender’s lawyer instead of the borrower’s lawyer subjects the borrower to responsibility for the funds without the benefit of its own legal counsel’s guidance, protection, and assistance;
-   Once the loan funds are committed to the borrower by the lender, they become the responsibility of the borrower. When there is separate, independent representation of the borrower, the protections of malpractice insurance and the closing protection letter are available to the borrower.
-   The borrower’s recourses may be limited if closing funds are mishandled and the borrower suffers a loss in connection with Bank’s Counsel’s preparation of the closing statement and disbursement of the loan proceeds. However, when the borrower's lawyer performs the escrow and closing functions, the lender gets an insured closing letter and a legal opinion relative to authority and enforceability from the borrower's lawyer and has protection.
-   Having the lender’s lawyer perform the property and business due diligence functions may result in the disclosure of confidential information relative to the borrower’s property or its business interests that would not be disclosed if the borrower’s lawyer performed these functions.
-   Unless the borrower is sophisticated and instructs its lawyer to be actively involved, the borrower’s lawyer may be placed in the role of “outsider” or passive observer, which may limit the quality and scope of the representation that the borrower receives. It will also invite, notwithstanding disclosure, the perception that the lender's lawyer is looking out for the interests of all of the parties.

[Inquiry #1:]{.casesection}

May a lawyer represent both the borrower and the lender for the closing of a commercial loan secured by real property? If so, is informed consent of both the borrower and the lender required, and what information must be disclosed to obtain informed consent?

[Opinion #1:]{.casesubsection}

In most instances, a lawyer may not represent both the borrower and the lender for the closing of a commercial loan even with consent.

Rule 1.7 prohibits the representation of a client if the representation involves a concurrent conflict of interest unless certain conditions are met. A concurrent conflict of interest exists if the representation of one client will be directly adverse to another client or the representation of one client may be materially limited by the lawyer’s responsibilities to another client. Rule 1.7(a). The closing of a commercial loan secured by real estate is an “arm’s length” business transaction in which large sums of money are at stake, the documentation is complex, and the opportunities to negotiate on behalf of each party are numerous. As observed in the comment to Rule 1.7:

> Even where there is no direct adverseness, a conflict of interest exists if a lawyer's ability to consider, recommend, or carry out an appropriate course of action for the client may be materially limited as a result of the lawyer's other responsibilities or interests. For example, a lawyer asked to represent a seller of commercial real estate, a real estate developer, and a commercial lender is likely to be materially limited in the lawyer's ability to recommend or advocate all possible positions that each might take because of the lawyer's duty of loyalty to the others. The conflict in effect forecloses alternatives that would otherwise be available to the client. The mere possibility of subsequent harm does not itself preclude the representation or require disclosure and consent. The critical questions are the likelihood that a difference in interests will eventuate and, if it does, whether it will materially interfere with the lawyer's independent professional judgment in considering alternatives or foreclose courses of action that reasonably should be pursued on behalf of the client.

Rule 1.7, cmt. \[8\].

Rule 1.7(b) allows a lawyer to proceed with a representation burdened with a concurrent conflict of interest, but only if the lawyer determines that the representation of all of the affected clients will be competent and diligent and each affected client gives informed consent. In other words, the lawyer must decide whether the conflict is “consentable.” Rule 1.7, cmt. \[2\]. If the lawyer’s exercise of independent professional judgment on behalf of any client will be compromised, the conflict is not consentable. As noted in the comment to Rule 1.7:

> Some conflicts are nonconsentable, meaning that the lawyer involved cannot properly ask for such agreement or provide representation on the basis of the client's consent Consentability is typically determined by considering whether the interests of the clients will be adequately protected if the clients are permitted to give their informed consent to representation burdened by a conflict of interest Representation is prohibited if in the circumstances the lawyer cannot reasonably conclude that the lawyer will be able to provide competent and diligent representation.

Rule 1.7, cmt.\[14\]-\[15\]. Although deleted from the comment to Rule 1.7 when the Rules of Professional Conduct were comprehensively revised in 2003, the following is an excellent test for determining whether a conflict is “consentable”: “when a disinterested lawyer would conclude that the client should not agree to the representation under the circumstances, the lawyer involved cannot properly ask for such agreement or provide representation on the basis of the client's consent.” Rule 1.7, cmt. \[5\] (2002).

In RPC 210, the Ethics Committee held that a lawyer may represent the seller, borrower/buyer, and lender in a residential real estate closing with the informed consent of all of the parties. Even so, the opinion includes the following cautionary language:

> A lawyer may reasonably believe that the common representation of multiple parties to a residential real estate closing will not be adverse to the interests of any one client if the parties have already agreed to the basic terms of the transaction and the lawyer's role is limited to rendering an opinion on title, memorializing the transaction, and disbursing the proceeds. Before reaching this conclusion, however, the lawyer must determine whether there is any obstacle to the loyal representation of both parties. The lawyer should proceed with the common representation only if the lawyer is able to reach the following conclusions: he or she will be able to act impartially; there is little likelihood that an actual conflict will arise out of the common representation; and, should a conflict arise, the potential prejudice to the parties will be minimal.

A commercial loan closing is substantially different from a residential closing in which there is little opportunity to negotiate on behalf of the borrower/buyer once the purchase contract and loan commitment letter are signed. In a commercial loan closing, there are numerous opportunities for a lawyer to negotiate on behalf of the parties, so impartiality is rarely possible. There are also numerous opportunities for an actual conflict to arise between the borrower and the lender and, if a conflict does arise, the prejudice to the parties would be substantial. Therefore, common representation in a commercial loan closing is, in most instances, a “nonconsentable” conflict, meaning that a lawyer may not ask the borrower and the lender to consent to common representation. Restatement (Third) of The Law Governing Lawyers, § 122, Comment g(iv), cites decisions in which the court denied the possibility of client consent as a matter of law in certain categories of cases. These decisions include Baldasarre v. Butler, 625 A. 2d 458 (N.J. 1993), in which the Supreme Court of New Jersey observed:

> This case graphically demonstrates the conflicts that arise when an attorney, even with both clients’ consent, undertakes the representation of the buyer and the seller in a complex commercial real estate transaction. The disastrous consequences of the lawyer’s dual representation convinces us that a new bright-line rule prohibiting dual representation is necessary in commercial real estate transactions where large sums of money are at stake, where contracts contain complex contingencies, or where options are numerous. The potential for conflict in that type of complex real estate transaction is too great to permit even consensual dual representation of buyer and seller. Therefore, we hold that an attorney may not represent both the buyer and seller in a complex commercial real estate transaction even if both give their informed consent.

In summary, dual representation of the borrower and the lender for the closing of a commercial real estate loan is a nonconsentable conflict of interest unless the following conditions can be satisfied: (1) the contractual terms have been finally negotiated prior to the commencement of the representation; (2) there are no material contingencies to be resolved; (3) the lawyer reasonably believes that the lawyer will be able to provide competent and diligent representation to each affected client; (4) it is unlikely that a difference in interests will eventuate and, if it does, it will not materially interfere with the lawyer’s independent professional judgment in considering alternatives or foreclose courses of action that should be pursued on behalf of a client; (5) the lawyer reasonably concludes that he will be able to act impartially in the representation of both parties; (6) the lawyer explains to both parties that his role is limited to executing the tasks necessary to close the loan and that this limitation prohibits him from advocating for the specific interests of either party; (7) the lawyer discloses that he must withdraw from the representation of both parties if a conflict arises; and (8) after the foregoing full disclosure, both parties give informed consent confirmed in writing.

Regardless of the above conditions allowing common representation of the borrower and lender, consent may never be sought to represent the lender, the borrower, and the seller of real property if the seller will provide secondary financing for the transaction and accept a secondary deed of trust. In this situation, the risks to the interests of the seller are too great to permit a lawyer to seek consent to common representation.

[Inquiry #2:]{.casesection}

The bank intends for Bank’s Counsel to represent only the bank (lender) but to handle all aspects of the closing.

May a lawyer represent only the lender but handle all aspects of a commercial loan closing including the title search, title certification, marshalling the necessary documents, and holding and disbursing of the closing funds? If so, what information must be disclosed by Bank’s Counsel to the borrower relative to the role of Bank’s Counsel?

[Opinion #2:]{.casesubsection}

Yes, a lawyer may be the lead lawyer for the closing (“the closing lawyer”) provided the lawyer represents only one party—either the lender or the borrower. Because the title work and other due diligence are for the benefit of the lender, there is no prohibition on the lender’s lawyer performing these tasks. See 2004 FEO 10 (because buyer is the intended beneficiary of the deed although not a signatory, buyer’s lawyer may prepare deed without creating a lawyer-client relationship with seller). However, if the closing lawyer represents the lender, certain conditions must be satisfied.

In 2006 FEO 3, the Ethics Committee considered whether a lawyer may represent a lender on the closing of the sale to a third party of property acquired by the lender as result of foreclosure by execution of the power of sale in the deed of trust on the property. The opinion holds (among other things) that a lawyer may serve as the closing lawyer and limit his representation to the lender/seller if there is disclosure to the buyer:

> Attorney A must fully disclose to Buyer that the lender/seller is his sole client, he does not represent the interests of Buyer, the closing documents will be prepared consistent with the specifications in the contract to purchase, and, in the absence of such specifications, he will prepare the documents in a manner that will protect the interests of his client, the lender/seller, and, therefore, Buyer may wish to obtain his own lawyer. See, e.g., RPC 40 (disclosure must be far enough in advance of the closing that the buyer can procure his own counsel), RPC 210, 04 FEO 10, and Rule 4.3(a). Because of the strong potential for Buyer to be misled, the disclosure must be thorough and robust.

Consistent with the holding in 2006 FEO 3, in a commercial loan closing, the lender’s lawyer may serve as the closing lawyer provided the borrower is informed that the closing lawyer will not represent its interests and will interpret loan documents in the light that is most favorable to the lender; the borrower is given a reasonable opportunity to retain its own counsel and is not mislead as to its right to do so; the lawyers for both parties advise their clients about the risks and benefits of a having the lender’s lawyer serve as the closing lawyer; and the borrower’s lawyer is allowed to observe and participate in the transaction to the extent necessary to protect the borrower’s interests.

This opinion cannot address all of the concerns expressed in the Background section above relative to the additional risks to the borrower if the lawyer for the closing is the lender’s lawyer. However, if the closing funds are deposited to and disbursed from the trust account of the lender’s lawyer in accordance with the requirements of the trust accounting rule, Rule 1.15, the funds should not be at risk. To the extent that there are other risks to the interests of the borrower, the borrower’s lawyer must analyze those risks and advise the borrower about steps that may be taken to minimize the risks including negotiating with the lender’s lawyer for aspects of the closing to be handled by the borrower’s lawyer.

#### @ContemporaneousResidentialRealEstate_NCStateBar2021

Opinion addresses conflicts of interest, communication, funding issues, and accountings in contemporaneous closings for residential real property.

[Facts:]{.casesection}

Residential real property is owned by record owner A. The property is to be conveyed from record owner A to B and from B to end buyer C on the same day. The sales price for the A to B transaction is \$80,000. The sales price for the B to C transaction is \$100,000. The money provided by C would be utilized by B to make B’s purchase from A; B would provide no independent funding. One lawyer, Lawyer, would close both the A to B and B to C transactions. Lawyer would represent B and C; Lawyer would not represent A. Lawyer would be the settlement agent for the closings.

[Inquiry #1:]{.casesection}

Can Lawyer represent B and C in these transactions?

[Opinion #1:]{.casesubsection}

This scenario presents a concurrent conflict of interest under Rule 1.7(a). Lawyer’s representation of C may be materially limited by Lawyer’s responsibilities to B, and vice versa.

Rule 1.7(b) articulates the circumstances under which a lawyer may represent a client notwithstanding the existence of a concurrent conflict of interest. One requirement is that the lawyer reasonably believes that the lawyer will be able to provide competent and diligent representation to each affected client.

In assessing whether a representation burdened by a concurrent conflict of interest might be permissible, the lawyer “must consider ‘whether there is any obstacle to the loyal representation of both parties.’” As discussed in 2013 FEO 4 in the context of joint representation of a buyer and a seller in a residential real estate transaction:

> The lawyer has a duty to ensure that he can comply with Rule 1.7 prior to accepting joint representation of the buyer and seller. When contemplating joint representation, a lawyer must consider whether the interests of the parties will be adequately protected if they are permitted to give their informed consent to the representation, and whether an independent lawyer would advise the parties to consent to the conflict of interest. Representation is prohibited if the lawyer cannot reasonably conclude that he will be able to provide competent and diligent representation to all clients.

To provide competent and diligent representation to C, Lawyer would need to disclose to C all material facts known to Lawyer about the transactions and advise C with respect to all of the facts and circumstances concerning the transactions.

Matters about which Lawyer would need to communicate with C include:

1.  That B does not own the property and whether the contract entered into between B and C for the sale of the property is valid;

2.  That C’s money will be used by B to purchase the property from A, for which C’s informed consent would need to be given (*see* Opinion #4 below); and

3.  The price at which B is purchasing the property from A, which is a fact that may not otherwise be known by C and might bear upon the true market value of the property and/or whether C would consider it in C’s best interest to proceed.

Certain of these facts will be confidential information known to Lawyer from his representation of B and protected from disclosure under Rule 1.6. Certain of these facts may be matters B does not want disclosed to C or may involve information the disclosure of which would harm B’s interests, which Lawyer must consider in determining whether Lawyer can provide competent and diligent representation to both B and C.

Lawyer cannot represent C unless B consents to the disclosure to C of all facts regarding the A to B transaction and the conditions of Rule 1.7(b) are otherwise met.

Another of the conditions in Rule 1.7(b) on representation notwithstanding a concurrent conflict of interest is that the lawyer obtain any affected client’s informed consent to the representation confirmed in writing. Informed consent is defined in Rule 1.0 as “the agreement by a person to a proposed course of conduct after the lawyer has communicated adequate information and explanation appropriate to the circumstances.” Comment \[6\] to Rule 1.0 states that, to obtain informed consent, a lawyer

> must make reasonable efforts to ensure that the client or other person possesses information reasonably adequate to make an informed decision. Ordinarily this will require communication that includes a disclosure of the facts and circumstances giving rise to the situation, any explanation reasonably necessary to inform the client or other person of the material advantages and disadvantages of the proposed course of conduct and a discussion of the client’s or other person’s options and alternatives.

Lawyer would need to obtain informed consent from both B and C. To obtain informed consent from B and C, Lawyer must explain to B and C how the interests of B and C may be in conflict, including disclosure of all facts and circumstances giving rise to potential conflicts in their interests.

With respect to C, the facts and circumstances Lawyer would need to disclose to C to obtain informed consent from C include but are not limited to all of the matters discussed above for required communications to C. To obtain informed consent from C, Lawyer must also discuss with C the advantages and disadvantages of the proposed transactions for C and C’s options and alternatives, including C retaining independent counsel. If Lawyer cannot discuss all of these matters with C for any reason – including B not wanting certain information disclosed to C or disclosure to C being adverse to B’s interests – then Lawyer cannot obtain C’s informed consent and cannot represent C in these transactions.

[Inquiry #2:]{.casesection}

Is the answer to Inquiry #1 different if Lawyer maintains that Lawyer only represents B in the A to B transaction and only represents C in the B to C transaction.

[Opinion #2:]{.casesubsection}

No. A concurrent conflict of interest under Rule 1.7(a)(2) exists if a lawyer’s representation of a client may be materially limited by the lawyer’s responsibilities to another client, a former client, a third person, or by a personal interest of the lawyer. The above-identified conflicts would still exist even if Lawyer only represented B with respect to the A to B transaction and C with respect to the B to C transaction. *See* Opinion #1.

[Inquiry #3:]{.casesection}

If Lawyer concludes that Lawyer cannot represent C, can Lawyer proceed with the closings representing only B?

[Opinion #3:]{.casesubsection}

It depends. To the extent C consulted with Lawyer or provided Lawyer with information to close the B to C transaction but no attorney-client relationship was formed between Lawyer and C, C would be a prospective client under Rule 1.18(a). If an attorney-client relationship was formed between Lawyer and C but was terminated by Lawyer due to the conflict of interest, then C is a former client under Rule 1.9.

Under Rule 1.18(b) and Rule 1.9(c), Lawyer is prohibited from revealing any information learned from C and from using such information to the disadvantage of C. If this prohibition materially limits Lawyer’s representation of B, then Lawyer cannot represent B under Rule 1.7(a). Moreover, this is a nonconsentable conflict of interest if Lawyer would not be able to provide competent and diligent representation to B as required under Rule 1.7(b) with the representation materially limited by the prohibition against revealing or using confidential information from C.

Additionally, under Rule 1.18(c) and Rule 1.9(b), Lawyer may not represent a client with interests materially adverse to C in the same or substantially related matter if Lawyer received information from C that could be either significantly harmful to C in that matter under Rule 1.18(c) (C as prospective client), or that is material to the matter under Rule 1.9(b) (C as former client). Exceptions are provided under Rule 1.9 and Rule 1.18, including if C gives informed consent confirmed in writing. However, certain disclosures need to be made to C to obtain informed consent, as discussed above. If Lawyer is prohibited from making those disclosures to obtain C’s informed consent, Lawyer is prohibited from representing B under both Rule 1.9, and Rule 1.18 unless another exception under Rule 1.18(d) applies.

[Inquiry #4:]{.casesection}

Can Lawyer use the funds provided by C for C’s purchase from B to fund B’s purchase from A?

[Opinion #4:]{.casesubsection}

No, not without C’s knowledge and informed consent and some appropriate legal arrangement (e.g. promissory note). Without C’s knowledge and informed consent and an appropriate legal arrangement, use of C’s money for the benefit of B is a misappropriation of C’s funds in violation of Rule 1.15-2(n) and Rule 8.4(b) and (c), as detailed below.

Lawyer cannot disburse funds from a residential real estate transaction until the deed is recorded. Accordingly, B is not entitled to possession or use of any of C’s funds held by Lawyer until the B to C deed is recorded.

The B to C deed cannot be recorded before the A to B deed is recorded. However, the A to B deed – which is entrusted property as defined in Rule 1.15-1(f) – cannot be recorded by Lawyer until Lawyer is in possession of funds the possession and use of which B is then currently entitled as discussed above, to pay the sales price due to A.

[Inquiry #5:]{.casesection}

Can Lawyer represent B and C in developing a legal arrangement under which B would become entitled to the possession and use of C’s funds prior to recordation of the B to C deed and can Lawyer draft the necessary documentation for that arrangement?

[Opinion #5:]{.casesubsection}

No. Such joint representation involves a nonconsentable conflict of interest under Rule 1.7.

The making of an appropriate arrangement between B and C under which B would gain entitlement to the possession and use of C’s funds prior to the recording of the B to C deed, and the drafting of appropriate documentation of that arrangement, presents another conflict of interest under Rule 1.7(a). Because the terms of this arrangement must be negotiated between B and C, Lawyer cannot jointly represent B and C and cannot draft the documents for the arrangement. *See, e.g.,* 2013 FEO 14 (nonconsentable conflict of interest barring joint representation in commercial real estate transaction unless the conditions listed therein are satisfied, including that contract terms have been finally negotiated prior to commencement of the representation and that there are no material contingencies to be resolved). *See also* 2013 FEO 4 (joint representation may be permissible in a residential real estate transaction because the contract to purchase is entered into prior to commencement of the representation and the lawyer has no obligation to bargain for either party).

*See* Opinion #3 above with respect to whether Lawyer could represent only B or only C.

[Inquiry #6:]{.casesection}

Are there other concerns about Lawyer’s participation in the closing of these transactions?

[Opinion #6:]{.casesubsection}

Yes, there are other issues Lawyer will have to consider before determining whether Lawyer can proceed.

Such issues may include the following:

1.  Whether Lawyer would be assisting any other person in engaging in a criminal offense or would be engaging in conduct constituting a criminal offense, implicating Rules 1.2(d), 8.4(a), and 8.4(b).

2.  Whether Lawyer would be engaging in conduct involving dishonesty, fraud, deceit, or misrepresentation, implicating Rule 8.4(c), such as in the identification of the owner in the preliminary opinion of title for the B to C transaction or in any other aspect. All documentation prepared by Lawyer must be accurate, including identifying the record owner in any preliminary opinion of title for a search period during which A is the record owner.

[Inquiry #7:]{.casesection}

If all conflicts, confidentiality, and funding issues are properly resolved, the transactions are permitted by law, and no other issues exist that would preclude Lawyer from proceeding with closing these transactions, what accountings must Lawyer do for these closings and to whom must the accountings be provided under Rule 1.15-3(e) and Rule 1.15-3(f)?

[Opinion #7:]{.casesubsection}

Accountings are due to A, B, and C pursuant to Rule 1.15-3(e) and (f).

For the A to B transaction, there must be a trust account client ledger and there must be a written accounting of receipts and disbursements (typically in the form of a settlement statement) for the funds provided by B or to which B becomes entitled to possess and use (e.g. under a promissory note) pursuant to Rule 1.15-3(b)(5) and Rule 1.15-3(e) and (f). The written accounting must be provided to B pursuant to Rule 1.15-3(e) and (f). The client ledger and the written accounting must show the receipt of the funds from or on behalf of B, including identification of funds provided for B’s use by C, and the disbursements of those funds.

For the B to C transaction, there must be a trust account client ledger and there must be a written accounting of receipts and disbursements (typically in the form of a settlement statement) for the funds provided by C or on behalf of C. The written accounting must be provided to C pursuant to Rule 1.15-3(e) and (f). The ledger and written accounting must show the receipt of the funds from or on behalf of C and the disbursements of those funds, including any conveyance of some portion of C’s funds to B for B’s use in the A to B transaction.

For both transactions, each seller must receive a written accounting of the sales proceeds to which the seller becomes the beneficial owner upon the recording of the applicable deed. Rule 1.15-3(f). This accounting must show all disbursements made from the seller’s proceeds, including all costs and fees deducted from the sales price due to the seller under the applicable contract.

Opinion #7 is limited to applying Rule 1.15-3(b)(5), Rule 1.15-3(e), and Rule 1.15-3(f); other authorities and obligations may require documents to be provided to other parties.

[Inquiry #8:]{.casesection}

Instead of being structured as A to B and B to C transactions, B enters into a contract to purchase with A and assigns his rights under that contract to C. B initially engages Lawyer for representation to close the sale from A to C and expects that Lawyer will also represent C. B does not want A or C to know certain information about the transaction. The assignment documentation does not disclose all information about the transaction such as the purchase price in the A to B purchase contract or the amount of the assignment fee to be paid to B. B wants the settlement statements prepared in a manner that does not disclose all information to A or C. Can Lawyer represent B and C and close this transaction?

[Opinion #8:]{.casesubsection}

This scenario presents many of the same issues and considerations discussed above. Lawyer must be able to disclose all information about the transaction to client C and cannot close the transaction if unable to disclose because of a duty of confidentiality to B. In addition, Lawyer must be able to be forthright with all parties and must be able to disclose to all parties any information as required by law. All documents, closing statements, and deeds prepared by Lawyer must be accurate in all respects. Lawyer must also provide accurate accountings to A and C. *See* Opinions #1, #3, #6, and #7.

[Inquiry #9:]{.casesection}

Could Lawyer represent A, B, and C in these transactions?

[Opinion #9:]{.casesubsection}

The same issues and considerations discussed above would apply if Lawyer wished to engage in the multiple representation of A, B, and C. *See* Opinions #1 through #8.

## Conflicts Involving the Lawyer's Business & Personal Interests

#### @MRPC18

::: legalcode
##### Current Clients -- Specific Rules

-   \(a\) A lawyer shall not enter into a business transaction with a client or knowingly acquire an ownership, possessory, security or other pecuniary interest adverse to a client unless:
    -   \(1\) the transaction and terms on which the lawyer acquires the interest are fair and reasonable to the client and are fully disclosed and transmitted in writing in a manner that can be reasonably understood by the client;
    -   \(2\) the client is advised in writing of the desirability of seeking and is given a reasonable opportunity to seek the advice of independent legal counsel on the transaction; and
    -   \(3\) the client gives informed consent, in a writing signed by the client, to the essential terms of the transaction and the lawyer's role in the transaction, including whether the lawyer is representing the client in the transaction.
-   \(b\) A lawyer shall not use information relating to representation of a client to the disadvantage of the client unless the client gives informed consent, except as permitted or required by these Rules.
-   \(c\) A lawyer shall not solicit any substantial gift from a client, including a testamentary gift, or prepare on behalf of a client an instrument giving the lawyer or a person related to the lawyer any substantial gift unless the lawyer or other recipient of the gift is related to the client. For purposes of this paragraph, related persons include a spouse, child, grandchild, parent, grandparent or other relative or individual with whom the lawyer or the client maintains a close, familial relationship.
-   \(d\) Prior to the conclusion of representation of a client, a lawyer shall not make or negotiate an agreement giving the lawyer literary or media rights to a portrayal or account based in substantial part on information relating to the representation.
-   \(e\) A lawyer shall not provide financial assistance to a client in connection with pending or contemplated litigation, except that:
    -   \(1\) a lawyer may advance court costs and expenses of litigation, the repayment of which may be contingent on the outcome of the matter;
    -   \(2\) a lawyer representing an indigent client may pay court costs and expenses of litigation on behalf of the client; and
    -   \(3\) a lawyer representing an indigent client pro bono, a lawyer representing an indigent client pro bono through a nonprofit legal services or public interest organization and a lawyer representing an indigent client pro bono through a law school clinical or pro bono program may provide modest gifts to the client for food, rent, transportation, medicine and other basic living expenses. The lawyer:
        -   \(i\) may not promise, assure or imply the availability of such gifts prior to retention or as an inducement to continue the client-lawyer relationship after retention;
        -   \(ii\) may not seek or accept reimbursement from the client, a relative of the client or anyone affiliated with the client; and
        -   \(iii\) may not publicize or advertise a willingness to provide such gifts to prospective clients.
    -   Financial assistance under this Rule may be provided even if the representation is eligible for fees under a fee-shifting statute.
-   \(f\) A lawyer shall not accept compensation for representing a client from one other than the client unless:
    -   \(1\) the client gives informed consent;
    -   \(2\) there is no interference with the lawyer's independence of professional judgment or with the client-lawyer relationship; and
    -   \(3\) information relating to representation of a client is protected as required by Rule 1.6.
-   \(g\) A lawyer who represents two or more clients shall not participate in making an aggregate settlement of the claims of or against the clients, or in a criminal case an aggregated agreement as to guilty or nolo contendere pleas, unless each client gives informed consent, in a writing signed by the client. The lawyer's disclosure shall include the existence and nature of all the claims or pleas involved and of the participation of each person in the settlement.
-   \(h\) A lawyer shall not:
    -   \(1\) make an agreement prospectively limiting the lawyer's liability to a client for malpractice unless the client is independently represented in making the agreement; or
    -   \(2\) settle a claim or potential claim for such liability with an unrepresented client or former client unless that person is advised in writing of the desirability of seeking and is given a reasonable opportunity to seek the advice of independent legal counsel in connection therewith.
-   \(i\) A lawyer shall not acquire a proprietary interest in the cause of action or subject matter of litigation the lawyer is conducting for a client, except that the lawyer may:
    -   \(1\) acquire a lien authorized by law to secure the lawyer's fee or expenses; and
    -   \(2\) contract with a client for a reasonable contingent fee in a civil case.
-   \(j\) A lawyer shall not have sexual relations with a client unless a consensual sexual relationship existed between them when the client-lawyer relationship commenced.
-   \(k\) While lawyers are associated in a firm, a prohibition in the foregoing paragraphs (a) through (i) that applies to any one of them shall apply to all of them.
:::

#### @ReMorse_Ga2013

##### Per Curium

This disciplinary matter is before the Court on a Petition for Voluntary Discipline filed by Respondent Jack O. Morse pursuant to Bar Rule 4-227(b)(2) before a formal complaint was issued. In his petition, Morse admits violating Rule 1.8(e) of the Georgia Rules of Professional Conduct set forth in Bar Rule 4-102(d). Although such a violation is punishable by public reprimand, Morse requests the imposition of a Review Panel reprimand. The State Bar has no objection.

Morse, who has been a member of the State Bar since 1972, admits that while representing a client in a personal injury claim, he lent the client \$1,400 for the client's use in avoiding foreclosure and possible jail time for his violation of probation. Although the client repaid the loan in full, Morse admits that he violated Rule 1.8(e). He asserts that while he has had three instances of prior discipline (having received a 90-day suspension in 1996, and Review Panel reprimands in both 1993 and 1998—one of which was for similar misconduct), he has had no disciplinary matters for an extended period of time. He further asserts that since 1998, he has shown a strong regard for the professional standards of conduct and asks that this Court consider, in mitigation, his cooperative attitude with disciplinary authorities and the fact that the violation occurred as a result of him attempting to assist the client, a longtime acquaintance.

Under these specific circumstances, we agree that imposition of a Review Panel reprimand is an appropriate sanction. Accordingly, we accept Morse's petition for voluntary discipline and hereby order that Morse receive a Review Panel reprimand in accordance with Bar Rules 4-102(b)(4) and 4-220(b) for his admitted violation of Rule 1.8(e).

##### Blackwell, Justice, concurring.

I concur fully in the opinion of the Court, but I write separately to remind our readers that a lawyer providing financial assistance to a litigation client is not *always* a violation of Rule 1.8(e). With two exceptions, Rule 1.8(e) provides that "a lawyer shall not provide financial assistance to a client in connection with pending or contemplated litigation." By its plain terms, the Rule only prohibits the provision of financial assistance to a litigation client to the extent of some "connection" between the financial assistance on the one hand, and the litigation or representation on the other.[^chap6-1] Absent such a "connection," a lawyer may provide financial assistance to a litigation client without running afoul of Rule 1.8(e).

[^chap6-1]: (n.2 in opinion) Such a connection might exist, for instance, if the lawyer intended the financial assistance to enable or encourage the client to retain the lawyer or to prosecute the litigation, if the client actually was encouraged or enabled by the financial assistance to retain the lawyer or to prosecute the litigation, or if the lawyer and client agreed that the financial assistance would be repaid from amounts awarded in the litigation. By the way, this list of circumstances that might suffice to show the requisite connection is not intended to be an exhaustive one.

This understanding not only is required by the plain terms of the Rule, but it also is perfectly consistent with the three purposes of Rule 1.8(e). First, Rule 1.8(e) is intended to preserve the loyalty and independence that the lawyer owes to the client, loyalty and independence that might be compromised if the lawyer obtained "too great a financial stake in the litigation." American Bar Association Model Rules of Professional Conduct, Rule 1.8, comment 10. Second, the Rule is intended to "prevent clients from selecting a lawyer based on improper factors," considering that "unregulated lending to clients might generate unseemly bidding wars for cases." Third, the Rule is intended to restrain the pernicious practices of barratry, maintenance, and champerty.[^chap6-2] As I see it, financial assistance to an existing client that has no connection whatsoever with the litigation or representation of the client does not offend any of the policies that the Rule is intended to promote.

[^chap6-2]: (n.4 in opinion) At common law, barratry was "the offence of frequently exciting and stirring up suits and quarrels between his majesty's subjects, either at law or otherwise." Maintenance was "an officious intermeddling in a suit that in no way belongs to one, by maintaining or assisting either party with money or otherwise, to prosecute or defend it." Champerty was a particular species of maintenance, namely "a bargain with a plaintiff or defendant to divide the land or other matter sued for between them, if they prevail at law; whereupon the champertor is to carry on the party's suit at his own expense."

This case is a little troubling to me because it appears from the record that Morse has been a friend of his client for a long time, such that he might have provided financial assistance to his client independent of the attorney-client relationship or the litigation, and indeed, even in the absence of an attorney-client relationship or litigation. Lawyers can be generous, and it is not uncommon for lawyers to help out their kin, their friends, and their neighbors. Nevertheless, Morse has unequivocally admitted a violation of Rule 1.8(e), and as such, he has implicitly admitted a connection between the financial assistance he provided and the litigation in which he represented his client. For that reason, I am content to join the Court in accepting his petition for voluntary discipline, and I am satisfied with the discipline that the Court has seen fit to impose. I am authorized to state that Justice Hunstein joins in this concurrence.

#### @CommitteeProfEthicsEtc_Iowa1982

This case involves review of a Grievance Commission report recommending that respondent be reprimanded for alleged ethical violations arising from a business transaction with a client. We adopt the recommendation.

From our de novo review of the record, we find the facts as follows. Respondent is a Cedar Falls attorney. He began to do tax and property work for Leonard O. Miller, a farmer, in 1951. Miller owned 100 acres of farmland adjacent to a country club near the city. In 1969, when he was 68, Miller became interested in developing the land for residential purposes. He employed a landscape architect and R. O. Schenk, of Schenk Engineering Company, to prepare a preliminary plat and market study.

When the preliminary work was completed, Miller brought Schenk to meet with respondent to discuss the project. Miller wished to proceed with the development but did not have sufficient funds to pay engineering costs. Schenk suggested that the three men form a corporation to which Miller would contribute the land, Schenk would contribute engineering services, and respondent would contribute legal services. They agreed the land was worth approximately \$400 an acre. Schenk estimated engineering costs at \$400 an acre, and he said legal costs were usually one half that amount.

After several conferences in early 1970, the three men formed a corporation, Union Township Development, Inc. Subsequently Miller conveyed the farmland to the corporation at a capitalized value of \$12,500 and received 400 shares of stock. Schenk gave the corporation a \$12,500 promissory note and also received 400 shares of stock. Respondent gave the corporation a \$6,250 promissory note and received 200 shares of stock. The promissory notes were interest free and due at the discretion of the corporation. They were to represent the services to be rendered by Schenk and respondent.

Development plans were premised on the corporation's ability to obtain financing on the security of the farmland. As it turned out, the corporation was unable to borrow money unless the three individuals would guarantee the obligation personally. They refused to do so, and financing was never obtained.

The trio met at least annually to discuss the development, but when Miller died on December 31, 1978, at the age of 77, the project was still at a stalemate. Respondent believed the parties had an oral agreement that if development did not occur he and Schenk would relinquish their interests in the corporation to Miller. Three days after Miller's death, he transferred his stock to the corporation. He asked Schenk to do the same thing, but Schenk refused, denying any obligation to do so.

Respondent was nominated in Miller's will as executor of his estate. He served in that capacity until Miller's two daughters expressed dissatisfaction with his role in Miller's conveyance of the farmland to the corporation. He then resigned as executor. Consistent with his view, he showed Miller as owner of all corporate stock in the preliminary probate inventory. The farmland was appraised at \$4,000 an acre.

Although respondent had expended \$900 in out-of-pocket expenses for the corporation and performed legal services worth more than \$6,000, he did not intend to seek payment. Schenk, however, maintained at the time of the grievance hearing that he still owned one half of the outstanding stock of the corporation.

The determinative question in our review is whether this evidence establishes a violation of the principle in DR5-104(A), which provides:

> A lawyer shall not enter into a business transaction with a client if they have differing interests therein and if the client expects the lawyer to exercise his professional judgment therein for the protection of the client, unless the client has consented after full disclosure.

In order to establish a violation of DR5-104(A) it is necessary to show that the lawyer and client had differing interests in the transaction, that the client expected the lawyer to exercise his professional judgment for the protection of the client, and that the client consented to the transaction without full disclosure.

The definitions section of the code of professional responsibility defines "differing interests":

> "Differing interests" include every interest that will adversely affect either the judgment or loyalty of a lawyer to a client, whether it be a conflicting, inconsistent, diverse, or other interest.

Miller and Mershon plainly had differing interests in at least two aspects of the transaction. One was the issue of giving respondent a present interest in the corporation in anticipation of future legal services. The fee agreement was made during the existence of the attorney-client relationship and thus was subject to the general principles governing attorney-client transactions. Because respondent's fee was tied to the amount of his stock in the corporation, he and Miller had differing interests concerning the extent of respondent's stock ownership. Another differing interest involved making respondent a debtor of the corporation to assure that the services would be performed. Because Miller's interest was aligned wholly with the corporation, he and respondent had differing interests with respect to respondent's promissory note.

No dispute exists that Miller relied on respondent to exercise his professional judgment to protect him. One respect in which respondent did so was in preparing a written agreement to assure that Miller was reimbursed from the first profits of the corporation for the preincorporation expenses of preliminary studies. This, however, was the only agreement of the parties that was reduced to writing.

The fighting issue before the Commission was whether respondent made full disclosure to Miller within the meaning of the Canon before Miller entered the transaction. If full disclosure means only that respondent made Miller fully aware of the nature and terms of the transaction, this requirement was satisfied. Nothing was hidden from Miller, and he was an active participant in the transaction. Full disclosure, however, means more than this.

Because of the fiduciary relationship which exists, the attorney

> has the burden of showing that the transaction was in all respects fairly and equitably conducted; that he fully and faithfully discharged all his duties to his client, not only by refraining from any misrepresentation or concealment of any material fact, but by active diligence to see that his client was fully informed of the nature and effect of the transaction proposed and of his own rights and interests in the subject matter involved, and by seeing to it that his client either has independent advice in the matter or else receives from the attorney such advice as the latter would have been expected to give had the transaction been one between his client and a stranger.

Respondent acknowledges he did not suggest to Miller that he obtain independent advice. The record does not show he otherwise gave Miller the kind of advice Miller should have had if the transaction were with a stranger. Respondent let Schenk estimate the value of his legal services and thus the extent of respondent's stock ownership without any investigation to determine whether the estimate was accurate. Nor did he suggest to Miller that he make such investigation. If Schenk's estimate was generous, the effect may have been to chill respondent's scrutiny of the benchmark for the valuation, which was Schenk's valuation of his own services. Furthermore there was no discussion or investigation concerning the reasonableness or wisdom of tying respondent's fee for future services to a present twenty percent interest in the corporation. Respondent acknowledges that the arrangement was at least a technical violation.

Nothing was done to assure that Miller would get his farm back if either Schenk or respondent did not perform or if the development should not be undertaken. Nothing was done to protect Miller or his estate in the event of the death of any of the parties. The promissory notes could hardly have been on more favorable terms to the debtors. The record does not show whether Miller was informed of the difficulty the corporation might have in enforcing respondent's obligation. So far as the record shows, Miller was not told of any possible effect of respondent's differing interests on the exercise of his professional judgment.

The Commission found respondent is forthright and honest and gained no profit from the transaction. The record confirms this finding. As the Commission also found, however, a violation of DR5-104(A) was nevertheless established. Respondent had three alternatives when the Schenk proposal was first made. The safest and perhaps best course would have been to refuse to participate personally in the transaction. Alternatively, he could have recommended that Miller obtain independent advice. Finally, if Miller refused to seek independent advice or respondent did not recommend he do so, he could have made the least desirable choice. He could have attempted to meet the high standard of disclosure outlined in this opinion.

Having chosen to enter the transaction without recommending that Miller obtain independent advice, respondent was obliged to make full disclosure. Because the record does not show full disclosure was made before Miller consented to the transaction, a violation of DR5-104(A) has been established. This is true even though respondent did not act dishonestly or make a profit on the transaction.

In accordance with the Commission recommendation, we reprimand him for the violation.

#### @SaladiniRighellis_Mass1997

The plaintiff, Lisa Saladini, appeals from the decision of a judge in the Superior Court dismissing her complaint, sua sponte, on the ground that a written agreement she had with the defendant, George P. Righellis, was champertous and unenforceable. Saladini had sought a declaratory judgment establishing her rights under the agreement. We granted Saladini's application for direct appellate review to consider whether we should continue to enforce the doctrine. We rule that the common law doctrines of champerty, barratry, and maintenance no longer shall be recognized in Massachusetts. We reverse the judgment entered in the Superior Court and remand this case for further proceedings.

On September 23, 1992, Saladini and Righellis entered into a written agreement pursuant to which Saladini agreed to advance funds to Righellis to allow him to pursue potential legal claims he had arising out of his interest in real estate in Cambridge, known as Putnam Manor. In return, Righellis agreed that, if pursuit of his claims yielded any recovery, the first amount recovered would be used to reimburse Saladini, and that Saladini would, in addition, receive 50% of any net recovery remaining after payment of attorney's fees. Saladini, herself, had no interest in Putnam Manor.

Saladini thereafter advanced funds to Righellis that he used to retain an attorney under a contingent fee agreement to bring a lawsuit and to pursue his legal claims. At some point Righellis became dissatisfied with that attorney's representation and, with the concurrence of Saladini, hired a new lawyer, Robert Potters, to replace him. Righellis signed a new contingent fee agreement with Potters.

The original agreement between Saladini and Righellis did not anticipate retaining a second attorney to represent Righellis in the Putnam Manor lawsuit. Saladini maintains that to deal with this circumstance, she and Righellis agreed that each would pay one-half of the retainer required by Potters, each would pay one-half of the litigation disbursements, and that in all other respects the terms of their original agreement would remain in effect. No new or amended agreement was executed, but Saladini did pay one-half of the retainer to Potters and one-half of the litigation disbursements. All told, Saladini advanced a total of \$19,229 to Righellis.

At some point Righellis settled the Putnam Manor lawsuit, with the defendants in that case agreeing to pay him \$130,000. The first payment of \$10,000 was paid on or about November 2, 1994, with the balance due on January 11, 1995. Neither Potters nor Righellis informed Saladini that a settlement had been reached, or that the first settlement funds had been received.

When Saladini became aware of the settlement, she filed suit, seeking to establish her rights under the agreement. She also sought, and a judge in the Superior Court granted, injunctive relief, enjoining Righellis and Potters from disbursing any of the settlement funds until her claims had been adjudicated.

In November, 1995, Righellis filed a motion for summary judgment that Saladini opposed. After reviewing the submissions of the parties, a judge in the Superior Court, sua sponte, invited both parties to submit memoranda on the issue whether the agreement between Saladini and Righellis was champertous. A hearing followed and, in September, 1996, another judge ruled that the agreement was champertous and unenforceable as against public policy. She ordered that Saladini's complaint be dismissed in its entirety. A judgment to that effect was entered on September 24, 1996. Saladini appealed. A judge granted Saladini's motion to continue the preliminary injunction pending her appeal.

Champerty has been described as the unlawful maintenance of a suit, where a person without an interest in it agrees to finance the suit, in whole or in part, in consideration for receiving a portion of the proceeds of the litigation. We described the doctrine as a "narrow and somewhat technical concept," a type of maintenance that occurs when a person engages in "officious intermeddling in a suit that no way belongs to one, by maintaining or assisting either party with money or otherwise, to prosecute or defend it."

The doctrine has a long and, in this country, checkered history. The ancient prohibition against champerty arose in feudal England. More recently the doctrine has been viewed as a check on frivolous or unnecessary litigation, or a mechanism to encourage the settlement of disputes without recourse to litigation. The extent to which courts, here, accepted the doctrine has varied. In some States, champerty was never adopted, or has been abandoned. In others, the doctrine was given narrow application. Massachusetts followed the common law prohibition against champerty, although we have never enforced the doctrine to the same extent as English courts.[^chap6-3] Nevertheless, under our own development of the doctrine we have little doubt that the agreement between Saladini and Righellis would be champertous were we to continue to recognize the offense. We no longer are inclined to do so.

[^chap6-3]: (n.4 in opinion) For example, we consistently have held that it is not unlawful "to engage in the business of buying choses in action and enforcing them by suit if necessary," although under English common law assignments of choses in action are within the scope of champerty. We have not prohibited agreements otherwise champertous where the party has an independent interest in the suit. We also have recognized the validity of contingent fee arrangements with attorneys, which otherwise would be champertous.

We have long abandoned the view that litigation is suspect, and have recognized that agreements to purchase an interest in an action may actually foster resolution of a dispute. In more recent cases we have questioned whether the doctrine continues to serve any useful purpose. In *McInerney*, we noted that "the decline of champerty, maintenance, and barratry as offences is symptomatic of a fundamental change in society's view of litigation---from ‘a social ill, which, like other disputes and quarrels, should be minimized' to ‘a socially useful way to resolve disputes.'" In *Christian v. Mooney*, we declined to consider whether an agreement between a "bounty hunter in troubled titles" and other plaintiffs in a suit was champertous because that issue was not contested by the parties to the agreement---even though that plaintiff's repeated instigation of litigation regarding troubled real estate titles was the very conduct traditionally condemned as violative of the prohibition against champerty. Most recently, in *Berman v. Linnane*, we declined to strike down a contingent fee agreement that did not satisfy the requirements of S.J.C. Rule 3:05 as champertous, relying rather on "the public policy against the recovery of excessive fees" to limit the financial recovery by an attorney. We observed in that case that "at least as to lawyers, other principles fulfill whatever purpose champerty once had." These decisions all reflect the change in our attitude toward the financing of litigation.

We also no longer are persuaded that the champerty doctrine is needed to protect against the evils once feared: speculation in lawsuits, the bringing of frivolous lawsuits, or financial overreaching by a party of superior bargaining position. There are now other devices that more effectively accomplish these ends. Our rule governing contingent fees between attorneys and clients is based on the principle that an attorney's fee must be reasonable. We also recognize a public policy against the recovery of excessive fees. Additional devices include Mass. R. Civ. P. 11, providing sanctions for misconduct, and G. L. C. 231, § 6F, regulating the bringing of frivolous lawsuits. General Laws c. 93A, and the doctrines of unconscionability, duress, and good faith, establish standards of fair dealing between opposing parties. To the extent that we continue to have the concerns that the doctrine of champerty was thought to address, we conclude that it is better to do so directly, rather than attempting to mold an ancient doctrine to modern circumstances.[^chap6-4] As Justice Holmes, then a member of this court, said a century ago: "It is revolting to have no better reason for a rule of law than that so it was laid down in the time of Henry IV. It is still more revolting if the grounds upon which it was laid down have vanished long since, and the rule simply persists from blind imitation of the past."

[^chap6-4]: (n.6 in opinion) The doctrine of champerty may also be unworkable or have harsh results. Rather than punishing the owner of the legal claim who has entered into a champertous agreement, the doctrine bestows on him a windfall. In this case, for example, Righellis would be permitted to retain the full benefit of the positive result achieved in the Putnam Manor lawsuit, while he would not have to honor his obligations to Saladini, the person whose support made pursuit of the lawsuit possible. A defendant sued in a champerty-supported litigation may not assert the champerty as a defense, but a court may refuse to enforce a champertous agreement even where the defense of champerty has not been asserted.

Other States that no longer recognize the doctrine of champerty have continued to scrutinize an agreement to finance a lawsuit with care. We shall do likewise. This means that if an agreement to finance a lawsuit is challenged, we will consider whether the fees charged are excessive or whether any recovery by a prevailing party is vitiated because of some impermissible overreaching by the financier. Judges also retain their inherent power to disapprove an attorney's fee that is unreasonable. We shall be guided in our analysis by a rule of what is fair and reasonable, looking to all of the circumstances at the time the arrangement is made to determine whether the agreement should be set aside or modified. In this case, for example, had the agreement been challenged, relevant factors might have included the respective bargaining position of the parties at the time the agreement was made, whether both parties were aware of the terms and consequences of the agreement, whether Righellis may have been unable to pursue the lawsuit at all without Saladini's funds, and whether the claim by Righellis that he will receive but \$35,000 of the total \$130,000 settlement award if Saladini prevails is unreasonable in the circumstances. We observe that before the judge raised the issue, Righellis had never challenged the validity of his agreement with Saladini. The record before us does not permit any conclusion regarding the reasonableness of the agreement between Righellis and Saladini on the one hand, or Righellis and Potters on the other. We see no reason why Righellis should be the beneficiary of any windfall, or why any adjustment to the financing arrangement---if appropriate at all---should be made solely at Saladini's expense. If pursued, those matters can be decided by the trial judge.

#### @ReStateGrandJury_NJ2009

Confronted with a grand jury inquiry that commanded the testimony of several of its employees, an employer elected to provide and pay for counsel to those employees for purposes of that investigation. Fearing that having individual employees/grand jury witnesses represented by counsel retained and compensated by the putative target of the grand jury inquiry violated several of the Rules of Professional Conduct, the State moved to disqualify those counsel. The trial court denied that application, limited the amount of information to be transmitted by such counsel to the employer, and, further, imposed restrictions both on the ability of the employer to discontinue paying the fees of counsel for the employees as well as on the ability of those counsel to discontinue representing the subpoenaed employees.

Regardless of the setting—whether administrative, criminal or civil, either as part of an investigation, during grand jury proceedings, or before, during and after trial—whether an attorney may be compensated for his services by someone other than his client is governed in large measure by Rule 1.8(f) and, to a lesser extent, Rule 1.7(a) and Rule 5.4(c). The overarching Rule, which purposely is written in the negative, forbids a lawyer from "accepting compensation for representing a client from one other than the client unless \[three factors coalesce\]: (1) the client gives informed consent; (2) there is no interference with the lawyer's independence of professional judgment or with the lawyer-client relationship; and (3) information relating to representation of a client is protected" as provided in the Rules. A straightforward application of Rules 1.7(a), 1.8(f) and 5.4(c) requires that we affirm the order of the trial court.

[I.]{.casesection}

The operative facts on which this appeal arise are readily stated. The State commenced a grand jury investigation into whether a corporate contractor had submitted fraudulent invoices for services purportedly rendered to a county government. That inquiry focused primarily on the contractor and three of its employees. In response, the company arranged for counsel for its employees. The company entered into four separate retainer agreements with four separate lawyers, three of whom were assigned to represent, respectively, the three specific employees noted, and the fourth was retained to represent "all non-target current and former employees of \[the company\] in connection with the current state grand jury investigation."

The retainer agreements with each of the four lawyers, however, shared common characteristics and were, in all substantive and material respects, indistinguishable. A typical retainer agreement provided (1) that the company "will be ultimately responsible to the law firm for all reasonable and necessary legal fees and expenses incurred in this matter;" (2) that the "undertaking by the company is made with the express understanding that the sole professional obligation of the law firm will be to \[the named employee;\]" (3) that the "law firm is not required to disclose any legal strategy, theory, plan of action, or the like, to the company;" (4) that "payment of legal fees by the company to the law firm in no way depends upon any such disclosure;" (5) that "no professional relationship will arise between the company and the law firm as a result of the rendering of legal services by the law firm or the payment of legal fees and expenses by the company;" (6) that "the reimbursement of legal fees and expense is neither conditioned upon nor dependent upon the law firm's cooperation with the company or any other party;" (7) that while "detailed invoices will be provided to \[the represented employee,\] to preserve the attorney/client privilege, only summary invoices will be submitted to the company;" and (8) that the company would be responsible to pay those invoices "upon receipt."

Based on the company's retention of separate counsel for each of three employees identified by the State, the company wrote to each such employee, informing them that:

> As you know, the New Jersey Attorney General's office served \[the company\] with a Grand Jury subpoena seeking various billing and payroll records related to \[the company\]'s contract with \[the specified county government\]. The company has been fully cooperative with the State's investigation.
>
> Recently the Attorney General's office has begun interviewing some of our employees at the identified project. Given your position with the company and involvement in this project, and based upon the advice of our attorneys in New Jersey, we believe it would be prudent to retain separate counsel to represent you personally in connection with the State's investigation. Accordingly, \[the company\] has retained \[a specially retained lawyer\] to represent you in connection with the State's investigation. You do not have to use \[that specially retained lawyer\] as your attorney. You are free to hire your own attorney, at your own costs.
>
> You should not interpret this decision to mean that \[the company\] believes there to have been any illegal activity in this matter on the part of any company employee. Rather, it is based upon the recognition that your personal rights may conflict with the interests of the company. While \[the company\] agrees to pay for your legal representation in this matter, please understand that it has no obligation to do so and may stop paying those legal fees and costs at any time, should it believe it appropriate to do so.
>
> \[Your specially retained lawyer\] may be reached at \[\_\_\_\_\]. His firm address is: \[\_\_\_\_\_\].
>
> Please expect \[your specially retained lawyer\] to contact you directly to arrange a convenient time to meet and discuss this matter. Please feel free to contact me directly or speak with \[the company's local counsel\] if you have any questions regarding this matter.
>
> Very truly yours,
>
> /s/ Senior Vice President and General Counsel

The company also announced to all other employees that the company had retained a lawyer—free of charge to the employees—with whom those employees could consult and who was available to represent those employees in respect of the grand jury inquiry.

In time, two of the four lawyers retained by the company to represent its employees were subpoenaed to appear before the grand jury; they declined to appear, and the State later withdrew those subpoenas. The State then notified the company that it, along with several unnamed employees, had been designated as targets of the grand jury's investigation, and later served grand jury subpoenas for the company's records in respect of the retention of counsel for its employees. The company complied with that subpoena by producing responsive but non-privileged documents.

The State moved before the Superior Court to disqualify the counsel retained by the company to represent its employees "from further participation in this matter, pursuant to Rule 1.7, Rule 1.8 and Rule 1.10." In response, each of the employees to whom the company had provided counsel to date—the three identified "target" employees and two additional "nontarget" employees—submitted certifications asserting that none of them could afford to retain separate counsel, and that each was satisfied with and wished to remain with their then counsel.

The trial court noted at the outset that it "view\[ed the company's\] conduct as one that is certainly to be appreciated." Addressing the caliber of the lawyers retained by the company for its employees, the trial court explained that "as a major corporation, \[the company\] didn't go out and hire some low-level attorney. They went out and hired competent, knowledgeable, respected attorneys\[.\]" Focusing on the application of the Rules of Professional Conduct to the State's motion for disqualification, the court first observed that Rule 1.5 "talks about fees being reasonable \[and t\]hat is not an issue before the Court." Moving on to the application of Rule 1.6, which addresses the confidentiality of information between a lawyer and his client, the trial court remarked that the retained lawyers had provided certifications and sample redacted bills. Agreeing that the procedure employed was proper, the trial court emphasized that "the only thing that I would require going forward is that all of the bills sent to \[the company\] be redacted and that no specific information be detailed in the billing."

Turning to Rule 1.7, the general conflict of interest rule, the trial court concluded that, "at least at this point, there's been no demonstration that there is even a conflict and even if there were, these employees have the right to waive that conflict." It also declared itself "satisfied that there has been informed consent given by all of the employees by way of what they have put in the certifications." It concluded that

> "the Court finds nothing improper about the attorneys that have been retained by \[the company.\] In fact, the Court would go further and say that \[the company\] acted responsibly, quite frankly, and with corporate policy and, quite frankly, having been advised of the reputation of these attorneys. And clearly the understanding between the company and these attorneys was spelled out in not only the retainer agreements, but in previous letters before all this was signed."

It added, however, some restrictions: "that \[the company\] and the individual attorneys, prior to ending any relationship for payment, would have to make application to the Court\[,\]" and that counsel were to "redact the billings to cure any notion that the State may have that somehow the billings will reveal significant aspects of \[the grand jury\] investigation."

The trial court entered an order that denied the State's motion to disqualify counsel. More specifically, it

> FURTHER ORDERED that before \[the company\] may cease paying any of the attorney's legal fees and costs, \[the company\] shall provide notice to the Court and all parties, and the Court shall conduct a hearing on the issue of whether \[the company\] may cease paying such legal fees and costs; and
>
> IT IS FURTHER ORDERED that before any of the attorneys may withdraw from this case based upon the refusal of \[the company\] to pay the attorney's legal fees and costs, such attorney shall provide notice to the Court and all parties, and the Court shall conduct a hearing on the issue of the attorney's request to withdraw; and
>
> IT IS FURTHER ORDERED that the attorneys henceforth shall submit to \[the company\] legal bills either in summary form or with all detailed information redacted therefrom.

The State sought leave to appeal that determination and, in an unpublished order, the Appellate Division denied that application. It then moved before this Court, seeking leave to appeal the trial court's order and other ancillary relief. We also granted leave to the Association of Criminal Defense Lawyers of New Jersey (ACDL-NJ) to appear as amicus curiae. For the reasons that follow, we affirm the order of the trial court.

[II.]{.casesection}

According to the State, a per se conflict of interest arises whenever, as here, two facts contemporaneously appear: a target in a grand jury investigation unilaterally selects and retains a lawyer to represent potential witnesses against it, *and* the lawyer relies on the target for payment of legal fees. In the State's view, that arrangement will split the attorney's loyalty and will discourage the lawyer from counseling the client to cooperate with the State, even when cooperation might be in the client's best interest. It asserts that the perceived effect of allowing a target to select and pay for counsel for the witnesses against it is to irreparably taint the proceedings. The State also claims that such a conflict cannot be waived and that, even if it could be waived, a waiver could only be demonstrated through the live testimony of the witnesses, and not, as was done here, via certifications.

The lawyers whose disqualification is sought counter that Rule 1.8(f) clearly contemplates an employer designated as a grand jury "target" providing and paying for separate counsel for its employees during that grand jury inquiry. They reject the State's claim that, in the criminal law setting, the better rule is the imposition of a per se conflict. Finally, they assert that, even if a potential conflict of interest exists, it has been effectively waived. Amicus ACDL-NJ repeats those arguments.

The company echoes the arguments advanced both by the lawyers whose disqualification is sought and by amicus, and further asserts that, under the laws of its place of incorporation, it has an obligation to provide counsel to its employees, noting that, absent counsel provided by and paid for by the company, most of its employees would be unable to afford a lawyer.

[III.]{.casesection}

"Our evaluation of an actual or apparent conflict does not take place in a vacuum, but is, instead, highly fact specific." "In that respect, the Court's attention is directed to something more than a fanciful possibility." "To warrant disqualification in this setting, the asserted conflict must have some reasonable basis."

The State asserts that a target of a grand jury inquiry providing and paying for the lawyers who will represent the target's employees before the very grand jury considering the target's culpability creates an insoluble conflict not subject to waiver. Although the State's arguments possess considerable initial appeal, in light of modern changes in the manner in which attorney-client relationships are to be viewed, we are constrained to disagree.

No doubt, it long has been the law of this State that it is "improper for \[the attorney for an employee\] to have accepted the organization's promise to pay his bill, for such an arrangement has the inherent risk of dividing an attorney's loyalty between \[his client\] and \[his client's\] employer who will pay for the services." In those instances, we have concluded that "a conflict of interest inheres in every such situation\[,\]" one that cannot be waived "when the subject matter is crime and when the public interest in the disclosure of criminal activities might thereby be hindered." Reasoning that "an attorney must realize that the employer who agrees to pay him is motivated by the expectation that he will be protected," we have concluded that

> it is inherently wrong to represent both the employer and the employee if the employee's interest may, and the public interest will, be advanced by the employee's disclosure of his employer's criminal conduct. For the same reasons, it is also inherently wrong for an attorney who represents only the employee to accept a promise to pay from one whose criminal liability may turn on the employee's testimony.

\[New Jersey R.P.C.\] Rule 1.8(f) \[...\] provides in full as follows:

> A lawyer shall not accept compensation for representing a client from one other than the client unless:
>
> \(1\) the client gives informed consent;
>
> \(2\) there is no interference with the lawyer's independence of professional judgment or with the lawyer-client relationship; and
>
> \(3\) information relating to representation of a client is protected as required by Rule 1.6.

However, Rule 1.8(f) does not exist in a vacuum: two other Rules directly touch on the question presented. First, Rule 1.7(a) forbids a lawyer from representing a client "if the representation involves a concurrent conflict of interest." That Rule recognizes "a concurrent conflict of interest if: there is a significant risk that the representation of one or more clients will be materially limited by the lawyer's responsibilities to a third person or by a personal interest of the lawyer." Rule 1.7(a)(2). Second, Rule 5.4(c) provides that "a lawyer shall not permit a person who recommends, employs, or pays the lawyer to render legal services for another to direct or regulate the lawyer's professional judgment in rendering such legal services."

Our task, then, is to harmonize Rules 1.7(a)(2), 1.8(f) and 5.4(c) \[and their\] seemingly overlapping mandates so as to give proper guidance on whether, and under what circumstances, a lawyer may represent a client when the fees and costs incurred are being paid by another.

The starting point for analysis must be the Rule that most specifically addresses the question of when a lawyer can represent a client while being paid by another: Rule 1.8(f). That Rule makes clear that three factors must coalesce in order to allow a lawyer paid by a third party to represent a client: the client must give informed consent; the lawyer's independent professional judgment and the lawyer-client relationship must be maintained sacrosanct; and no improper disclosures relating or referring to the representation can be made. However, the considerations that animate Rule 1.7(a)(2)—that there be no concurrent conflict of interest—and Rule 5.4(c)—that no third party may influence the lawyer's professional judgment— also are relevant and must be addressed.

A synthesis of Rules 1.7(a)(2), 1.8(f) and 5.4(c) yields a salutary, yet practical principle: a lawyer may represent a client but accept payment, directly or indirectly, from a third party provided each of the six conditions is satisfied. Those conditions are:

\(1\) The informed consent of the client is secured. In this regard, "'informed consent' is defined as the agreement by a person to a proposed course of conduct after the lawyer has communicated adequate information and explanation about the material risks of and reasonably available alternatives to the proposed course of conduct."

\(2\) The third-party payer is prohibited from, in any way, directing, regulating or interfering with the lawyer's professional judgment in representing his client.

\(3\) There cannot be any current attorney-client relationship between the lawyer and the third-party payer.

\(4\) The lawyer is prohibited from communicating with the third-party payer concerning the substance of the representation of his client. The breadth of this prohibition includes, but is not limited to, the careful and conscientious redaction of all detail from any billings submitted to the third-party payer.

\(5\) The third-party payer shall process and pay all such invoices within the regular course of its business, consistent with manner, speed and frequency it pays its own counsel.

\(6\) Once a third-party payer commits to pay for the representation of another, the third-party payer shall not be relieved of its continuing obligations to pay without leave of court brought on prior written notice to the lawyer and the client. In such an application, the third-party payer shall bear the burden of proving that its obligation to continue to pay for the representation should cease; the fact that the lawyer and the client have elected to pursue a course of conduct deemed in the client's best interests but disadvantageous to the third-party payer shall not be sufficient reason to discontinue the third-party payer's continuing obligation of payment. If a third-party payer fails to pay an employee's legal fees and expenses when due, the employee shall have the right, via a summary action, for an order to show cause why the third-party payer should not be ordered to pay those fees and expenses.

We now apply this principle, and its conditions, to the case on appeal.

*Informed consent.* Each of the letters from the company to the individual employees provided that the employee "did not have to use \[the assigned counsel\] as your attorney. You are free to hire your own attorney, at your own costs." As conceded by counsel for the company during oral argument, that "take-it-or-leave-it" approach, on its face, does not satisfy the requirement that the employee's acceptance of counsel be based on informed consent. Therefore, presumptively, the retention of counsel here does not comply with Rule 1.8(f)(1). However, as acknowledged by the trial court, each of the employees certified that he was satisfied with the assigned counsel and wished to remain as that counsel's client. Therefore, we conclude that the arrangement approved by the trial court below is satisfactory, albeit with the caveat that, in the future, no such limitations on the choice of counsel should be communicated or imposed on the employee/client save for reasonable limitations on fees and expenses.

*Interference with the lawyer's professional judgment.* As clearly set forth in the separate retention letters between the lawyers and the company, each of the lawyers explained that "the sole professional obligation of the law firm will be to \[the assigned client\]." For the avoidance of future doubt, such retention letters should clearly and conspicuously note that nothing in the representation shall limit the lawyer's responsibilities to the client, as provided in Rule 1.8(f)(2), and that the third-party payer shall not, in any way, seek to "direct or regulate the lawyer's professional judgment in rendering such legal services." Rule 5.4(c).

*Current representation.* The record is clear that none of the lawyers selected to represent the individual employees had any current relationship with the company, and that "no professional relationship will arise between the company and the law firm as a result of the rendering of legal services by \[the assigned lawyer\] or the payment of legal fees and expenses by the company." Those facts, standing alone, constitute a sufficient showing in favor of permitting this representation. Again, as an aid in future matters, the retention letters should clearly spell out that the lawyer does not have a professional relationship with the third-party payer.

*Prohibited communications.* Each of the retention letters made clear that the lawyer "is not required to disclose any legal strategy, theory, plan of action, or the like, to the company and payment of legal fees by the company to the law firm in no way depends upon any such disclosure." In this respect, the better practice is to affirmatively state that the lawyer will not disclose any part of the substance of the representation of the client to the third-party payer. Consistent with that representation, all billings from the lawyer to the third-party payer must have any detail information redacted, simply stating the sum due for services rendered and the sum due for expenses incurred. Because these latter conditions were imposed by the trial court, the retention letters, as modified by the trial court, clearly comply with the requirements we have imposed.

*Prompt and continued payment.* Once an employer commits to paying the legal fees and expenses of its employees, it scrupulously must honor that commitment. Also, if the employer wishes to discontinue paying the legal fees and expenses of one or more of its employees, it may only do so by leave of court granted. Because this condition also was imposed by the trial court and was agreed to by all parties, the arrangements at issue are satisfactory.

In sum, through the combined product of the good faith of an employer, the diligence of competent counsel and the exercise of a trial court's supervisory authority, the net result of the company's retention and payment of counsel for its employees complies with the Rules of Professional Conduct. For these reasons, the trial court properly denied the State's motion to disqualify counsel.

#### @NegotiatingPrivateEmploymentOpposing_NCStateBar2017

Opinion rules that a lawyer may not negotiate for employment with another firm if the firm represents a party adverse to the lawyer’s client unless both clients give informed consent.

**Note:** This opinion is limited to the explanation of the professional responsibilities of a lawyer moving from one place of private employment to another. Rule 1.11(d)(2)(B) governs the conduct of a government lawyer seeking private employment.

[Inquiry:]{.casesection}

May a lawyer negotiate for employment with a law firm that represents a party on the opposite side of a matter in which the lawyer is also representing a party?

[Opinion:]{.casesubsection}

Yes, with client consent.

A lawyer shall not represent a client if the representation of a client may be materially limited by a personal interest of the lawyer unless the lawyer reasonably believes that he can provide competent and diligent representation to the affected client and the client gives informed consent, confirmed in writing. Rule 1.7(b)(2). As observed in Rule 1.7, cmt. \[10\], when a lawyer has discussions concerning possible employment with an opponent of the lawyer’s client, or with a law firm representing the opponent, such discussions could materially limit the lawyer’s representation of the client.

On the same issue, ABA Formal Ethics Op. 96-400 (1996) advises that there are two overriding factors affecting the “likelihood that a conflict will eventuate” and “materially interfere with the lawyer’s independent professional judgment in considering alternatives or foreclosing courses of action”: the nature of the lawyer’s role in the representation of the client; and the extent to which the lawyer’s interest in the firm is concrete, and has been communicated and reciprocated. The ABA opinion states:

> the likelihood that a lawyer’s job search will adversely affect his “judgment in considering alternatives or foreclosing courses of action” is far greater when the lawyer has an active and material role in representing a client. Thus, if the posture of the case is such that there is no call on the lawyer’s judgment in representing a client during the period of his job search, it is not likely that his search and negotiations will adversely affect his judgment. Furthermore, if a lawyer’s interest in another firm, or its interest in him, is not reciprocated, it seems unlikely, in most cases, that such unreciprocated interest will have a material effect on a lawyer’s judgment in a matter between them.

While the exact point at which a lawyer’s own interest may materially limit his representation of a client may vary, the committee believes that clients, lawyers, and their firms are all best served by a rule that requires consultation and consent at the earliest point that a client’s interests could be prejudiced.

The ABA opinion concludes that a lawyer who is interested in negotiating employment with a firm representing a client’s adversary must obtain the client’s consent before engaging in substantive discussions[^chap6-5] with the firm or the lawyer must withdraw from the representation.

[^chap6-5]: (n.1 in opinion) A substantive discussion entails a communication between the job-seeking lawyer and the hiring law firm about the job-seeking lawyer’s skills, experience, and the ability to bring clients to the firm; and the terms of association. ABA Formal Ethics Op. 96-400 (1996). Thus there is a two-prong test for “substantive discussions.” There must be (1) a discussion/negotiation that is (2) substantive. Sending a resume blind to a potential employer is not a “discussion.” Speaking generally with a colleague at a social event about employment opportunities is not “substantive.”

*The Restatement (Third) of the Law Governing Lawyers* advises that once the discussion of employment has become concrete and the interest is mutual, the lawyer must promptly inform the client; without effective client consent, the lawyer must terminate all discussions concerning the employment, or withdraw from representing the client. *Restatement (Third) of the Law Governing Lawyers: A Lawyer’s Personal Interest Affecting the Representation of a Client*, § 125, cmt. d (2000). See also Kentucky Ethics Op. E-399 (1998) (lawyer may not negotiate for employment with another firm where firms represent adverse parties and lawyer is involved in the client’s matter or has actual knowledge of protected client information, unless the client consents to negotiation).

We agree: a job-seeking lawyer who is representing a client, or has confidential information about the client’s matter, may not engage in substantive negotiations for employment with the opposing law firm without the client’s informed consent.

To obtain the client’s informed consent, the job-seeking lawyer must explain to the client the current posture of the case, including what, if any, additional legal work is required, and whether another firm lawyer is available to take over the representation should the lawyer seek to withdraw. If the client declines to consent, the job-seeking lawyer must either cease the employment negotiations until the client’s matter is resolved or withdraw from the representation but only if the withdrawal can be accomplished without material adverse effect on the interests of the client. Rule 1.16(b)(1). Because personal conflicts of interests are not imputed to other lawyers in the firm, another lawyer in the firm may continue to represent the client. Rule 1.10(a).

Similarly, the hiring law firm must not engage in substantive employment negotiations with opposing counsel unless its own client consents. If the client does not consent, the firm must cease the employment negotiations or withdraw from the representation. The firm may only withdraw if the withdrawal can be accomplished without material adverse effect on the interests of the client. Rule 1.16(b) (1).

#### @DisciplinaryCounselSarver_Ohio2018

Respondent, Jason Allan Sarver, of Rockbridge, Ohio, Attorney Registration No. 0082073, was admitted to the practice of law in Ohio in 2007.

In a formal complaint certified to the Board of Professional Conduct on April 6, 2017, relator, disciplinary counsel, charged Sarver with four ethical violations arising from his sexual relationship with a client. Initially, the parties entered into an agreement for discipline by consent and stipulated to a two-year suspension, with the entire suspension stayed on just one condition—that Sarver not engage in any further misconduct. The board accepted the consent-to-discipline agreement and the stipulated sanction and recommended that we do so also. However, we rejected that sanction and remanded the matter for additional proceedings. Subsequently, at a hearing before a panel of the board, the parties presented stipulations of fact, misconduct, and aggravating and mitigating factors, submitted 28 joint exhibits, and recommended that Sarver be suspended from the practice of law for two years, with the entire suspension stayed on multiple conditions.

The panel adopted the parties' stipulations and recommended sanction, and the board again adopted the panel's report in its entirety, and no objections have been filed. Although we agree with the finding that Sarver committed professional misconduct, we reject the board's recommended sanction and conclude that Sarver's misconduct warrants a suspension from the practice of law for two years, with the last 18 months of the suspension stayed on the conditions recommended by the board.

[Misconduct]{.casesection}

Sarver and J.B. met each other in 2012 when Sarver represented J.B.'s then boyfriend in a legal matter. On September 11, 2015, J.B. reached out to Sarver when she needed "a good attorney for felony … some stupid shit happened and I really need to talk to u its not good." The next day, Sarver and J.B. met at a Columbus restaurant, discussed J.B.'s criminal case over drinks, and then had sex in Sarver's vehicle in the parking lot.

J.B. was charged with theft in the Hocking County Municipal Court and a warrant was issued for her arrest. According to Sarver, he was unaware that a warrant had been issued when he subsequently instructed her to turn off the Global Positioning System ("GPS") on her mobile phone so that law enforcement could not track her. Several days later, a grand jury indicted J.B. for multiple felonies, and due to Sarver's advice to turn off the GPS on her mobile phone, she avoided arrest for almost one month before being apprehended.

The judge presiding over J.B.'s arraignment appointed Sarver to represent her, and Sarver, now representing an indigent client as court-appointed counsel, engaged in sexual activity with her at least seven more times over the next four months. They also trespassed onto Sarver's neighbor's property to use a hot tub.

In the meantime, Sarver filed a petition to run for Hocking County Prosecuting Attorney. And although rumors of his sexual relationship with J.B. soon spread, Sarver falsely denied the rumors to the judge presiding over J.B.'s criminal case on two separate occasions. Around the same time that Sarver had lied about his inappropriate relationship with J.B. to the judge, the Hocking County Sheriff's Office began investigating Sarver. Detectives interviewed J.B. and promised her a reduced sentence if she disclosed the true nature of her relationship with Sarver. J.B. agreed to cooperate with the investigation, and during her interview with detectives, she stated that Sarver had "insinuated" that he would help J.B. with her "warrants and cases for sexual favors." She told the detectives that she had "problems saying no to something like that. You feel kinda forced into it. And, you know, of course, I had something over my head, I was facing 7 felonies."

The state, through a special prosecutor, charged Sarver with several offenses, including two counts of sexual battery in violation of \[an Ohio statute\], which prohibits knowingly coercing another to engage in sexual conduct. However, the sexual-battery counts were dismissed as part of an agreement under which Sarver pleaded guilty to three misdemeanor counts of criminal trespassing (based on Sarver's unauthorized use of his neighbor's hot tub) and one misdemeanor count of obstructing official business (based on his advice to J.B. to turn off her phone's GPS while there was an outstanding warrant for her arrest). Additionally, as part of the plea agreement, Sarver had to withdraw his candidacy for county prosecuting attorney and the special prosecutor dismissed the remaining counts of the indictment. The court sentenced Sarver to two years of community control and fined him \$1,250.

After we rejected the board's original recommendation to accept the parties' consent-to-discipline agreement and remanded the cause to the board for further proceedings, a hearing was held before a panel, the parties presented stipulations of fact, misconduct, and aggravating and mitigating factors, and they recommended that Sarver be suspended from the practice of law for two years, with the entire suspension stayed on multiple conditions.

The panel adopted the parties' stipulations and recommended sanction. The board adopted the panel's report in its entirety and found that Sarver's conduct violated Rules 1.8(j) (prohibiting a lawyer from soliciting or engaging in sexual activity with a client unless a consensual sexual relationship between them existed prior to the client-lawyer relationship), 8.4(b) (prohibiting a lawyer from committing an illegal act that adversely reflects on the lawyer's honesty or trustworthiness), 8.4(c) (prohibiting a lawyer from engaging in conduct involving dishonesty, fraud, deceit, or misrepresentation), and 8.4(d) (prohibiting a lawyer from engaging in conduct that is prejudicial to the administration of justice).

[Sanction]{.casesection}

When imposing sanctions for attorney misconduct, we consider all relevant factors, including the ethical duties that the lawyer violated, the aggravating and mitigating factors listed in Gov.Bar R. V(13), and the sanctions imposed in similar cases.

The parties stipulated and the board found the presence of two aggravating factors—that Sarver acted with a dishonest and selfish motive and committed multiple offenses.

Stipulated mitigating factors found by the board include the absence of prior discipline, Sarver's full and free disclosure to the board and cooperative attitude toward the disciplinary proceedings, and other penalties and sanctions incurred for his misconduct. The parties stipulated and the board found that Sarver had submitted letters attesting to his good character and reputation, and the judge who had presided over J.B.'s criminal case also submitted a letter expressing his agreement with the proposed sanction. In addition, the board noted that Sarver had successfully completed court-ordered counseling and made a good-faith effort to address the issues underlying his misconduct by entering into a contract with the Ohio Lawyers Assistance Program ("OLAP") and attending additional counseling with his spouse.

In considering the appropriate sanction for Sarver's misconduct, the board emphasized that "compelling" mitigating factors in this case warranted a two-year suspension, with the entire suspension stayed on conditions:

> \(1\) not only was there no harm to the client but the client leveraged her relationship with Sarver to get a better plea deal by agreeing to testify against him; (2) he received a very public reprimand of sorts from the local media because his arrest and indictment, while he was a candidate for prosecutor, were front-page news; (3) he was over-indicted with 14 felonies and four misdemeanors including bribery and sexual battery charges; (4) he was arrested twice and spent two nights in jail; and (5) he was forced to withdraw his candidacy for county prosecutor.

The board explained that "what makes these factors so significant is that they all stem from Sarver's consensual sexual relationship with his client."

We agree that Sarver's conduct violated Rules 1.8(j), 8.4(b), 8.4(c), and 8.4(d). However, we disagree that a two-year suspension, with the entire suspension stayed on the conditions recommended by the board, is the appropriate sanction for that misconduct.

Rule 1.8(j) prohibits a lawyer from soliciting or engaging in sexual activity with a client unless a consensual sexual relationship between them predated the client-lawyer relationship. In the absence of a preexisting, consensual sexual relationship, seeking or having sex with a client is a per se violation. The fact that a client appears to have consented does not mitigate the attorney's misconduct or provide a defense against a violation. Indeed, Comment 17 to Rule 1.8(j) explains that "this rule prohibits the lawyer from engaging in sexual activity with a client *regardless of whether the relationship is consensual and regardless of the absence of prejudice to the client,* unless the sexual relationship predates the client-lawyer relationship." (Emphasis added.) *Compare* Rule 1.7 (allowing client to consent to representation of another client that will be directly adverse to the client in certain circumstances); Rule 1.8(a) (allowing client to consent to an attorney's transacting business with the client when certain conditions are met). And \[the Ohio State Bar rules\] do not identify the client's consent as a mitigating factor that may be considered in favor of a less severe sanction.

We have admonished lawyers and sanctioned them with an actual suspension from the practice of law for engaging in sexual conduct with clients with whom they had no sexual relationship prior to the representation. "Most disturbing are cases in which a lawyer has had sex with a client while defending the client against criminal charges or has accepted sex in lieu of fees."

In *Disciplinary Counsel v. Booher,* Booher had been appointed to represent a female client who was facing felony charges. When Booher met with his client to discuss a possible prison sentence in a jail meeting room, they engaged in sexual activity. The client reported the incident to the judge presiding over her case, resulting in disciplinary action against Booher. The board recommended a one-year suspension of Booher's license, with the entire suspension stayed on conditions. We concluded, however, that a more severe sanction was warranted, explaining:

> The case before us involves court-appointed counsel for a criminal defendant. The lawyer-client relation in a criminal matter is inherently unequal. The client's reliance on the ability of her counsel in a crisis situation has the effect of putting the lawyer in a position of dominance and the client in a position of dependence and vulnerability. The more vulnerable the client, the heavier is the obligation upon the attorney not to exploit the situation for his own advantage. Whether a client consents to or initiates sexual activity with the lawyer, the burden is on the lawyer to ensure that all attorney-client dealings remain on a professional level.

We also noted that because the client was incarcerated, Booher had abused his status as an officer of the court by meeting with the client and engaging in sexual activity with her in the jail. We therefore imposed a one-year actual suspension.

In *Disciplinary Counsel v. Freeman,* Freeman paid his 18-year-old female client—who was facing serious criminal charges—\$150 to pose for nude photographs. And after the attorney-client relationship had ended, Freeman offered his underage client alcohol and solicited her to perform sex acts in exchange for specific monetary amounts. Citing *Booher,* this court explained that "we have denounced the patent impropriety of similar misconduct before." And given the reprehensible nature of Freeman's conduct and our obligation to protect the public, we suspended his license to practice law for an actual six-month term.

In *Krieger,* we explained that an assistant public defender "took advantage of the 'inherently unequal' balance of power between a criminal defense lawyer and his or her client" when Krieger had a sexual relationship with—and provided financial assistance to—a male client whom she had previously represented as a juvenile and continued to represent in other legal matters. The attorney had also lied about the relationship to her employer, the public defender, and impeded the public defender in providing competent and objective representation to this indigent defendant, eventually causing the public defender to refuse to provide him with future legal representation. We suspended Krieger from the practice of law for two years, with one year of the suspension stayed on conditions.

In *Akron Bar Assn. v. Williams,* the attorney represented a female client in a domestic-relations proceeding and defended her against charges for driving under the influence and driving with a suspended license. During this time, the client "was in danger of losing custody of her children, had little, if any, money to pay for legal assistance, was struggling with drug use, and was in counseling for having attempted suicide." Nonetheless, Williams began a sexual relationship with the client with an understanding that she would not be charged for his legal services. After the client filed a grievance, Williams lied in a deposition under oath when he denied that he was having a sexual relationship with her. Noting the "egregious" misconduct in which the attorney "took advantage of a vulnerable client and lied under oath to hide his misdeeds," we suspended Williams's law license for two years, with the last 18 months of the suspension stayed on conditions.

These cases all involved attorneys who took advantage of the attorney-client relationship and their clients' vulnerable circumstances for the attorneys' own sexual gratification. And in each case, we determined that an actual suspension was the appropriate sanction for their misconduct.

In this case, however, the board concluded that "compelling mitigating factors" supported adopting the parties' recommendation of a two-year suspension, with the entire suspension stayed on conditions. It noted that "not only was there no harm to the client but the client leveraged her relationship with Sarver to get a better plea deal by agreeing to testify against him." The board also explained that other negative consequences that Sarver experienced—a public shaming "of sorts" from the local media, his being "over-indicted with 14 felonies and four misdemeanors," his two arrests and the two nights that he spent in jail, and his being forced to withdraw his candidacy for county prosecutor—were "significant" because "they all stemmed from Sarver's consensual sexual relationship with his client."

However, the board's finding that there was a consensual relationship seems oblivious to the facts that (1) J.B. was an indigent criminal defendant, (2) Sarver was her court-appointed, criminal-defense attorney, (3) "the lawyer-client relation in a criminal matter is inherently unequal," and (4) "the client's reliance on the ability of her counsel in a crisis situation has the effect of putting the lawyer in a position of dominance and the client in a position of dependence and vulnerability," This power imbalance "'enables the lawyer to dominate and take unfair advantage'" of the client.

Reported cases are filled with clients who have said that they submitted to their attorney's sexual advances out of fear that refusing to submit would affect the quality of their representation at a time of vulnerability and dependence on the attorney.

Here, Sarver met an indigent client "for drinks" and to discuss a serious criminal matter. At the end of the meeting, Sarver proceeded to have sex with her in his parked car, which the client described as a "favor" for his legal services. Then, after the client had been found indigent and Sarver had been appointed by the court to represent her, Sarver continued to engage in sexual activity with J.B. while she remained vulnerable and dependent on him as he defended her against serious criminal charges.

Yet, although J.B. told detectives that she believed Sarver was helping her in exchange for sexual favors and that she had submitted to his sexual advances because of her legal jeopardy—and notwithstanding relator's statement at the hearing that J.B. still contended that the sexual activity with Sarver was not consensual—the board never heard directly from her before making conclusions about the nature of her relationship with Sarver. Instead, the board essentially blamed the victim, J.B., for the negative consequences that *Sarver experienced* resulting from his own decision to engage in sexual relations with a vulnerable client whom he had been appointed to represent in a criminal case.

And then, ignoring all the indications that Sarver exploited the attorney-client relationship to obtain "sexual favors," the board concluded that the client was all the better for it, because she "leveraged her relationship with Sarver to get a better plea deal." The mere fact that the client's criminal case was not prejudiced does not mean that she suffered no harm from Sarver's misconduct. As the Supreme Court of Colorado has explained, "a sexual relationship between lawyer and client during the course of the professional relationship is inherently and insidiously harmful." The client may be psychologically and emotionally harmed by an exploitative sexual relationship regardless of the outcome of the legal case.

The abuse of the attorney-client relationship not only harms the dignity of the client, whose body and trust in her lawyer have been violated, but it also impugns the legal system as a whole. J.B., an indigent criminal defendant, turned to the court and the legal profession to protect her freedom and right to due process, only to be exploited for Sarver's sexual gratification.

It is for all these reasons that Ohio has adopted a per se prohibition against an attorney's having a sexual relationship with a client when such a relationship did not exist before the attorney-client relationship was formed, and the professional-conduct rules do not indicate that a lesser sanction should be imposed on the attorney when the relationship "appears" to be consensual or when the client's case does not seem to have been prejudiced. And in keeping with the aspiration expressed in A Lawyer's Creed "to make the law and our legal system available to all," courts have the obligation to ensure that the lawyers appointed to represent indigent criminal defendants "offer loyalty, confidentiality, competence, diligence and their best judgment" and abide by their professional duty not to initiate a sexual relationship with a vulnerable client whose liberty and right to due process are at stake. Failing to impose an actual suspension on a court-appointed, criminal-defense attorney who has violated Rule 1.8(j) by having sex with his indigent client would contravene our obligation to protect the public.

The board's finding that J.B. freely engaged in a relationship with Sarver ignores the power imbalance between an indigent client and court-appointed defense counsel, and its finding that J.B. had not been prejudiced discounts the inherent harm that results when an attorney abuses the attorney-client relationship in pursuit of the attorney's own sexual gratification. For all of these reasons, Sarver's misconduct of engaging in a sexual relationship with a client in a criminal case—during which he also obstructed official business, committed trespass, and lied about the relationship to a judge—warrants an actual suspension of his law license.

Accordingly, Jason Allan Sarver is suspended from the practice of law in Ohio for two years, with 18 months of the suspension stayed on the conditions that he (1) comply with his December 12, 2017 OLAP contract, (2) take the Multistate Professional Responsibility Exam and receive a passing score, (3) complete 12 hours of continuing legal education focused on professional ethics or attorney-client relationships, (4) serve a two-year period of monitored probation, and (5) engage in no further misconduct. If Sarver fails to comply with any condition of the stay, the stay will be lifted and he will serve the full two-year suspension.

::: callout-note
**Postscript to *Sarver*:** Sarver's disciplinary woes did not end here. Two years after his suspension, he was permanently disbarred and ordered to pay \$50,000 in restitution for "filing a false affidavit of compliance with \[the Ohio Supreme Court\], continuing to practice law while under suspension, and committing other professional misconduct during the course of his suspension and the ensuing disciplinary investigation." [\@DisciplinaryCounselSarver_Ohio2020](https://scholar.google.com/scholar_case?case=11286210687675325700).
:::

## Conflicts Involving Former Clients

#### @MRPC19

::: legalcode
##### Duties to Former Clients

-   \(a\) A lawyer who has formerly represented a client in a matter shall not thereafter represent another person in the same or a substantially related matter in which that person's interests are materially adverse to the interests of the former client unless the former client gives informed consent, confirmed in writing.
-   \(b\) A lawyer shall not knowingly represent a person in the same or a substantially related matter in which a firm with which the lawyer formerly was associated had previously represented a client
    -   \(1\) whose interests are materially adverse to that person; and
    -   \(2\) about whom the lawyer had acquired information protected by Rules 1.6 and 1.9(c) that is material to the matter; unless the former client gives informed consent, confirmed in writing.
-   \(c\) A lawyer who has formerly represented a client in a matter or whose present or former firm has formerly represented a client in a matter shall not thereafter:
    -   \(1\) use information relating to the representation to the disadvantage of the former client except as these Rules would permit or require with respect to a client, or when the information has become generally known; or
    -   \(2\) reveal information relating to the representation except as these Rules would permit or require with respect to a client.
:::

#### @MRPC111

::: legalcode
##### Special Conflicts of Interest for Former & Current Government Officers & Employees

-   \(a\) Except as law may otherwise expressly permit, a lawyer who has formerly served as a public officer or employee of the government:
    -   \(1\) is subject to Rule 1.9(c); and
    -   \(2\) shall not otherwise represent a client in connection with a matter in which the lawyer participated personally and substantially as a public officer or employee, unless the appropriate government agency gives its informed consent, confirmed in writing, to the representation.
-   \(b\) When a lawyer is disqualified from representation under paragraph (a), no lawyer in a firm with which that lawyer is associated may knowingly undertake or continue representation in such a matter unless:
    -   \(1\) the disqualified lawyer is timely screened from any participation in the matter and is apportioned no part of the fee therefrom; and
    -   \(2\) written notice is promptly given to the appropriate government agency to enable it to ascertain compliance with the provisions of this rule.
-   \(c\) Except as law may otherwise expressly permit, a lawyer having information that the lawyer knows is confidential government information about a person acquired when the lawyer was a public officer or employee, may not represent a private client whose interests are adverse to that person in a matter in which the information could be used to the material disadvantage of that person. As used in this Rule, the term "confidential government information" means information that has been obtained under governmental authority and which, at the time this Rule is applied, the government is prohibited by law from disclosing to the public or has a legal privilege not to disclose and which is not otherwise available to the public. A firm with which that lawyer is associated may undertake or continue representation in the matter only if the disqualified lawyer is timely screened from any participation in the matter and is apportioned no part of the fee therefrom.
-   \(d\) Except as law may otherwise expressly permit, a lawyer currently serving as a public officer or employee:
    -   \(1\) is subject to Rules 1.7 and 1.9; and
    -   \(2\) shall not:
        -   \(i\) participate in a matter in which the lawyer participated personally and substantially while in private practice or nongovernmental employment, unless the appropriate government agency gives its informed consent, confirmed in writing; or
        -   \(ii\) negotiate for private employment with any person who is involved as a party or as lawyer for a party in a matter in which the lawyer is participating personally and substantially, except that a lawyer serving as a law clerk to a judge, other adjudicative officer or arbitrator may negotiate for private employment as permitted by Rule 1.12(b) and subject to the conditions stated in Rule 1.12(b).
-   \(e\) As used in this Rule, the term "matter" includes:
    -   \(1\) any judicial or other proceeding, application, request for a ruling or other determination, contract, claim, controversy, investigation, charge, accusation, arrest or other particular matter involving a specific party or parties, and
    -   \(2\) any other matter covered by the conflict of interest rules of the appropriate government agency.
:::

#### @MRPC112

::: legalcode
##### Former Judge, Arbitrator, Mediator or Other Third-Party Neutral

-   \(a\) Except as stated in paragraph (d), a lawyer shall not represent anyone in connection with a matter in which the lawyer participated personally and substantially as a judge or other adjudicative officer or law clerk to such a person or as an arbitrator, mediator or other third-party neutral, unless all parties to the proceeding give informed consent, confirmed in writing.
-   \(b\) A lawyer shall not negotiate for employment with any person who is involved as a party or as lawyer for a party in a matter in which the lawyer is participating personally and substantially as a judge or other adjudicative officer or as an arbitrator, mediator or other third-party neutral. A lawyer serving as a law clerk to a judge or other adjudicative officer may negotiate for employment with a party or lawyer involved in a matter in which the clerk is participating personally and substantially, but only after the lawyer has notified the judge or other adjudicative officer.
-   \(c\) If a lawyer is disqualified by paragraph (a), no lawyer in a firm with which that lawyer is associated may knowingly undertake or continue representation in the matter unless:
    -   \(1\) the disqualified lawyer is timely screened from any participation in the matter and is apportioned no part of the fee therefrom; and
    -   \(2\) written notice is promptly given to the parties and any appropriate tribunal to enable them to ascertain compliance with the provisions of this Rule.
-   \(d\) An arbitrator selected as a partisan of a party in a multimember arbitration panel is not prohibited from subsequently representing that party.
:::

#### @NuStarFarmsLLCZylstra_Iowa2016

In this interlocutory appeal, we are asked to decide whether an attorney should be disqualified from representing one party in a lawsuit, either because his representation of the two parties was concurrent or because he had previously represented the opposing party in a similar matter. The district court concluded that the attorney need not be disqualified. For the reasons stated below, we conclude that the district court did not abuse its discretion in concluding that the prior attorney-client relationship failed the "substantial relationship" test. However, we conclude that the attorney did have a concurrent conflict of interest. Therefore, we find the district court abused its discretion in not disqualifying the attorney.

[Background Facts and Proceedings.]{.casesection}

Attorney Larry Stoller began representing Robert and Marcia Zylstra in 2002. Stoller represented them in a number of legal matters between 2002 and 2014, including financial issues, business acquisitions, and real estate transactions. Although the Zylstras were represented by Stoller on a number of occasions, they also used the services of other attorneys throughout this time period. At issue for the purposes of this case are a meeting in January 2007 and a small claims case ending in 2014.

On January 24, 2007, Robert met with Stoller to discuss estate planning and manure easement agreements. At the time of the meeting, the Zylstras were shareholders in Sibley Dairy, LLP. During this meeting, Robert showed Stoller a multipage document containing multiple manure easement agreements that the Zylstras intended to enter into with NuStar Farms, LLC. The parties disagree as to the extent of Stoller's involvement during this meeting regarding the manure easement agreements. Stoller asserts that he only briefly glanced at the easement agreements and then advised Robert that he should seek the advice of another attorney. Although Stoller acknowledges he made notations on the first page of the document, he argues that the notations do not indicate he read the entirety of the multipage manure easement agreements. Robert asserts that he asked Stoller to review the manure easement agreements and provide advice. Robert further alleges that Stoller examined the agreements during the meeting and advised him to go ahead and complete and sign them.

The record reflects that Stoller made notations on the documents. However, Stoller claims the notations were made at Robert's request to help Robert remember what to discuss with one of the attorneys that Stoller suggested Robert contact. Both parties agree that Stoller suggested Robert find an attorney with more experience in the area of manure easements. Stoller sent a follow-up email to Robert with two attorney references who he thought could assist the Zylstras with the easements. The email also confirmed that Robert asked Stoller to look at the easements and that Stoller "briefly looked at them." Further, Stoller wrote, "The changes you were talking about should be run by the other attorney and I suggest that if approved they be included in the easements. I would also think that some permit would be necessary." The record also reflects that during this conference they discussed estate planning matters. This is confirmed in the follow-up email and Stoller's office notes of the conference. Stoller billed the Zylstras for 1.20 hours and described the meeting as, "Conference with Robert on manure easement; review easements and agreement." There is nothing in the record to indicate that Stoller represented the Zylstras when they executed the manure easement agreements with NuStar or that he had any further involvement in the sale of Sibley Dairy.

Stoller continued to represent the Zylstras in a number of other legal matters between 2007 and 2014. In December 2013, Stoller began representing the Zylstras in a small claims matter. The case was submitted to the small claims court on February 10, 2014, but the court did not issue its ruling until May 30. Stoller began representing NuStar in early May in an action regarding loan covenants. Also in early May, Stoller began contacting the Zylstras on behalf of NuStar. At least part of these contacts involved the Zylstras' failure to provide NuStar with a deed to property involving ingress. Stoller acknowledges that he contacted Robert about the Zylstras' need to sign the deed. On May 13, Stoller sent the Zylstras an email that stated it was the third time he had contacted them about the deed to ingress property sold by the Zylstras to NuStar. Stoller wrote in the email,

> I must now put you on formal notice that if the signed deed is not received by my office by the close of business on Wednesday, May 14, 2014, that I will need to pursue the appropriate remedies for specific performance and damages on behalf of NuStar.

Stoller also wrote in his email, "I have tried to remain neutral in those matters and advised both parties that I could represent neither."

In this same email, Stoller informed the Zylstras that he would no longer be representing them in any future matters. Robert acknowledges that he understood the May 13 email as a severance of the attorney-client relationship. Stoller emailed the Zylstras again on May 14, expressing disappointment that the Zylstras were not going to sign the deed. Stoller also reminded Robert of his prior financial situation and how Stoller had helped him in the past.

By May 15, the Zylstras had retained John Sandy to represent them in their dealings with NuStar. In Sandy's correspondence to Stoller that same day, he alerted Stoller that the Zylstras found his representation of NuStar to be a conflict of interest based on his prior legal representation and counsel provided to the Zylstras. Sandy specifically requested that Stoller cease further representation of NuStar when those interests conflicted with the Zylstras.

On June 5, Stoller sent the Zylstras a letter notifying them of the judge's ruling in the small claims case and informing them that he believed the decision was appealable. Stoller further notified the Zylstras of their rights to appeal and the deadlines associated with such an appeal. Stoller wrote he would be willing to file an appeal on their behalf and included information about his retainer and billing rate. Stoller also advised the Zylstras that if they chose to have another attorney represent them on the appeal he would release their file to that attorney.

On July 9, Stoller filed a multicount petition on behalf of NuStar against the Zylstras. The petition alleged the Zylstras agreed to sell NuStar a parcel in farmland in 2008, but they failed to tender the requisite deed. One count of the petition also alleged the Zylstras did not abide by certain terms contained in the manure easement agreements. In response, the Zylstras filed a preanswer motion to dismiss based on statute of limitations grounds. They also filed a motion seeking to disqualify Stoller as the attorney for NuStar based on a conflict of interest.

On August 8, the district court held a hearing, and the parties argued both the motion to dismiss and the motion to disqualify Stoller. On October 14, the district court denied both motions. On November 10, the Zylstras filed an application for interlocutory appeal seeking review of the district court's denial of their motion to disqualify Stoller. We granted the application for interlocutory appeal on December 5.

[Analysis]{.casesection}

The right of a party to choose his or her own attorney is important, but it must be balanced against the need to maintain "the highest ethical standards" that will preserve the public's trust in the bar and in the integrity of the court system. A court must necessarily balance these two competing interests when determining whether to disqualify an attorney. In doing so, the court "must also be vigilant to thwart any misuse of a motion to disqualify for strategic reasons." When we evaluate motions to disqualify an attorney, we use our Iowa Rules of Professional Conduct as the starting point.

Rule 32:1.7 covers concurrent conflicts of interest and states in pertinent part,

> \(a\) Except as provided in paragraph (b), a lawyer shall not represent a client if the representation involves a concurrent conflict of interest. A concurrent conflict of interest exists if: (1) the representation of one client will be directly adverse to another client; or (2) there is significant risk that the representation of one or more clients will be materially limited by the lawyer's responsibilities to another client, a former client, or a third person by a personal interest of the lawyer.

The rule goes on to state that a lawyer may continue with the representation of a client if certain stipulations are met, one of which is that each client gives informed, written consent.

The Zylstras allege that Stoller's representation of NuStar was a concurrent conflict of interest with his representation of them. They argue that he began the action on behalf of NuStar in early May, while knowing that the representation would be adverse to the Zylstras because it involved a deed between the two parties. Further, Stoller began contacting the Zylstras on behalf of NuStar before the May 13 email officially terminating his attorney-client relationship with the Zylstras on the small claims case. Stoller responds that there was no concurrent conflict of interest because he did not file the action on behalf of NuStar against the Zylstras until after the May 13 email terminating the attorney-client relationship. In the alternative, the Zylstras argue that Stoller's June 5 email indicates that he was continuing to represent them in the small claims matter until the court issued its ruling. Even thereafter, Stoller advised the Zylstras there was a basis to appeal the judgment, the time for perfecting such an appeal, and his willingness to continue representing them in the appeal. Stoller contends that it was his duty to inform the Zylstras, as his former clients, of the outcome of the small claims hearing and the time limits for appeal. He further contends that, although he said he would be willing to represent the Zylstras on the appeal, he was also recommending they find alternate representation and thus was only informing them of their options if they chose to go forward with an appeal.

Before we turn to an analysis of whether a concurrent conflict of interest exists, we must address two questions: when the attorney-client relationship between the Zylstras and Stoller ended, and when the attorney-client relationship between NuStar and Stoller began. The first question we may dispose of easily. Generally, a lawyer's representation of a client extends until the time period for motions or appeals expires in a civil action. However, both the attorney and the client may terminate the relationship prior to this natural ending. Both Stoller and the Zylstras agree that the attorney-client relationship was terminated with the May 13 email. Further, while Stoller did offer to represent the Zylstras on the appeal, the Zylstras did not actually appeal the small claims case and did not solicit Stoller's services on any other legal matters. We find that the attorney-client relationship between Stoller and the Zylstras ended with the May 13 email.

The next question we must address is when the attorney-client relationship between Stoller and NuStar began. The attorney-client relationship is governed by general contract principles. It may be either express, such as when representation is based on a written agreement, or implied by the conduct of the parties. There are three elements that must be met to find that an attorney-client relationship has been established:

> \(1\) a person sought advice or assistance from an attorney, (2) the advice or assistance sought pertained to matters within the attorney's professional competence, and (3) the attorney expressly or impliedly agreed to give or actually gave the desired advice or assistance.

The relationship between Stoller and NuStar clearly meets this test. NuStar sought advice from Stoller at least beginning in early May about the action that required a deed from the Zylstras. The advice they sought from Stoller pertained to matters within his professional ability. Stoller has practiced law for a number of years and across a number of areas. Last, Stoller both agreed to give and actually gave NuStar advice and assistance. On NuStar's behalf, Stoller began contacting the Zylstras regarding the deed that NuStar was demanding. We find that the attorney-client relationship between NuStar and Stoller began, at the latest, in early May. This is also confirmed by Stoller's correspondence with the Zylstras on May 13 in which he asserts that it was the third time he had contacted them in regard to the deed. We now turn to a discussion of whether this attorney-client relationship involved a concurrent conflict of interest that violates rule 32:1.7.

There are two ways for a concurrent conflict of interest to exist under rule 32:1.7. The first is if "the representation of one client will be directly adverse to another client." The second is if "there is a significant risk that the representation will be materially limited by the lawyer's responsibilities to another client, a former client, or a third person." We may find a concurrent conflict of interest under either situation.

We have acknowledged that rule 32:1.7(a) "applies where directly adverse representation will take place, as when one current client is about to file suit against another current client." The comments to the rule expand on what a "directly adverse" action may be:

> Loyalty to a current client prohibits undertaking representation directly adverse to that client without that client's informed consent. Thus, absent consent, a lawyer may not act as an advocate in one matter against a person the lawyer represents in some other matter, even when the matters are wholly unrelated.

Stoller acknowledged in a letter to the Iowa Supreme Court Attorney Disciplinary Board that he began the representation of NuStar in early May and that the Zylstras were aware of his representation of NuStar. It is unclear from the record at what point Stoller realized the action would include the deed that NuStar wanted the Zylstras to sign. However, by the time Stoller sent the May 13 email, he was already contemplating taking action against the Zylstras on behalf of NuStar. The email stated,

> I must now put you on formal notice that if the signed deed is not received by my office by the close of business on Wednesday, May 14, 2014, that I will need to pursue the appropriate remedies for specific performance and damages on behalf of NuStar.

In this email, Stoller clearly demonstrates the intent to pursue a future, adverse action against the Zylstras on behalf of NuStar. Although Stoller terminated the attorney-client relationship with the Zylstras in the same email, the intent to pursue legal action unless the Zylstras complied with NuStar's request to sign the deed arose before the email was sent---which is precisely why the demand or "formal notice" language is included. We find that Stoller's representation of NuStar was a directly adverse concurrent conflict of interest. Because Stoller did not properly obtain consent from the Zylstras to represent NuStar, his actions fall squarely within the guidance of the comments that "absent consent, a lawyer may not act as an advocate in one matter against a person the lawyer represents in some other matter, even when the matters are wholly unrelated." Thus, we find Stoller should be disqualified from representing NuStar in the action against the Zylstras. Because the district court applied the law in error, we find that it abused its discretion in concluding that Stoller should not be disqualified.

[Rule 32:1.9(a)---Duties to Former Clients]{.casesubsection}

Stoller argues that, even though there was a concurrent conflict of interest in the past, the conflict no longer exists because he severed the attorney-client relationship, and therefore he can continue to represent NuStar in the current action against the Zylstras. Rule 32:1.9(a) concerns a lawyer's duties to former clients. In pertinent part, it provides,

> A lawyer who has formerly represented a client in a matter shall not thereafter represent another person in the same or a substantially related matter in which that person's interests are materially adverse to the interests of the former client unless the former client gives informed consent, confirmed in writing.

The comments expand on what makes a matter "substantially related" for purposes of the rule. A matter is substantially related if it involves the same transaction or legal dispute. If there is "a substantial risk that confidential factual information as would normally have been obtained in the prior representation would materially advance the client's position in the subsequent matter," then the matter is substantially related.

We consider three factors when we determine whether a substantial relationship exists:

> \(1\) the nature and scope of the prior representation; (2) the nature of the present lawsuit; and (3) whether the client might have disclosed a confidence to his or her attorney in the prior representation which could be relevant to the present action.

Under the first factor, we must consider the scope---if any---of Stoller's representation of the Zylstras in regard to the manure easement agreements. There is no question that Stoller and Robert met to discuss the agreements and that Stoller was aware the Zylstras intended to enter into the agreements with NuStar. During the meeting, Robert showed Stoller the easement agreements. Stoller acknowledges that he looked at the first page and made some notations, though he contends the notations were made at Robert's request so Robert would know what he needed to discuss with another attorney. Stoller further claims that he did not read the entirety of the agreements. During the meeting, Stoller advised Robert to find another attorney to help him with the agreements because it was not an area of the law Stoller was familiar with. He gave Robert the names of two attorneys to contact.

Stoller sent an email to Robert following the meeting that summarized their discussion about the easement agreements. The email stated that Robert asked Stoller to look at the easements and that he "briefly looked at them." Stoller also wrote, "The changes you were talking about should be run by the other attorney and I suggest that if approved they be included in the easements. I would also think that some permit would be necessary." This reflects at least some level of advice given to Robert by Stoller. However, this is in stark contrast to our previous cases where we have found an attorney was extensively involved in prior representation.

In *Doe*, we found an attorney was highly involved in a client's prior representation when he had met with the clients, had telephone conversations with the clients, appeared as their attorney, and signed pleadings on their behalf. In *Marks*, we found that the attorney violated rule 32:1.9(a) when he represented a client in a foreclosure action and later represented his own wife in the sale of property to that same former client. We found that the attorney's representation of the client and his wife were substantially related because he had obtained information about the client's property during the foreclosure action. In comparison to our prior cases, we cannot say that the scope of Stoller's representation of the Zylstras regarding the manure easement agreements was in any way significant.

The second factor we consider is the nature of the present lawsuit between the Zylstras and NuStar. In the original petition that Stoller filed on behalf of NuStar, he included six counts. All of the counts except one deal with a real estate contract between NuStar and the Zylstras. Stoller did not participate in the real estate contract on behalf of the Zylstras. Count IV alleges a breach of the manure easement agreements between NuStar and the Zylstras. Although the majority of the counts do not relate to the manure easement agreements that Stoller had knowledge of, at least one part of the current lawsuit does relate to the prior scope of Stoller's representation.

The final factor we consider is "whether the client might have disclosed a confidence to his or her attorney in the prior representation which could be relevant to the present action." The meeting between Robert and Stoller to discuss the manure easement agreements was brief. The parties only superficially discussed the substance of the agreements and Stoller specifically suggested that Robert seek other competent agricultural law counsel to review the agreements before signing them. The email from Stoller does note that the two discussed whether permits were required or whether Robert should change anything in the agreements. However, nothing from this meeting indicates that Robert disclosed anything in confidence about the agreements to Stoller that would affect the current lawsuit between the Zylstras and NuStar.

We do not find that a substantial relationship exists sufficient to disqualify Stoller under rule 32:1.9(a). We therefore find that the district court did not abuse its discretion in holding that Stoller could not be disqualified under the substantial relationship test.

[Conclusion]{.casesection}

We find that the district court did not abuse its discretion in concluding that any prior relationship between Stoller and Zylstra in regard to the manure easement agreements failed the substantial relationship test. However, we find that Stoller did have a concurrent conflict of interest. Therefore, we conclude that the district court abused its discretion in not disqualifying Stoller from representing NuStar in the action. On remand, the district court should enter an order disqualifying Stoller from further representation of NuStar in this lawsuit.

## Imputed Conflicts

#### @MRPC112

::: legalcode
##### Imputation of Conflicts of Interest: General Rule

-   \(a\) While lawyers are associated in a firm, none of them shall knowingly represent a client when any one of them practicing alone would be prohibited from doing so by Rules 1.7 or 1.9, unless
    -   \(1\) the prohibition is based on a personal interest of the disqualified lawyer and does not present a significant risk of materially limiting the representation of the client by the remaining lawyers in the firm; or
    -   \(2\) the prohibition is based upon Rule 1.9(a) or (b) and arises out of the disqualified lawyer’s association with a prior firm, and
        -   \(i\) the disqualified lawyer is timely screened from any participation in the matter and is apportioned no part of the fee therefrom;
        -   \(ii\) written notice is promptly given to any affected former client to enable the former client to ascertain compliance with the provisions of this Rule, which shall include a description of the screening procedures employed; a statement of the firm's and of the screened lawyer's compliance with these Rules; a statement that review may be available before a tribunal; and an agreement by the firm to respond promptly to any written inquiries or objections by the former client about the screening procedures; and
        -   \(iii\) certifications of compliance with these Rules and with the screening procedures are provided to the former client by the screened lawyer and by a partner of the firm, at reasonable intervals upon the former client's written request and upon termination of the screening procedures.
-   \(b\) When a lawyer has terminated an association with a firm, the firm is not prohibited from thereafter representing a person with interests materially adverse to those of a client represented by the formerly associated lawyer and not currently represented by the firm, unless:
    -   \(1\) the matter is the same or substantially related to that in which the formerly associated lawyer represented the client; and
    -   \(2\) any lawyer remaining in the firm has information protected by Rules 1.6 and 1.9(c) that is material to the matter.
-   \(c\) A disqualification prescribed by this rule may be waived by the affected client under the conditions stated in Rule 1.7.
-   \(d\) The disqualification of lawyers associated in a firm with former or current government lawyers is governed by Rule 1.11.
:::

#### @ScreeningLateralHireWho_NCStateBar2013

Opinion rules that a lawyer who represented an organization while employed with another firm must be screened from participation in any matter, or any matter substantially related thereto, in which she previously represented the organization, and from any matter against the organization if she acquired confidential information of the organization that is relevant to the matter and which has not become generally known.

[Inquiry #1:]{.casesection}

Attorney J was employed with Law Firm H where she did workers’ compensation defense work. During this time, Attorney J handled many such cases for Large Manufacturer and its insurer. In addition, Attorney J was privy to Large Manufacturer’s workers’ compensation policies and procedures, litigation strategies, and system for case preparation. Attorney J participated in workers’ compensation strategy meetings with representatives of Large Manufacturer as well as with defense counsel from Law Firm Y, another firm providing workers’ compensation defense representation to Large Manufacturer.

Attorney J resigned from Law Firm H to work for Law Firm S, a plaintiffs’ personal injury firm that routinely handles workers’ compensation cases against Large Manufacturer.

May Attorney J work at Law Firm S?

[Opinion #1:]{.casesubsection}

Yes, if Attorney J is properly screened from participation in (1) any matter in which Attorney J represented Large Manufacturer or any other adverse party; (2) any matter that is substantially related to a matter in which Attorney J represented Large Manufacturer; and (3) any matter in which a lawyer with Law Firm H represents or represented Large Manufacturer or any other adverse party and about which Attorney J acquired material confidential information while she was employed with Law Firm H. Written notice of the screen must be given to Large Manufacturer and any other affected former client.

Rule 1.9(a) prohibits a lawyer who has formerly represented a client in a matter from thereafter representing an adverse party in the same or a substantially related matter unless the former client gives informed consent. This provision of the rule prohibits Attorney J from representing any workers’ compensation claimant on a claim for which she formerly defended Large Manufacturer and from representing any claimant on a claim that is substantially related to a matter upon which Attorney J formerly represented Large Manufacturer.

Comment \[3\] to Rule 1.9 provides the following explanation of disqualification because of substantial relationship:

> matters are “substantially related” for purposes of this Rule if they involve the same transaction or legal dispute or if there otherwise is a substantial risk that information as would normally have been obtained in the prior representation would materially advance the client’s position in the subsequent matter. Information that has been disclosed to the public or to other parties adverse to the former client ordinarily will not be disqualifying. Information acquired in a prior representation may have been rendered obsolete by the passage of time, a circumstance that may be relevant in determining whether two representations are substantially related. In the case of an organizational client, general knowledge of the client’s policies and practices ordinarily will not preclude a subsequent representation; on the other hand, knowledge of specific facts gained in a prior representation that are relevant to the matter in question ordinarily will preclude such a representation.

The substantial relationship test serves as a proxy for requiring a former client to disclose confidential information to demonstrate that the lawyer has a conflict of interest:

> A former client is not required to reveal the information learned by the lawyer to establish a substantial risk that the lawyer has information to use in the subsequent matter. A conclusion about the possession of such information may be based on the nature of the services the lawyer provided the former client and information that would in ordinary practice be learned by a lawyer providing such services.

Rule 1.9, cmt. \[3\].

Rule 1.9(b) prohibits a lawyer from representing anyone in the same or a substantially related matter in which a firm with which the lawyer was formerly associated had previously represented the adverse party and about whom the lawyer acquired confidential, material information, unless the former client gives informed consent. This provision of the rule prohibits Attorney J from representing a workers’ compensation claimant in a matter in which one of the other lawyers at Law Firm H defended Large Manufacturer and about which Attorney J acquired confidential information that is material to the matter.

If Attorney J is disqualified under any provision of Rule 1.9, Rule 1.10(c) permits screening of Attorney J to avoid imputing her disqualification to the other lawyers in her new firm. The rule provides:

> when a lawyer becomes associated with a firm, no lawyer associated in the firm shall knowingly represent a person in a matter in which that lawyer is disqualified under Rule 1.9 unless:

> > \(1\) the personally disqualified lawyer is timely screened from any participation in the matter; and

> > \(2\) written notice is promptly given to any affected former client to enable it to ascertain compliance with the provisions of this Rule.

Comment \[4\] to Rule 1.9, which relates to lawyers moving between firms, elucidates the policy considerations justifying the use of screens in this situation:

> \[w\]hen lawyers have been associated within a firm but then end their association, the question of whether a lawyer should undertake representation is more complicated. There are several competing considerations. First, the client previously represented by the former firm must be reasonably assured that the principle of loyalty to the client is not compromised. Second, the rule should not be so broadly cast as to preclude other persons from having reasonable choice of legal counsel. Third, the rule should not unreasonably hamper lawyers from forming new associations and taking on new clients after having left a previous association. In this connection, it should be recognized that today many lawyers practice in firms, that many lawyers to some degree limit their practice to one field or another, and that many move from one association to another several times in their careers. If the concept of imputation were applied with unqualified rigor, the result would be radical curtailment of the opportunity of lawyers to move from one practice setting to another and of the opportunity of clients to change counsel.

As long as a screen is implemented to isolate Attorney J from participation in these matters, the consent of Large Manufacturer to the representation of the claimants by a lawyer with Law Firm S is not required. *See* Rule 1.0(l) and 2003 FEO 8 (setting forth screening procedures).

[Inquiry #2:]{.casesection}

Large Manufacturer contends that any new workers’ compensation claims against Large Manufacturer that Attorney J handles at Law Firm S will be substantially related to her prior representation of Large Manufacturer because Attorney J was privy to information about Large Manufacturer’s defense of workers’ compensation cases and this information will materially advance the interests of any client with a workers’ compensation claim against Large Manufacturer.

May Attorney J represent claimants on new workers’ compensation cases against Large Manufacturer if the claimant did not seek representation from Law Firm S until after Attorney J’s employment?

[Opinion #2:]{.casesubsection}

It depends. If a new matter is not the same or substantially related to Attorney J’s prior representations of Large Manufacturer, she is not disqualified from the representation unless, during her prior employment with Law Firm H, she acquired confidential information of Large Manufacturer that is material or relevant to the representation of the new client, may be used to the disadvantage of Large Manufacturer, and is not generally known. Attorney J has a continuing duty under paragraphs (a) and (b) of Rule 1.9 to monitor any new matter involving Large Manufacturer to determine whether it is substantially related to her prior representation of her former client or she acquired confidential information from Large Manufacturer that is material to the matter. If so, she is personally disqualified and must be screened. *See* Opinion #1.

Even if the matters are not substantially related, however, Attorney J has a continuing duty under paragraph (c) of Rule 1.9 to ensure that the representation will not result in the misuse of confidential information of Large Manufacturer. Rule 1.9(c) prohibits a lawyer who has formerly represented a client in a matter or whose former firm has formerly represented a client in a matter from thereafter using confidential information relating to the representation to the disadvantage of the former client except as allowed by the Rules or when the information has become “generally known.” A screen must be promptly implemented to isolate Attorney J from participation in any such case. *See* Opinion #1.

Comment \[8\] to Rule 1.9 explains the exception for information that is “generally known” as follows:

> …the fact that a lawyer has once served a client does not preclude the lawyer from using generally known information about that client when later representing another client. Whether information is “generally known” depends in part upon how the information was obtained and in part upon the former client’s reasonable expectations. The mere fact that information is accessible through the public record or has become known to some other persons does not necessarily deprive the information of its confidential nature. If the information is known or readily available to a relevant sector of the public, such as the parties involved in the matter, then the information is probably considered “generally known.”

Similarly, the *Restatement (Third) of The Law Governing Lawyers* adopts an access approach to the determination of what information is “generally known”:

> Whether information is generally known depends on all circumstances relevant in obtaining the information. Information contained in books or records in public libraries, public-record depositaries such as government offices, or in publicly accessible electronic-data storage is generally known if the particular information is obtainable through publicly available indexes and similar methods of access. Information is not generally known when a person interested in knowing the information could obtain it only by means of special knowledge or substantial difficulty or expense. Special knowledge includes information about the whereabouts or identity of a person or other source from which the information can be acquired if those facts are not themselves generally known.

Restatement (Third) of the Law Governing Lawyer, §59, cmt. d.

Attorney J’s general knowledge of Large Manufacturer’s workers’ compensation case management, settlement, and litigation policies and practices may be sufficient in some matters to disqualify her. As observed in the discussion of “substantial relationship” in comment \[3\] to Rule 1.9, “in the case of an organizational client, general knowledge of the client’s policies and practices ordinarily will not preclude a subsequent representation; on the other hand, knowledge of specific facts gained in a prior representation that are relevant to the matter in question ordinarily will preclude such a representation.”

When evaluating whether a representation is substantially related to a prior representation of an organizational client or whether a lawyer acquired confidential information of a former organizational client that is substantially relevant to the representation of a client and may be used to the disadvantage of the former client, the following factors, among others, should be considered: the length of time that the lawyer represented the former client; the lawyer’s role in representing the former client, including the lawyer’s presence at strategy and decision-making sessions for the former client; the relative authority of the lawyer to make decisions about the representation of the former client; the passage of time since the lawyer represented the former client;[^chap6-6] the extent to which there are material factual and legal similarities between former and present representations; and the substantial relevance of the former client’s litigation policies, strategies, and practices to the new matter.

[^chap6-6]: (n.1 in opinion) For an example of a timeframe deemed to be sufficient to manage post-employment conflicts of interest for federal government employees, see the Ethics in Government Act of 1978, 18 U.S.C.§ 207(c).

[Inquiry #3:]{.casesection}

May the other lawyers in Law Firm S represent claimants on new workers’ compensation cases against Large Manufacturer?

[Opinion #3:]{.casesubsection}

Yes, if Attorney J is screened from those matters for which she acquired confidential information of Large Manufacturer that is disqualifying. *See* Opinion #2.

[Inquiry #4:]{.casesection}

Should Attorney J be screened from participation in workers’ compensation cases against Large Manufacturer that were defended by lawyers from Law Firm Y while Attorney J was employed by Law Firm H?

[Opinion #4:]{.casesubsection}

Yes, if she acquired confidential information of Large Manufacturer that is disqualifying. *See* Opinion #2.

[Inquiry #5:]{.casesection}

Large Manufacturer has many long-term employees who over time may file multiple workers’ compensation claims against Large Manufacturer. If Lawyer J or another lawyer with Law Firm H defended Large Manufacturer against a particular employee while Attorney J was employed by the firm, it is contended that there is a substantial risk that Attorney J will have specific confidential information of Large Manufacturer that would be relevant and useful to the representation of the particular claimant. For example, a manager’s thoughts and opinions regarding the claimant could be information that would not be generally known and which might be used to the disadvantage of Large Manufacturer.

May Attorney J represent a claimant on a new workers’ compensation case against Large Manufacturer if the claimant had previously filed a workers’ compensation case against Large Manufacturer that was defended by a lawyer from Law Firm H while Attorney J was employed by the firm?

[Opinion #5:]{.casesubsection}

As stated in Opinion #2, Attorney J has a continuing duty to monitor any matter involving Large Manufacturer to be sure that the representation will not result in the use of confidential information of Large Manufacturer that has not become generally known to the disadvantage of Large Manufacturer in violation of Rule 1.9(c). A screen must be promptly implemented to isolate Attorney J from participation in any such matter.