# Confidentiality & Privileges

## Duty of Confidentiality

#### @MRPC16
::: legalcode
##### Confidentiality of Information

-   \(a\) A lawyer shall not reveal information relating to the representation of a client unless the client gives informed consent, the disclosure is impliedly authorized in order to carry out the representation or the disclosure is permitted by paragraph (b).
-   \(b\) A lawyer may reveal information relating to the representation of a client to the extent the lawyer reasonably believes necessary:
    -   \(1\) to prevent reasonably certain death or substantial bodily harm;
    -   \(2\) to prevent the client from committing a crime or fraud that is reasonably certain to result in substantial injury to the financial interests or property of another and in furtherance of which the client has used or is using the lawyer's services;
    -   \(3\) to prevent, mitigate or rectify substantial injury to the financial interests or property of another that is reasonably certain to result or has resulted from the client's commission of a crime or fraud in furtherance of which the client has used the lawyer's services;
    -   \(4\) to secure legal advice about the lawyer's compliance with these Rules;
    -   \(5\) to establish a claim or defense on behalf of the lawyer in a controversy between the lawyer and the client, to establish a defense to a criminal charge or civil claim against the lawyer based upon conduct in which the client was involved, or to respond to allegations in any proceeding concerning the lawyer's representation of the client;
    -   \(6\) to comply with other law or a court order; or
    -   \(7\) to detect and resolve conflicts of interest arising from the lawyer’s change of employment or from changes in the composition or ownership of a firm, but only if the revealed information would not compromise the attorney-client privilege or otherwise prejudice the client.
-   \(c\) A lawyer shall make reasonable efforts to prevent the inadvertent or unauthorized disclosure of, or unauthorized access to, information relating to the representation of a client.
:::

#### @MRPC19
::: legalcode
##### Duties to Former Clients

-   \(c\) A lawyer who has formerly represented a client in a matter or whose present or former firm has formerly represented a client in a matter shall not thereafter:
    -   \(1\) use information relating to the representation to the disadvantage of the former client except as these Rules would permit or require with respect to a client, or when the information has become generally known; or
    -   \(2\) reveal information relating to the representation except as these Rules would permit or require with respect to a client.
:::

#### @MRPC118
::: legalcode
##### Duties to Prospective Client

-   \(b\) Even when no client-lawyer relationship ensues, a lawyer who has learned information from a prospective client shall not use or reveal that information, except as Rule 1.9 would permit with respect to information of a former client.
-   \(c\) A lawyer subject to paragraph (b) shall not represent a client with interests materially adverse to those of a prospective client in the same or a substantially related matter if the lawyer received information from the prospective client that could be significantly harmful to that person in the matter, except as provided in paragraph (d). If a lawyer is disqualified from representation under this paragraph, no lawyer in a firm with which that lawyer is associated may knowingly undertake or continue representation in such a matter, except as provided in paragraph (d).
-   \(d\) When the lawyer has received disqualifying information as defined in paragraph (c), representation is permissible if:
    -   \(1\) both the affected client and the prospective client have given informed consent, confirmed in writing, or:
    -   \(2\) the lawyer who received the information took reasonable measures to avoid exposure to more disqualifying information than was reasonably necessary to determine whether to represent the prospective client; and
        -   \(i\) the disqualified lawyer is timely screened from any participation in the matter and is apportioned no part of the fee therefrom; and
        -   \(ii\) written notice is promptly given to the prospective client.
:::

#### @MRPC44
::: legalcode
##### Respect for Rights of Third Persons

-   \(b\) A lawyer who receives a document or electronically stored information relating to the representation of the lawyer's client and knows or reasonably should know that the document or electronically stored information was inadvertently sent shall promptly notify the sender.
:::

#### @NCRulesProfessional_Rule86

::: legalcode
##### Information About a Possible Wrongful Conviction

-   \(a\) Subject to paragraph (b), when a lawyer knows of credible evidence or information, including evidence or information otherwise protected by Rule 1.6, that creates a reasonable likelihood that a defendant did not commit the offense for which the defendant was convicted, the lawyer shall promptly disclose that evidence or information to the prosecutorial authority for the jurisdiction in which the defendant was convicted and to North Carolina Office of Indigent Defense Services or, if appropriate, the federal public defender for the district of conviction.
-   \(b\) Notwithstanding paragraph (a), a lawyer shall not disclose evidence or information if:
    -   \(1\) the evidence or information is protected from disclosure by law, court order, or 27 N.C. Admin. Code Ch. 1B §.0129;
    -   \(2\) disclosure would criminally implicate a current or former client or otherwise substantially prejudice a current or former client's interests; or
    -   \(3\) disclosure would violate the attorney-client privilege applicable to communications between the lawyer and a current or former client.
-   \(c\) A lawyer who in good faith concludes that information is not subject to disclosure under this rule does not violate the rule even if that conclusion is subsequently determined to be erroneous.
-   \(d\) This rule does not require disclosure if the lawyer knows an appropriate governmental authority, the convicted defendant, or the defendant's lawyer already possesses the information.
:::

#### @DoughertyPepperHamiltonLLP_PennsylvaniaSuperiorCourt2016

Appellant, John J. Dougherty, appeals from the order granting summary judgment in favor of Pepper Hamilton LLP and its attorneys Amy B. Ginensky, Michael E. Baughman, Peter M. Smith, and Raphael Cunniff, in this civil action alleging breach of fiduciary duty and breach of contract. For the reasons that follow, we reverse and remand for further proceedings.

We summarize the protracted history of this case as follows. On October 30, 2003, Appellant retained Pepper Hamilton to represent him in relation to a federal matter involving a grand jury subpoena he received. Although Appellant was not the target of the grand jury investigation, an FBI Affidavit was filed to secure a search of Appellant's residence. Appellant has alleged that he provided Pepper Hamilton unfettered access to documents during the firm's representation of Appellant. Also, counsel from Pepper Hamilton was present during the execution of the search warrant at Appellant's home in November of 2006.

Initially, the FBI Affidavit securing the search warrant was under seal, but, somehow, the FBI Affidavit inadvertently became attached to a document presented in an unrelated criminal matter involving an unrelated person named "Donald Dougherty, Jr." According to Appellant, on January 30, 2008, the federal government filed a response to Donald Dougherty Jr.'s motion to suppress evidence, which was entered as Document No. 27 on the federal criminal docket for the prosecution of Donald Dougherty, Jr. This filing was allegedly made under "restricted status."2 Document No. 27 referenced, as Exhibit "A," a copy of an affidavit by an FBI agent in support of the issuance of a search warrant for Donald Dougherty, Jr.'s premises. However, the affidavit that was attached to Document No. 27 as Exhibit "A" was actually the FBI Affidavit in support of the search of Appellant's premises.

At least some of the documents in Donald Dougherty Jr.'s case were filed under seal and, thus, not accessible to the public. Subsequently, however, in April of 2008, certain documents in Donald Dougherty Jr.'s case were unsealed by Judge Robreno of the United States District Court for the Eastern District of Pennsylvania. More specifically, Judge Robreno's April 11, 2008 order authorized the eastern district Clerk of Court to lift the seal on Documents 31, 32, 48 and 38. Appellant alleges that Document No. 27 was also, albeit mistakenly, removed from "restrictive status" around this time.

When Appellant was running for a vacant seat in the Pennsylvania Senate in April of 2008, the Philadelphia Inquirer published several articles about Appellant. The articles implied that Appellant had engaged in criminal conduct in the past and was likely to do so again if elected to the Pennsylvania Senate. In March of 2009, Appellant initiated a defamation suit against the Inquirer in state court. In 2011, Pepper Hamilton assumed representation of the defense for the Inquirer in the defamation suit filed by Appellant. In 2012, Pepper Hamilton informed the trial court that the defense of the defamation action would rely on information relating to the federal investigation in which Pepper Hamilton had previously represented Appellant. In 2013, Appellant moved to have Pepper Hamilton removed as defense counsel in his defamation action against the Inquirer. The trial court denied the motion to disqualify Pepper Hamilton. On appeal this Court reversed the decision of the trial court and remanded the matter for the entry of an order barring Pepper Hamilton and its attorneys from representing the Inquirer.

On December 10, 2012, while Pepper Hamilton and its attorneys were still representing the Inquirer, the firm filed a motion for summary judgment in the defamation suit and included in the attached exhibits a copy of the FBI Affidavit. On December 12, 2012, the Inquirer then published a front-page article, which included detailed references to the FBI Affidavit.

On February 11, 2013, Appellant initiated the instant action by filing a complaint against Appellees alleging breach of fiduciary duty and breach of contract. Appellant alleged that, in representing the Inquirer in the defamation suit, Pepper Hamilton acted against the interests of Appellant, its former client. The trial court has summarized the subsequent procedural history of this case as follows:

> Appellees filed Preliminary Objections on April 3, 2013. These Preliminary Objections were overruled by this Court by Order dated June 18, 2013. An Answer was filed by Appellees on July 8, 2013. On May 27, 2014, after some discovery was conducted and a Revised Case Management Order entered, Appellees filed a Motion for Summary Judgment. An Answer in response to the Motion for Summary Judgment was filed by Appellant on June 27, 2014. A Reply in Support of the Motion for Summary Judgment was filed by Appellees on July 2, 2014. A Supplemental Memorandum in Support of the Motion for Summary Judgment was filed by Appellees on July 25, 2014, and a Supplemental Memorandum in Opposition was filed by Appellant on July 29, 2014. By Order dated July 29, 2014, and entered on the docket on July 30, 2014, Summary Judgment was granted.

This timely appeal followed.

Appellant presents the following issues for our review:

> A. Whether the Trial Court erred in granting Appellees' motion for summary judgment on the mistaken basis that, because Pepper's breach of fiduciary duty was also a violation of the Pennsylvania Rules of Professional Conduct, Appellant cannot assert a claim against Pepper as a matter of law. B. Whether the Trial Court erred in holding that Appellees were entitled to summary judgment because, although they used information against Appellant that is substantially related to their former representation of him, that information is publicly available and thus cannot form the basis of a disloyalty claim. C. Whether the Trial Court prematurely granted Appellees motion for summary judgment where the parties had exchanged limited written discovery and taken no depositions.

Each of Appellant's issues challenges the propriety of the trial court's determination granting summary judgment.

A legal malpractice claim based on breach of contract, "involves (1\) the existence of a contract, (2\) a breach of a duty imposed by the contract, and (3\) damages." With respect to a legal malpractice claim based on breach of contract, this Court has stated the following:

> The attorney's liability must be assessed under the terms of the contract. Thus, if the attorney agrees to provide her best efforts and fails to do so, an action in assumpsit will accrue. An attorney who agrees for a fee to represent a client is by implication agreeing to provide that client with professional services consistent with those expected of the profession at large.

With respect to a breach of fiduciary duty claim, "a confidential relationship and the resulting fiduciary duty may attach wherever one occupies toward another such a position of advisor or counsellor as reasonably to inspire confidence that he will act in good faith for the other's interest." The leading case in Pennsylvania discussing breach of a fiduciary duty by an attorney with regard to a conflict of interest is *Maritrans GP Inc. v. Pepper, Hamilton & Scheetz*. In *Maritrans*, our Supreme Court upheld the trial court's issuance of a preliminary injunction preventing Pepper Hamilton from representing its former clients' competitors. The Court found that a cause of action for breach of a fiduciary duty against a law firm was actionable where the firm acquired confidential information during the course of its representation. In discussing actionability for breach of a fiduciary duty, our Supreme Court reiterated the following long-standing principles:

> Activity is actionable if it constitutes breach of a duty imposed by statute or by common law. Our common law imposes on attorneys the status of fiduciaries vis a vis their clients; that is, attorneys are bound, at law, to perform their fiduciary duties properly. Failure to so perform gives rise to a cause of action. It is "actionable." At common law, an attorney owes a fiduciary duty to his client; such duty demands undivided loyalty and prohibits the attorney from engaging in conflicts of interest, and breach of such duty is actionable.

The *Maritrans* Court highlighted that Pepper Hamilton "was furnished with substantial confidential commercial information" and "came to know the complete inner-workings of the company along with Maritrans' longterm objectives, and competitive strategies." As explained by the Court, adherence to a fiduciary duty "ensures that clients will feel secure that everything they discuss with counsel will be kept in confidence" and that Pepper Hamilton "had a duty to administer properly their responsibilities to respect the confidences of Maritrans." It further explained that the rationale behind this policy is to prevent an attorney from taking "undue advantage of the confidential communications of such client."

In reaching its determination, the Court in *Maritrans* emphasized the confidential information that Pepper Hamilton garnered during the course of its representations.

Pennsylvania Rule of Professional Conduct 1.9 further addresses attorney duties to former clients and provides, in relevant part, as follows:

> \(a\) A lawyer who has formerly represented a client in a matter shall not thereafter represent another person in the same or a substantially related matter in which that person's interests are materially adverse to the interests of the former client unless the former client gives informed consent. (c) A lawyer who has formerly represented a client in a matter or whose present or former firm has formerly represented a client in a matter shall not thereafter: (1\) use information relating to the representation to the disadvantage of the former client except as these Rules would permit or require with respect to a client, or when the information has become generally known; or (2\) reveal information relating to the representation except as these Rules would permit or require with respect to a client.

The explanatory comment to Rule 1.9(c) offers the following pertinent insight:

> 8 Paragraph (c) provides that information acquired by the lawyer in the course of representing a client may not subsequently be used or revealed by the lawyer to the disadvantage of the client. However, the fact that a lawyer has once served a client does not preclude the lawyer from using generally known information about that client when later representing another client.

In addition, section 59 of the Restatement (Third) of the Law Governing Lawyers defines the term "Confidential Client Information" as "Confidential client information consists of information relating to representation of a client, other than information that is generally known." Comment b to the above definition explains that "the definition includes information that becomes known by others, so long as the information does not become generally known." Furthermore, comment d states the following:

> d\. *Generally known information*. Confidential client information does not include information that is generally known. Such information may be employed by a lawyer who possesses it in permissibly representing other clients and in other contexts where there is a specific justification for doing so. Information might be generally known at the time it is conveyed to the lawyer or might become generally known thereafter. At the same time, the fact that information has become known to some others does not deprive it of protection if it has not become generally known in the relevant sector of the public. Whether information is generally known depends on all circumstances relevant in obtaining the information. Information contained in books or records in public libraries, public-record depositaries such as government offices, or in publicly accessible electronic-data storage is generally known if the particular information is obtainable through publicly available indexes and similar methods of access. Information is not generally known when a person interested in knowing the information could obtain it only by means of special knowledge or substantial difficulty or expense. Special knowledge includes information about the whereabouts or identity of a person or other source from which the information can be acquired, if those facts are not themselves generally known. A lawyer may not justify adverse use or disclosure of client information simply because the information has become known to third persons, if it is not otherwise generally known. Moreover, if a current client specifically requests that information of any kind not be used or disclosed in ways otherwise permissible, the lawyer must either honor that request or withdraw from the representation.

We further observe that there is no Pennsylvania case law directly on point. However, as the Supreme Court of Ohio aptly stated in *Akron Bar Association v. Holder*, "An attorney is not free to disclose embarrassing or harmful features of a client's life just because they are documented in public records or the attorney learned of them in some other way." Likewise, in *Lawyer Disciplinary Board v. McGraw*, the Supreme Court of West Virginia observed that "the ethical duty of confidentiality is not nullified by the fact that the information is part of a public record or by the fact that someone else is privy to it."

Here, the trial court concluded that because the FBI Affidavit was inadvertently appended to a document in an unrelated criminal matter, the information contained therein was public. Specifically, the trial court stated that "the fact that the FBI Affidavit in question was publicly available for many years precludes a determination that the receipt of the improperly filed FBI Affidavit through a breach by Appellees of the attorney-client relationship and duty of fidelity is actionable."

Our review of the record, in the light most favorable to Appellant as the non-moving party, reflects that the trial court erred in granting summary judgment in this case. Indeed, this case presents genuine issues of fact. The record reveals that the FBI Affidavit in question became part of another criminal matter through inadvertence. Even accepting that the FBI Affidavit was publicly available through PACER prior to December 10, 2012, we are left to ponder whether the FBI Affidavit was actually "generally known." All that is acknowledged at this point in the proceedings is that the FBI Affidavit was inadvertently appended to a document in a case that did not involve Appellant as a party. Therefore, it appears that such document was not "indexed" under Appellant's name and that a person interested in the FBI Affidavit "could obtain it only by means of special knowledge." Furthermore, it is unknown exactly how and when the FBI Affidavit came into the possession of the Inquirer and eventually became the subject of an article in the Inquirer during Pepper Hamilton's representation of the Inquirer. Whether Pepper Hamilton committed a breach of its duties to Appellant depends on the answers to these questions. Thus, these questions are sufficient to establish genuine issues of material fact regarding Pepper Hamilton's conduct. Contrary to the trial court's conclusion, in the event that the FBI Affidavit was not generally known information, it appears that Pepper Hamilton breached its duty to Appellant as a former client and such breach was actionable. Accordingly, we reverse the order granting summary judgment.

#### @MatterTennant_Montana2017

These consolidated proceedings include two formal disciplinary complaints filed against Montana attorney David G. Tennant. The complaints, which arise from Tennant's debt collection practices against clients and former clients, will be referenced in this Opinion and Order as the Ray complaint and the Harshman complaint.

[Background]{.casesection}

Tennant represented Richard and Debbie Harshman in an action for eviction of tenants from, and possession of, real property in Hungry Horse, Montana. The Harshmans obtained a default judgment against their tenants for damages to the property, including attorney fees of \$3,063.54. When he was unable to collect the attorney fees through execution on the tenants and the Harshmans did not pay their bill to Tennant's firm, Tennant filed an attorney's lien on the property. He later filed a complaint against the Harshmans alleging breach of contract, account stated, and foreclosure of the attorney's lien, in which action he was granted a default judgment of \$8,148.68. Tennant assigned the judgment to a collection agency, which obtained a writ of execution on the Harshmans' property. A sheriff's sale was held, at which the collection agency was the successful bidder. The Harshmans later redeemed their property.

Both Ray and the Harshmans filed complaints against Tennant with the Office of Disciplinary Counsel, and ODC filed formal disciplinary complaints in both matters. On August 31, 2016, Tennant filed conditional admissions and an affidavit of consent to discipline in these consolidated proceedings, pursuant to Rule 26, Montana Rules for Lawyer Disciplinary Enforcement. ODC objected to Tennant's conditional admissions. On October 20, 2016, the Commission on Practice held a hearing on the complaints and to consider Tennant's conditional admissions. Tennant was present with counsel and testified on his own behalf.

On January 5, 2017, the Commission submitted to this Court its Findings of Fact, Conclusions of Law, and Recommendation for Discipline. The Commission rejected Tennant's conditional admissions. The Commission concluded that ODC failed to carry its burden of proving by clear and convincing evidence any MRPC violations alleged in the Harshman complaint.

The Commission recommends that, as a result of his violations of the Montana Rules of Professional Conduct, Tennant be disciplined by public censure by this Court. The Commission recommends that, in the future, Tennant be required to provide to clients and former clients copies of any attorney's liens he or his firm files against them. In addition, the Commission recommends that, for a period of three years, Tennant be required to provide to ODC copies of any attorney's liens filed by him or his firm, copies of all complaints filed by him or his firm and served against former clients for unpaid fees, and copies of judgments or assignments of judgments obtained by him or his firm against former clients.

ODC has filed written objections to the Commission's findings, conclusions, and recommendation, and Tennant has filed a response.

[Discussion]{.casesection}

ODC argues that the Commission erred in concluding that it failed to prove violation of Rule 1.9, MRPC, in relation to the Harshmans. Rule 1.9(c) provides:

> A lawyer who has formerly represented a client in a matter or whose present or former firm has formerly represented a client in a matter shall not thereafter: (1\) use information relating to the representation to the disadvantage of the former client except as these Rules would permit or require with respect to a client, or when the information has become generally known.

ODC alleged Tennant violated this Rule when he bid on the Harshmans' Hungry Horse property at the sheriff's sale, because Tennant's knowledge of the property derived from his representation of the Harshmans. The Commission determined that because Tennant could have found out that the Harshmans owned property in Hungry Horse via public record and then foreclosed his fee lien and bid at the sheriff's sale, no violation of Rule 1.9 occurred.

As ODC emphasizes, Rule 1.9's language requires that, in order for the attorney to be free from the prohibition against using representation-related information to the disadvantage of a former client, the information at issue must be "generally known."

> Whether information is generally known depends on all circumstances relevant in obtaining the information. Information contained in books or records in public libraries, public-record depositories such as government offices, or in publicly accessible electronic-data storage is generally known if the particular information is obtainable through publicly available indexes and similar methods of access. Information is not generally known when a person interested in knowing the information could obtain it only by means of special knowledge or substantial difficulty or expense. A lawyer may not justify adverse use or disclosure of client information simply because the information has become known to third persons, if it is not otherwise generally known.

Some courts have applied a strict definition of "generally known" in the context of a Rule 1.9 analysis. That the information at issue is generally available does not suffice; the information must be within the basic understanding and knowledge of the public. "The client's privilege in confidential information disclosed to his attorney is not nullified by the fact that the circumstances to be disclosed are part of a public record, or that there are other available sources for such information, or by the fact that the lawyer received the same information from other sources."

In this case, although it would have been possible for Tennant to discover the existence of the Harshmans' property through searches of public records, he undisputedly learned of the property as part of his representation of the Harshmans. Tennant used that information to the Harshmans' disadvantage. We will not interpret the "generally known" provision of Rule 1.9(c) to allow Tennant to take advantage of his former clients by retroactively relying on public records of their information for self-dealing. The Commission erred in concluding that Tennant did not violate Rule 1.9, MRPC.

ODC further claims that, absent the Harshmans' redemption of their property, Tennant would have exceeded his fee claim and lien by receiving a windfall from the sheriff's sale of upwards of \$80,000---his former clients' equity in their property. ODC submits that this is a clear violation of Rule 1.9(c), MRPC. However, the Harshmans did redeem their property, and ODC's assumptions do not satisfy its burden of proof.

[Sanctions]{.casesection}

Finally, ODC argues that the Commission's recommended sanctions are inadequate given Tennant's unethical conduct and will not deter the same type of conduct by other Montana attorneys. ODC had recommended that Tennant be suspended from the practice of law for at least seven months and that he be required to retake and pass the Multistate Professional Responsibility Exam.

We have concluded that ODC established one ethical violation in addition to those recognized by the Commission. However, that violation ultimately did not harm Tennant's clients---the Harshmans redeemed their property. Further, the additional violation does not undermine the Commission's overall conclusions on the evidence presented, and on this record we are not inclined to deviate from the discipline recommended by the Commission.

#### @McClureThompson_9thCircuit2003

Oregon state prisoner Robert A. McClure appeals the district court's denial of his habeas corpus petition challenging his jury trial conviction for three aggravated murders. McClure's original defense attorney, Christopher Mecca, placed an anonymous telephone call to law enforcement officials directing them to the locations of what turned out to be the bodies of two children whom McClure was ultimately convicted of killing. The district court rejected McClure's arguments that the disclosure constituted ineffective assistance of counsel, holding there was no breach of the duty of confidentiality and no actual conflict of interest. We affirm.

[Background]{.casesection}

On Tuesday, April 24, 1984, the body of Carol Jones was found in her home in Grants Pass, Oregon. She had been struck numerous times on the head, arms and hands with a blunt object. A gun cabinet in the home had been forced open and a .44 caliber revolver was missing. Two of Jones' children---Michael, age 14, and Tanya, age 10---were also missing. The fingerprints of Robert McClure, a friend of Jones, were found in the blood in the home. On Saturday, April 28, McClure was arrested in connection with the death of Carol Jones and the disappearance of the children.

That same day, McClure's mother contacted attorney Christopher Mecca and asked him to represent her son. As discussed in more detail below, sometime in the next three days, under circumstances described differently by McClure and Mecca, McClure revealed to Mecca the separate remote locations where the children could be found. On Tuesday, May 1, Mecca, armed with a map produced during his conversations with McClure, arranged for his secretary to place an anonymous phone call to a sheriff's department telephone number belonging to a law enforcement officer with whom Mecca had met earlier.

Later that day and the following day, sheriff's deputies located the children's bodies, which were in locations more than 60 miles apart. The children had each died from a single gunshot wound to the head. Mecca then withdrew from representation. On May 3, McClure was indicted for the murders of Carol Jones and her children. At trial, the prosecution produced extensive evidence that stemmed from the discovery of the children's bodies and introduced testimony regarding the anonymous phone call. McClure was found guilty of all three murders and was sentenced to three consecutive life sentences with 30-year minimums. On direct appeal, his conviction was affirmed without opinion.

The parties agree that Mecca and McClure met at the jail and spoke on the telephone on a number of occasions between April 28 and May 1. However, the substance of the conversations between McClure and Mecca are the subject of significant dispute.

Mecca recorded his account in notes that he wrote immediately after the children's bodies were discovered. Mecca also gave deposition testimony for McClure's state post conviction proceeding, submitted an affidavit prior to McClure's federal habeas proceeding, and gave testimony at the federal district court evidentiary hearing in the habeas proceeding. In his notes, Mecca wrote that McClure had initially claimed that he was "being framed" for the murder, but that he was nervous about his fingerprints being in the house. He had asked Mecca to help him remove some other potential evidence, which Mecca declined to do.

According to the notes, on the Sunday night after McClure's Saturday arrest, Mecca received a "frantic phone call" from McClure's sister, who was convinced that McClure had murdered Jones, but had reason to believe that the children were alive and perhaps "tied up or bound someplace." In response, Mecca set up a meeting with McClure, his sister and his mother at the jail, at which McClure's sister "directly confronted McClure and begged him to divulge information about the whereabouts of the kids." McClure and his sister discussed how McClure sometimes did "crazy things" when he was using drugs, but McClure strongly maintained his innocence as to Carol Jones' murder and the children's disappearance.

According to his notes, when Mecca next spoke with McClure on Monday, McClure was less adamant in his denial. Mecca described how, when they met on Monday afternoon, McClure began to tell him of his "sexual hallucinations and fantasies" involving young girls and about "other situations that happened in the past involving things he would do while under the influence of drugs." "It was at that time," Mecca wrote, "when I realized in my own mind that he had committed the crime and the problem regarding the children intensified." Mecca wrote that he "was extremely agitated over the fact that these children might still be alive."

After a Monday night visit to the crime scene, Mecca returned to the jail to speak with McClure again, at which time he "peeled off most of the outer layers of McClure and realized that there was no doubt in my mind that he had killed Carol Jones." McClure told Mecca he wanted to see a psychiatrist, then launched into "bizarre ramblings." "Each time as I would try to leave," Mecca recalled in his notes, "McClure would spew out other information, bits about the children, and he would do it in the form of a fantasy." Mecca wrote that he "wanted to learn from him what happened to those children." He told McClure "that we all have hiding places, that we all know when we go hiking or driving or something, we all remember certain back roads and remote places," and that McClure "related to me one place where a body might be" and then "described where the other body would be located." Mecca wrote that he "wasn't going to push him for anything more," but "when I tried to leave, he said, and he said it tentatively, ‘would you like me to draw you a map and just give you an idea?' and I said ‘Yes' and he did." Mecca recorded that "at that time, I felt in my own mind the children were dead, but, of course, I wasn't sure."

Very late on Monday evening, McClure telephoned Mecca at home and said, "I know who did it." Mecca recorded in his notes that the next morning he went to meet with McClure, and asked him about this statement. McClure told Mecca that "Satan killed Carol." When Mecca asked, "What about the kids?" McClure replied, "Jesus saved the kids." Mecca wrote in his notes that this statement "hit me so abruptly, I immediately assumed that if Jesus saved the kids, that the kids are alive." Mecca wrote that he "kind of felt that McClure was talking about a sexual thing, but, in any event, I wasn't sure."

Mecca's notes indicate that on Monday, before McClure made the "Jesus saved the kids" comment, and again on Tuesday, immediately after the meeting at which he made that comment, Mecca had conversations with fellow lawyers, seeking advice regarding "the dilemma that he faced." After the second of these conversations, which took place Tuesday morning, Mecca arranged for a noon meeting with the undersheriff and the prosecutor. At the meeting, he "mentioned to them that I may have information which would be of interest to the State" and attempted to negotiate a plea. When the prosecutor responded that there would be no deal, Mecca recorded in his notes, "I had made up my mind then that I had to do the correct thing. The only option I had, as far as I was concerned, was to disclose the whereabouts of the bodies." (Recall that by the time Mecca wrote these notes, he had learned that the children were dead.) A law enforcement official testified in a federal court deposition that, after both the state bar association and the attorney general "recommended that it would be unwise for Mr. Mecca to provide us information," Mecca "indicated that, even though there might be sanctions, that he still was wanting to provide information that he had regarding the children." Mecca stated that when he spoke with McClure's sister and mother, they were adamant that he do whatever he could to locate the children, and that "they were still under the impression that one or both of the children were alive, or at least there was a chance they were alive."

Mecca then returned to the jail Tuesday afternoon and, according to his notes, "advised McClure that if there was any possibility that these children were alive, we were obligated to disclose that information in order to prevent, if possible, the occurrence of what could be the elevation of an assault to a murder, for instance. I further indicated that if he really requested psychiatric help, to help him deal with his problem, that this perhaps was the first step." "In any event," Mecca recorded in his notes, "he consented." "I arranged to have the information released anonymously to the Sheriff's Department with directions to the bodies." He noted that there was "no provable way to connect" McClure to the information, "but I think it's rather obvious from those in the know, who the information came from."

In the deposition conducted in conjunction with McClure's state habeas proceeding, Mecca gave a similar account of the events surrounding disclosure of the locations of the children. He emphasized that "it all happened relatively quickly" and that there was a public "hysteria about these kids, whether the kids were dead, whether the kids were alive." Mecca reiterated that much of the later conversations with McClure consisted of hypotheticals and fantasies---"like he was playing a game with me"---but that it was clear that McClure wanted to tell him where the children were. Mecca stated in his deposition that "the condition of the children was never discussed," but that the insistence by McClure's mother and sister that McClure wouldn't hurt the children put him "in this mode of thinking these kids might be alive someplace."

Mecca testified in his deposition that he thought that if the children were alive, it might relieve McClure of additional murder charges, but that the children were his main concern. When asked if he was "primarily concerned with the children's welfare or with Mr. McClure's welfare" at the time he disclosed the location of the bodies, Mecca replied, "At that point I was concerned with the children's welfare." When asked if he explained to McClure that "if they were in fact dead, that revealing the location of the bodies would lead to evidence which could implicate Mr. McClure in their murders," Mecca answered: "No. I don't think I had the presence of mind to sit down and analyze every single detail and go over with him, ‘Geez, you know, if they are really dead, why don't you tell me.'" However, he testified, "McClure knew I thought there was a chance those kids were alive."

Mecca testified in the deposition that the plan to place the anonymous telephone call was his, but that McClure knew that he planned to do it, and that, in his late-night call, McClure had made clear that he "absolutely wanted to disclose where those kids were." When asked, "Did he give you permission to reveal this information?" Mecca responded, "Oh, yes."

In a 1999 affidavit submitted in conjunction with McClure's federal habeas proceeding, Mecca gave an additional statement regarding McClure's consent: "Mr. McClure did not orally or expressly consent to the disclosure. I inferred consent from the circumstances, specifically, the fact that Mr. McClure called me at home on several occasions with the request that I see him at the jail, and the fact that he drew a map of the location of the bodies of the victim in his own handwriting and gave me the map."

In addition to reviewing Mecca's notes, his state-court deposition testimony, and his federal-court affidavit, the federal district court heard testimony from Mecca at an evidentiary hearing. In this testimony, Mecca emphasized that he generally takes a low-keyed approach to questioning his clients. He also emphasized that McClure was "fully engaged in his defense" and "was running the show." Every time they met or conversed, he said, it was at McClure's request. He said that he and McClure "discussed at various times various methods of what I was going to do with this information." Mecca testified that McClure never expressly said that he consented to the disclosure, and that Mecca never asked for such consent. He confirmed his earlier testimony that he inferred consent, and added for the first time that this inference was based on McClure's nodding, saying "okay," and otherwise manifesting assent. He said this was what he had meant when he had written in his notes that McClure consented. Mecca also reiterated that he never told McClure of the legal risks involved in disclosing the children's locations.

Mecca testified that after the Monday conversation with McClure, "the conclusion I came to was that, without telling me, he told me he had killed three people." But he stated that he did not confirm that conclusion by directly asking McClure if it was the case. Instead, he said, he emphasized to McClure that if there was a chance the children were alive, they needed to save them, and in response McClure "never said they were dead." After the "Jesus saved the kids" comment on Tuesday, Mecca testified, "I allowed myself to believe that these kids might somehow be alive." When asked on cross examination whether, at the time he decided to make the anonymous call, he thought there was "a strong possibility the kids still may be alive," Mecca responded that he "felt that it was a possibility. I wouldn't say a strong possibility." One of the reasons he felt this possibility existed, he said, was that his "client had not indicated anything differently." He testified that the possibility of saving his client from additional murder charges "was something that was going through his mind" during his decisionmaking. He noted that the weather at that time of year was "warm" and "pleasant," and that if the children had been left in the woods it was possible that the weather would not have contributed to their death.

McClure disagreed with Mecca's account of the events leading up to the anonymous call. In testimony in both the state and federal district court proceedings, he repeatedly insisted that he did not give Mecca permission to disclose any information and that he was reassured that everything he told Mecca would remain confidential. He said Mecca pressured him into disclosing information by setting up the meeting with his sister and mother, and then disseminated that information to his detriment without his knowledge or consent.

McClure testified that Mecca never asked him directly if the children were alive or dead, but that the hypothetical conversations that they had were about where Mecca might find dead "bodies," not live "children." He said his disclosure of those locations was his way of admitting to having killed them. He testified that Mecca never told him that he intended to make an anonymous telephone call.

McClure's single claim is that habeas relief is appropriate because he received ineffective assistance of counsel under the Sixth Amendment. He asserts three independent grounds on which ineffectiveness could be found. The first two are based on alleged breaches of Mecca's professional duty to maintain client confidentiality. McClure argues that this duty was breached both by a failure to obtain informed consent prior to the disclosure of confidential information and by a failure to inquire thoroughly before concluding that disclosure was necessary to prevent the deaths of the children. The third ground is that the primacy of Mecca's concern for the victims constituted a conflict of interest that rendered Mecca's counsel constitutionally ineffective.

[The Duty of Confidentiality]{.casesection}

McClure contends that Mecca's disclosure of McClure's confidential statements about the location of the children violated McClure's Sixth Amendment right to effective assistance of counsel. ABA Model Rule of Professional Conduct 1.6 sets forth a widely recognized duty of confidentiality: "A lawyer shall not reveal information relating to representation of a client." Our legal system is premised on the strict adherence to this principle of confidentiality, and "the Supreme Court has long held attorneys to stringent standards of loyalty and fairness with respect to their clients." There are few professional relationships "involving a higher trust and confidence than that of attorney and client," and "few more anxiously guarded by the law, or governed by sterner principles of morality and justice."

As critical as this confidential relationship is to our system of justice, the duty to refrain from disclosing information relating to the representation of a client is not absolute. The ABA Model Rule provides a list of well-established exceptions to the general principle of confidentiality, two of which are pertinent to the present case. First, a lawyer may reveal confidential information if "the client consents after consultation." Second, "a lawyer may reveal such information to the extent the lawyer reasonably believes necessary to prevent the client from committing a criminal act that the lawyer believes is likely to result in imminent death or substantial bodily harm." The relevant provisions of the Oregon Code of Professional Responsibility echo both the general principle of confidentiality and these particular exceptions.

The duty of an attorney to keep his or her client's confidences in all but a handful of carefully defined circumstances is so deeply ingrained in our legal system and so uniformly acknowledged as a critical component of reasonable representation by counsel that departure from this rule "makes out a deprivation of the Sixth Amendment right to counsel." With this uncontested premise as our starting point, we examine whether the circumstances surrounding Mecca's revelation of a confidential client communication excused his disclosure, such that his performance could have been found by the state court and the district court to be constitutionally adequate. Specifically, we look to see if Mecca's client "consented after consultation" or if Mecca "reasonably believed the revelation was necessary to prevent the client from committing a criminal act that Mecca believed was likely to result in imminent death or substantial bodily harm." We conclude that the first of these exceptions does not apply to justify Mecca's behavior, but that the second does.

[1. Consent After Consultation]{.casesubsection}

McClure argues that Mecca rendered constitutionally ineffective assistance because he breached his duty of confidentiality by not obtaining McClure's informed consent before disclosure. The professional standard that allows disclosure of confidential communications when "the client consents after consultation" has two distinct parts: consent by the client, and consultation by the counsel. Our required deference to both the state court's factual findings and the district court's credibility determination leads us to hold that the first of these elements was met. However, despite this deference, we hold that the second element was not met.

The state court made the following finding: "Trial counsel received petitioner's permission to anonymously disclose the whereabouts of the children to the authorities." AEDPA demands that this finding of consent be presumed correct and accepted as true unless McClure rebuts the presumption with clear and convincing evidence to the contrary. The district court, whose credibility determinations are given great weight, and whose findings of fact are reviewed only for clear error, explicitly accepted that finding, and stated that it did "not find credible petitioner's assertion that he did not consent to the disclosure of the information contained in the map." It found that McClure "voluntarily drew the map and gave it to Mecca," and that, even in the absence of the words "I consent," Mecca could infer consent from the circumstances and from McClure's conduct. It stated that it found Mecca's testimony "entirely credible and corroborated by his contemporaneous notes which state specifically that petitioner consented to the disclosure."

There is evidence in the record to cast doubt on these consent findings---indeed, enough evidence that if we were sitting as trier of fact, we might find that McClure did not give consent. McClure repeatedly denied that he consented, and certainly would have had good reason not to consent. The state court determination that McClure had consented was made before Mecca clarified that the consent was implied and not express. Moreover, it was based on Mecca's unconditional affirmative response, in his state-court deposition, to the question of whether permission to reveal the information was granted. Only later, in the federal habeas proceeding, did it come to light that Mecca had merely inferred McClure's consent.

Further, Mecca's account of the circumstances from which he inferred McClure's consent changed over the years. His initial account stated that he inferred consent from the fact that McClure called him at home, drew the map, and gave it to him. It is a significant leap to infer McClure's consent to disclose the map to law enforcement authorities from the fact that McClure gave the map to Mecca. Virtually all clients provide information to their attorneys, but they do so assuming that the attorneys will not breach their duty of confidentiality. Further, Mecca's behavior at the time of the disclosure suggested that he thought he lacked the kind of informed consent that would give him the legal authority to act.

However, the findings reached by the state and district courts are not so "implausible"---particularly in light of the district court's credibility determinations---that they produce a "definite and firm conviction that a mistake has been committed." The district court believed Mecca's account at the evidentiary hearing, disbelieved McClure's, and found the discrepancies in Mecca's testimony to be "minor." Because there are "two permissible views of the evidence, the factfinder's choice between them cannot be clearly erroneous." We therefore hold that McClure gave his consent to the disclosure.

However, the mere fact of consent is not sufficient to excuse what would otherwise be a breach of the duty of confidentiality. Consent must also be informed. That is, the client can provide valid consent only if there has been appropriate "consultation" with his or her attorney. Mecca's consultation with McClure regarding his consent to disclosure was addressed in the state court and district court findings. Both courts found that Mecca did not advise McClure about the potential harmful consequences of disclosure. The state court found that "before petitioner authorized trial counsel to reveal the childrens' locations to authorities, trial counsel did not advise petitioner that if authorities located the children, he could be further implicated in the criminal activity and the evidence against him would be stronger." The district court found that "Mecca admits that he did not advise petitioner of all potential adverse consequences."

Emphasizing that McClure was "fully engaged" in his defense and that he was told that the obligation to disclose the children's location arose only if the children were alive, the district court held that "under the circumstances, Mecca's failure to advise petitioner of all possible adverse consequences was not unreasonable." We believe this holding is inconsistent with the consultation requirement because it does not attach sufficient importance to the role that an attorney's advice plays in the attorney-client relationship. It is not enough, as the district court suggests, that McClure "did not dissuade Mecca from his intentions" to share the map with authorities. The onus is not on the client to perceive the legal risks himself and then to dissuade his attorney from a particular course of action. The district court's statement that Mecca was relieved of his duty to counsel his client because "common sense dictated that petitioner understood the consequences of his actions" fails to acknowledge the seriousness of those consequences and the importance of good counsel regarding them. Even in cases in which the negative ramifications seem obvious---for example, when criminal defendants opt for self-representation---we require that a criminal defendant's decision be made on the basis of legal guidance and with full cautionary explanation. We disagree with the district court's conclusion that this case was so exceptional that the attorney's basic consultation duties did not apply. It is precisely because the stakes were so high that Mecca had an obligation to consult carefully with his client. In the absence of some other exception to the duty of confidentiality, his failure to obtain informed consent would demonstrate constitutionally deficient performance under the Sixth Amendment.

[2. Prevention of Further Criminal Acts]{.casesubsection}

The State contends that, even if Mecca did not have informed consent, his revelation of client confidences did not amount to ineffective assistance of counsel because he reasonably believed that disclosing the location of the children was necessary in order to prevent further criminal acts. That is, Mecca reasonably believed that revealing the children's locations could have prevented the escalation of kidnapping to murder. This is not a traditional "prevention of further criminal acts" case, because all of the affirmative criminal acts performed by McClure had been completed at the time Mecca made his disclosure. Mecca was thus acting to prevent an earlier criminal act from being transformed by the passage of time into a more serious criminal offense. Nonetheless, we believe that where an attorney's or a client's omission to act could result in "imminent death or substantial bodily harm" constituting a separate and more severe crime from the one already committed, the exception to the duty of confidentiality may be triggered.

This exception, however, requires that an attorney reveal confidences only to the extent that he "reasonably believes necessary to prevent" those criminal acts and imminent harms. In assessing the effectiveness of McClure's counsel in light of this standard, the first step is to determine what a constitutionally effective counsel should be required to do before making a disclosure. That is, we must determine what basis the attorney had for believing that the precondition to disclosure was present, and how much investigation he or she must have undertaken before it was "reasonable" to "believe it necessary" to make the disclosure to prevent the harm. The second step is to apply that standard to the facts surrounding Mecca's decision to disclose.

There is remarkably little case law addressing the first analytical step. Citing cases dealing with a separate confidentiality exception allowing attorneys to reveal intended perjury on the part of their clients, McClure argues that a lawyer must have a "firm factual basis" before adopting a belief of impending criminal conduct. However, we are not persuaded that the perjury cases provide the proper standard.

McClure is correct that our inquiry must acknowledge the importance of the confidential attorney-client relationship and the gravity of the harm that results from an unwarranted breach of that duty. However, the standard applied in the professional responsibility code asks only if the attorney "reasonably believes" disclosure is necessary to prevent the crime. Further, the *Strickland* standard likewise focuses on "whether counsel's assistance was reasonable considering all the circumstances." Accordingly, we hold that the guiding rule for purposes of the exception for preventing criminal acts is objective reasonableness in light of the surrounding circumstances.

Reasonableness of belief may be strongly connected to adequacy of investigation or sufficiency of inquiry in the face of uncertainty. Significantly, as indicated above, *Strickland* explicitly imposes a duty on counsel "to make reasonable investigations or to make a reasonable decision that makes particular investigations unnecessary." In any ineffectiveness of counsel case, "a particular decision not to investigate must be directly assessed for reasonableness in all the circumstances, applying a heavy measure of deference to counsel's judgments." Thus, in determining whether Mecca's disclosure of confidential client information constituted ineffective assistance of counsel, we must examine whether Mecca "reasonably believed" that the precondition for disclosure existed and whether, in coming to that belief, Mecca conducted a reasonable investigation and inquiry.

The parties vigorously debate both the reasonableness of Mecca's belief that the children were alive and the reasonableness of his level of investigation and inquiry on that point. McClure argues that any conclusion that Mecca had a reasonable belief is unsupported because Mecca himself indicated that he harbored doubts as to the children's state, and yet failed to inquire further. He points to evidence in the record that Mecca, at least at some stages of his representation of McClure, did not believe the children were alive—or that he, at the least, suspected that they were dead. It is indisputable that this evidence exists, and that most of this evidence is contained in statements by Mecca himself, whom the district court found "highly credible." Mecca's notes state that, after McClure drew the map, Mecca "felt in my own mind that the children were dead, but, of course, I wasn't sure." He testified in the district court evidentiary hearing that the conclusion he came to was that, "without telling me, McClure had told me he had killed three people." And he stated in this same testimony that, at the time he had his secretary place the anonymous call, he thought there was a "possibility," but not a "strong possibility," that the children were alive.

McClure argues that the statement Mecca says abruptly changed his mind about the status of the children---McClure's comment that "Jesus saved the kids"---was so vague and ambiguous that it was not a sufficient basis for a "reasonable belief" that disclosure was necessary. Despite Mecca's acknowledgment that this comment led him only to "assume" that McClure was saying the children were alive, Mecca never directly asked a question that could have confirmed or refuted that assumption. Mecca repeatedly testified that he never squarely asked about the condition of the children or whether McClure had killed them. Accordingly, McClure argues, any finding that Mecca believed the children were alive is not sufficient to establish effective assistance of counsel, because Mecca's failure to engage in a reasonable level of investigation and inquiry rendered that belief unreasonable.

Given the implicit factual findings of the state court, and the explicit factual findings of the district court, which are at least plausible in light of the record viewed in its entirety, we disagree. The ultimate question of the reasonableness of Mecca's belief is a question of law, which we review *de novo*. In answering that question, however, we look to the facts and circumstances of the case, and as to these facts, we give great deference to the findings of the state court and the district court.

The district court made a number of specific findings regarding the factual basis for Mecca's belief that the children were alive. It found that only McClure knew the true facts and that he deliberately withheld them, leading Mecca to believe the children were alive. It found that McClure controlled the flow of information, and that when Mecca informed McClure that he had an obligation to disclose the children's whereabouts if there were a chance they were alive, McClure did not tell him they were dead. It specifically rejected McClure's assertion that Mecca in fact believed that the children were dead or that he lacked information that they were alive, noting that at the time there was no evidence, other than their disappearance and the passage of time, that they had been injured or killed.

The district court also made specific factual findings regarding the nature of Mecca's investigation and inquiry. It found that "Mecca attempted to discern whether the children were alive" and "that Mecca investigated to the best of his ability under extremely difficult circumstances." McClure argues that these findings are clearly erroneous, and that "arguments that Mr. McClure was manipulative and difficult are essentially irrelevant to the lawyer's obligations." But *Strickland* holds otherwise. The *Strickland* Court emphasized that "the reasonableness of counsel's actions may be determined or substantially influenced by the defendant's own statements or actions." More specifically, it held that "what investigation decisions are reasonable depends critically" on the "information supplied by the defendant."

This is a close case, even after we give the required deference to the state and district courts. The choices made by McClure's counsel give us significant pause, and, were we deciding this case as an original matter, we might decide it differently. But we take as true the district court's specific factual findings as to what transpired---including what McClure said and did, and what actions Mecca took and why he took them---and we conclude that Mecca made the disclosure "reasonably believing it was necessary to prevent the client from committing a criminal act that Mecca believed was likely to result in imminent death or substantial bodily harm." Mecca therefore did not violate the duty of confidentiality in a manner that rendered his assistance constitutionally ineffective.

## Attorney-Client Privilege

#### @Rest2dLawGoverningLawyers

::: legalcode
##### § 68. Attorney-Client Privilege

Except as otherwise provided in this Restatement, the attorney-client privilege may be invoked as provided in § 86 with respect to:

-   \(1\) a communication
-   \(2\) made between privileged persons
-   \(3\) in confidence
-   \(4\) for the purpose of obtaining or providing legal assistance for the client.

##### § 69. Attorney-Client Privilege—"Communication"

A communication within the meaning of § 68 is any expression through which a privileged person, as defined in § 70, undertakes to convey information to another privileged person and any document or other record revealing such an expression.

##### § 70. Attorney-Client Privilege—"Privileged Persons"

Privileged persons within the meaning of § 68 are the client (including a prospective client), the client's lawyer, agents of either who facilitate communications between them, and agents of the lawyer who facilitate the representation.

##### § 71. Attorney-Client Privilege—"In Confidence"

A communication is in confidence within the meaning of § 68 if, at the time and in the circumstances of the communication, the communicating person reasonably believes that no one will learn the contents of the communication except a privileged person as defined in § 70 or another person with whom communications are protected under a similar privilege.

##### § 72. Attorney-Client Privilege—Legal Assistance as the Object of a Privileged Communication

A communication is made for the purpose of obtaining or providing legal assistance within the meaning of § 68 if it is made to or to assist a person:

-   \(1\) who is a lawyer or who the client or prospective client reasonably believes to be a lawyer; and
-   \(2\) whom the client or prospective client consults for the purpose of obtaining legal assistance.

##### § 75. The Privilege of Co-Clients

-   \(1\) If two or more persons are jointly represented by the same lawyer in a matter, a communication of either co-client that otherwise qualifies as privileged under §§ 68-72 and relates to matters of common interest is privileged as against third persons, and any co-client may invoke the privilege, unless it has been waived by the client who made the communication.
-   \(2\) Unless the co-clients have agreed otherwise, a communication described in Subsection (1\) is not privileged as between the co-clients in a subsequent adverse proceeding between them.

##### § 76. The Privilege in Common-Interest Arrangements

-   \(1\) If two or more clients with a common interest in a litigated or nonlitigated matter are represented by separate lawyers and they agree to exchange information concerning the matter, a communication of any such client that otherwise qualifies as privileged under §§ 68-72 that relates to the matter is privileged as against third persons. Any such client may invoke the privilege, unless it has been waived by the client who made the communication.
-   \(2\) Unless the clients have agreed otherwise, a communication described in Subsection (1\) is not privileged as between clients described in Subsection (1\) in a subsequent adverse proceeding between them.
:::

::: legalcode
##### § 77. Duration of the Privilege

Unless waived (see §§ 78-80) or subject to exception (see §§ 81-85), the attorney-client privilege may be invoked as provided in § 86 at any time during or after termination of the relationship between client or prospective client and lawyer.

##### § 86. Invoking the Privilege and Its Exceptions

-   \(1\) When an attempt is made to introduce in evidence or obtain discovery of a communication privileged under § 68:
    -   \(a\) A client, a personal representative of an incompetent or deceased client, or a person succeeding to the interest of a client may invoke or waive the privilege, either personally or through counsel or another authorized agent.
    -   \(b\) A lawyer, an agent of the lawyer, or an agent of a client from whom a privileged communication is sought must invoke the privilege when doing so appears reasonably appropriate, unless the client:
        -   \(i\) has waived the privilege; or
        -   \(ii\) has authorized the lawyer or agent to waive it.
    -   \(c\) Notwithstanding failure to invoke the privilege as specified in Subsections (1\)(a) and (1\)(b), the tribunal has discretion to invoke the privilege.
-   \(2\) A person invoking the privilege must ordinarily object contemporaneously to an attempt to disclose the communication and, if the objection is contested, demonstrate each element of the privilege under § 68.
-   \(3\) A person invoking a waiver of or exception to the privilege (§§ 78-85) must assert it and, if the assertion is contested, demonstrate each element of the waiver or exception.
:::

#### @JonesUS_DCCourtofAppeals2003

After a jury trial, appellant was convicted of first-degree burglary, first-degree sexual abuse, first-degree felony murder, and second-degree murder. On appeal he contends that the trial court erred when it ruled that the attorney-client privilege did not require the exclusion of testimony about a conversation that appellant had with his girlfriend (at the time), who was an attorney employed by the federal government. We affirm on the merits, and remand for the sole purpose of vacating a redundant conviction.

[I]{.casesection}

On Saturday, March 23, 1996, at about 10:00 a.m., Metropolitan Police officers found Darcie Silver dead in her apartment after they received a call from her concerned co-workers reporting that she had failed to show up for work. The medical examiner determined that the cause of death was asphyxia by strangulation; other injuries indicated that she might also have been smothered. In addition, there were burns around her genital area; pieces of burned newspaper were found in the vicinity of her crotch. A vaginal swab revealed the presence of male deoxyribonucleic acid (DNA). In addition, investigators found semen stains on Ms. Silver's nightgown and on a denim jacket recovered from her apartment. The DNA evidence was later matched to appellant through testing by the FBI.

A police investigation revealed that on Friday evening, March 22, Ms. Silver had dinner with a co-worker from her job at Bread & Circus, a supermarket in the Georgetown area of the city. She returned to her apartment at approximately 10:00 p.m. and spoke to her father on the telephone from 10:47 p.m. on Friday until 12:03 a.m. on Saturday.

Two neighbors in Ms. Silver's apartment building heard a knocking at the front door of the building at about 2:30 a.m. on Saturday. One of the neighbors looked out a window and saw a "stocky" man with a fair to medium complexion at the door. This description was similar to that of appellant, who is a weightlifter and bodybuilder. Both neighbors heard the man respond to the building intercom using the name "Darcie." They then heard him say that he had locked himself out of his apartment and needed to borrow a telephone. The intercom made a buzzing noise, which unlocked the front door, and the man walked upstairs to the area of Ms. Silver's apartment. About fifteen minutes later, one neighbor heard a "crash" coming from Silver's apartment, and the other heard a loud "thump."

[II]{.casesection}

Appellant's primary argument on appeal is that the court erred when it ruled that the attorney-client privilege did not attach to a conversation that he had with his girlfriend at the time, Tina Ducharme, who was also a lawyer.

After Darcie Silver was murdered, the police interviewed several employees, including appellant, at the Bread & Circus store where Ms. Silver worked. The police requested hair and blood samples from appellant, but he declined to give them. He told the police that his girlfriend was a lawyer and that he "wanted to talk to her first and he even invited them to come to his house to talk to them if they wanted to, but only in her company." Later appellant called his girl friend, Tina Ducharme, a lawyer who worked for the federal government. At the time, she was away on business in San Diego. Appellant left a message at her hotel there, and she returned his call some time thereafter.

During their telephone conversation, appellant told Ms. Ducharme about the police interview at Bread & Circus. Defense counsel moved to exclude any testimony from Ms. Ducharme about that conversation. At a pre-trial hearing on the motion, Ms. Ducharme testified that appellant "told me that the police had been by his work and had questioned him and several other people who used to work with Darcie and had asked for blood samples from several individuals." Ms. Ducharme's response to appellant's concern was that "obviously he didn't have to provide the police with a sample if they didn't have a warrant." She also asked him, however, "why he wouldn't, since it would clear the air. Obviously he didn't have anything to do with it or didn't have anything to be concerned about. I didn't understand why he wouldn't just go ahead and do it." Appellant also told her that "he had been in Darcie's apartment before, and he questioned whether or not some fingerprints of his would be remaining in the apartment," particularly on some drinking glasses. Ms. Ducharme replied with the "common sense advice" that "probably Darcie had washed her glasses in the intervening amount of time." Finally, appellant asked "what if he had gone to the bathroom and left some sperm in there?" Ms. Ducharme laughed and commented that "unless he was masturbating in her bathroom, I really didn't think that would be a concern." Ms. Ducharme testified that appellant never said anything about her representing him in a criminal matter, nor did she intend to advise appellant as a lawyer, adding, "I wasn't qualified to advise anyone on criminal matters." Appellant, in fact, had never asked her to perform any legal work on his behalf. Besides, she said, she was barred by a regulation from representing any private individual "either criminally or civilly" because she was a government lawyer. Further, she believed the conversation was a typical call between boyfriend and girlfriend: "when either of us had a problem, we would call the other person to ask their advice or tell them about it."

Appellant's account of the conversation was different. He stated that he telephoned Ms. Ducharme because he "wanted to know what kind of position I would be putting myself in by giving hair and blood samples." Appellant said that he called her "because she's an attorney" and that he "was seeking legal advice." He testified, "I never thought she could be subpoenaed or anything because she was an attorney." On the basis of his prior experience with other attorneys, appellant believed their conversation would remain confidential.

At the close of the hearing, the court ruled that the conversation was not protected by the attorney-client privilege. Accepting Ms. Ducharme's version of the conversation as credible, the court found appellant's testimony incredible because he "kept switching around on the witness stand as if he was waiting on which way to go." In addition, the court ruled that the only thing Ms. Ducharme "said as a lawyer" was that appellant did not have to give the police hair and blood samples, which he had already elected not to do. Otherwise, said the court, the types of questions appellant asked Ms. Ducharme were "what if" questions that were more scientific than legal:

> They were questions about—they're scientific questions. And she wasn't a criminal lawyer to begin with. What if I used a glass, would the fingerprints still be there? Not a legal question. What if I went to the bathroom, would I have semen there? That's not a legal question. None of these were legal questions. The only legal question in this thing he already knew the answer to.

As a result, the court refused to allow appellant to invoke the attorney-client privilege, and Ms. Ducharme's testimony about the telephone conversation was later introduced into evidence at trial.

In the case at bar, the court heard testimony about the nature and substance of the conversation between appellant and his one-time girl friend, Ms. Ducharme. It made a credibility determination about the contents of the conversation and a factual finding that Ms. Ducharme was not acting as an attorney, but as a friend. On this record we see no reason to depart from our usual standard of review for factual findings by a trial court; *i.e.*, we must uphold that court's determination of the facts unless it is "plainly wrong or without evidence to support it." In particular, a trial court's "findings of fact relevant to the essential elements of a claim of attorney-client privilege will not be overturned unless clearly erroneous." This standard of review places a heavy burden on appellant. Because appellant has not shown that the trial court's factual findings were clearly erroneous or, in the words of our statute, "plainly wrong," we uphold the court's rejection of his claim of privilege.

The attorney-client privilege is the oldest of the established privileges for confidential communications. Its main purpose is to encourage full and frank communication between attorneys and their clients. Nevertheless, courts construe the attorney-client privilege narrowly to protect only those purposes which it serves. Thus the privilege applies only in the following circumstances:

> \(1\) where legal advice of any kind is sought (2\) from a professional legal advisor in his capacity as such, (3\) the communications relating to that purpose, (4\) made in confidence (5\) by the client, (6\) are at his instance permanently protected (7\) from disclosure by himself or by the legal adviser, (8\) except the protection be waived.

The burden of proving that the attorney-client privilege shields a particular communication from disclosure rests with the party asserting the privilege. This means that the party asserting the privilege must clearly show that the communication was made "in a professional legal capacity." "In general, American decisions agree that the privilege applies if one of the significant purposes of a client in communicating with a lawyer is that of obtaining legal assistance."

Whether a purpose is significantly that of obtaining legal assistance or is for a nonlegal purpose depends upon the circumstances, including the extent to which the person performs legal and nonlegal work, the nature of the communication in question, and whether or not the person had previously provided legal assistance relating to the same matter.

In the case of someone seeking advice from a friend who is also a lawyer, the lawyer-friend must be giving advice as a lawyer and not as a friend in order for the privilege to attach. The nature of the relationship is a factual question for the trial court to decide.

Finally, the relationship between attorney and client hinges on the client's intention to seek legal advice and his belief that he is consulting an attorney. In this case the government argues that the conversation in question was not privileged because Ms. Ducharme was not a criminal lawyer; because, as a government employee, she was barred by a regulation from representing appellant—or any other individual—in a private capacity; and because she believed that she was speaking to appellant as his girlfriend and not as a lawyer.[^chap5-1] These arguments fall short, however, because the intent of the person seeking advice is assessed from that person's viewpoint, not that of the attorney. The issue ultimately is what appellant believed when he was seeking advice and whether his belief about the confidentiality of the conversation was reasonable. Thus Ms. Ducharme's understanding of the conversation and of why appellant had called her is relevant only to whether appellant reasonably believed he was consulting her as an attorney, with the protections that such a relationship provides.

[^chap5-1]: (n.4 in opinion) During the evidentiary hearing, defense counsel attempted to impeach Ms. Ducharme with her grand jury testimony. Before the grand jury, Ms. Ducharme initially testified that she gave appellant advice "as a lawyer," but then stated a few moments later that appellant had called her "as his girlfriend." The trial court presumably considered this discrepancy but nevertheless found Ms. Ducharme credible.

Guided by these principles, we agree with the trial court that appellant failed to make the clear showing necessary to establish that his conversation with Ms. Ducharme was within the protection of the attorney-client privilege. We note that the trial court found appellant's testimony incredible, in part, because he appeared to have tailored his testimony to fit the legal standard for the privilege, which counsel and the court had discussed in front of him during the hearing. The court said to defense counsel:

> It's the court's observation that appellant is very bright. And I was especially fond of his answer to counsel's last question about whether he heard me. Then counsel and I had this legal discussion, at which time your client then answered the question, he didn't understand the concept. It's as if we helped him answer the question, the two of us.

In addition, the court ruled that the questions appellant asked Ms. Ducharme were not "legal" questions. The court noted that appellant knew his rights when he refused to provide blood and hair samples to the police. According to Ms. Ducharme, whose testimony the court expressly credited, appellant did not inquire about his right not to give samples without a warrant, but instead asked "scientific" questions about whether or not his fingerprints might remain on a glass or whether his semen and hair might be discovered in the bathroom.

While such concerns about "bad facts" might fall within the privilege if they were expressed in a communication within a clearly established attorney-client relationship, we conclude, like the trial court, that appellant failed to establish that, as a matter of fact, such a relationship existed between him and Ms. Ducharme. We see no reason to upset the court's conclusion, which rested largely on its determination that Ms. Ducharme was credible and that appellant was not. We find no error in that determination.

#### @PeopleBelge_NYCountyCourtOnandagaCounty1975

In the summer of 1973 Robert F. Garrow, Jr., stood charged in Hamilton County with the crime of murder. The defendant was assigned two attorneys, Frank H. Armani and Francis R. Belge. A defense of insanity had been interposed by counsel for Mr. Garrow. During the course of the discussions between Garrow and his two counsel, three other murders were admitted by Garrow, one being in Onondaga County. On or about September of 1973 Mr. Belge conducted his own investigation based upon what his client had told him and with the assistance of a friend the location of the body of Alicia Hauck was found in Oakwood Cemetery in Syracuse. Mr. Belge personally inspected the body and was satisfied, presumably, that this was the Alicia Hauck that his client had told him that he murdered.

This discovery was not disclosed to the authorities, but became public during the trial of Mr. Garrow in June of 1974, when to affirmatively establish the defense of insanity, these three other murders were brought before the jury by the defense in the Hamilton County trial. Public indignation reached the fever pitch, statements were made by the District Attorney of Onondaga County relative to the situation and he caused the Grand Jury of Onondaga County, then sitting, to conduct a thorough investigation. As a result of this investigation Frank Armani was no-billed by the Grand Jury but Indictment No. 75-55 was returned as against Francis R. Belge, Esq., accusing him of having violated subdivision 1 of section 4200 of the Public Health Law, which, in essence, requires that a decent burial be accorded the dead, and section 4143 of the Public Health Law, which, in essence, requires anyone knowing of the death of a person without medical attendance, to report the same to the proper authorities. Defense counsel moves for a dismissal of the indictment on the grounds that a confidential, privileged communication existed between him and Mr. Garrow, which should excuse the attorney from making full disclosure to the authorities.

The National Association of Criminal Defense Lawyers, as amicus curiae, succinctly state the issue in the following language: If this indictment stands, "The attorney-client privilege will be effectively destroyed. No defendant will be able to freely discuss the facts of his case with his attorney. No attorney will be able to listen to those facts without being faced with the Hobson's choice of violating the law or violating his professional code of Ethics."

Initially in England the practice of law was not recognized as a profession, and certainly some people are skeptics today. However, the practice of learned and capable men appearing before the court on behalf of a friend or an acquaintance became more and more demanding. Consequently, the King granted a privilege to certain of these men to engage in such practice. There had to be rules governing their duties. These came to be known as "Canons". The King has, in this country, been substituted by a democracy, but the "Canons" are with us today, having been honed and refined over the years to meet the changes of time. Most are constantly being studied and revamped by the American Bar Association and by the bar associations of the various States. While they are, for the most part, general by definition, they can be brought to bear in a particular situation. Among those is the following, cited in *United States v Funk*: "Confidential communications between an attorney and his client are privileged from disclosure \* \* \* as a rule of necessity in the administration of justice."

In the most recent issue of the New York State Bar Journal (June, 1975) there is an article by Jack B. Weinstein, entitled "Educating Ethical Lawyers". In a subcaption to this article is the following language which is pertinent: "The most difficult ethical dilemmas result from the frequent conflicts between the obligation to one's client and those to the legal system and to society. It is in this area that legal education has its greatest responsibility, and can have its greatest effects." In the course of his article Mr. Weinstein states that there are three major types of pressure facing a practicing lawyer. He uses the following language to describe these: "First, there are those that originate in the attorney's search for his own wellbeing. Second, pressures arise from the attorney's obligation to his client. Third, the lawyer has certain obligations to the courts, the legal system, and society in general."

Our system of criminal justice is an adversary system and the interests of the State are not absolute, or even paramount. "The dignity of the individual is respected to the point that even when the citizen is known by the state to have committed a heinous offense, the individual is nevertheless accorded such rights as counsel, trial by jury, due process, and the privilege against self incrimination."

A trial is in part a search for truth, but it is only partly a search for truth. The mantle of innocence is flung over the defendant to such an extent that he is safeguarded by rules of evidence which frequently keep out absolute truth, much to the chagrin of juries. Nevertheless, this has been a part of our system since our laws were taken from the laws of England and over these many years has been found to best protect a balance between the rights of the individual and the rights of society.

The concept of the right to counsel has again been with us for a long time, but since the decision of *Gideon v Wainwright*, it has been extended more and more so that at the present time a defendant is entitled to have counsel at a parole hearing or a probation violation hearing.

The effectiveness of counsel is only as great as the confidentiality of its client-attorney relationship. If the lawyer cannot get all the facts about the case, he can only give his client half of a defense. This, of necessity, involves the client telling his attorney everything remotely connected with the crime.

Apparently, in the instant case, after analyzing all the evidence, and after hearing of the bizarre episodes in the life of their client, they decided that the only possibility of salvation was in a defense of insanity. For the client to disclose not only everything about this particular crime but also everything about other crimes which might have a bearing upon his defense, requires the strictest confidence in, and on the part of, the attorney.

When the facts of the other homicides became public, as a result of the defendant's testimony to substantiate his claim of insanity, "Members of the public were shocked at the apparent callousness of these lawyers, whose conduct was seen as typifying the unhealthy lack of concern of most lawyers with the public interest and with simple decency." A hue and cry went up from the press and other news media suggesting that the attorneys should be found guilty of such crimes as obstruction of justice or becoming an accomplice after the fact. From a layman's standpoint, this certainly was a logical conclusion. However, the Constitution of the United States of America attempts to preserve the dignity of the individual and to do that guarantees him the services of an attorney who will bring to the Bar and to the Bench every conceivable protection from the inroads of the State against such rights as are vested in the Constitution for one accused of crime. Among those substantial constitutional rights is that a defendant does not have to incriminate himself. His attorneys were bound to uphold that concept and maintain what has been called a sacred trust of confidentiality.

The following language from the brief of the amicus curiae further points up the statements just made: "The client's Fifth Amendment rights cannot be violated by his attorney. There is no viable distinction between the personal papers and criminal evidence in the hands or mind of the client. Because the discovery of the body of Alicia Hauck would have presented 'a significant link in a chain of evidence tending to establish his guilt', Garrow was constitutionally exempt from any statutory requirement to disclose the location of the body. And Attorney Belge, as Garrow's attorney, was not only equally exempt, but under a positive stricture precluding such disclosure. Garrow, although constitutionally privileged against a requirement of compulsory disclosure, was free to make such a revelation if he chose to do so. Attorney Belge was affirmatively required to withhold disclosure. The criminal defendant's self-incrimination rights become completely nugatory if compulsory disclosure can be exacted through his attorney."

In the recent and landmark case of *United States v Nixon* the court stated: "the constitutional need for production of relevant evidence in a criminal proceeding is specific and neutral to the fair adjudication of a particular criminal case in the administration of justice. Without access to specific facts a criminal prosecution may be totally frustrated." In the case at bar we must weigh the importance of the general privilege of confidentiality in the performance of the defendant's duties as an attorney, against the inroads of such a privilege on the fair administration of criminal justice as well as the heart tearing that went on in the victim's family by reason of their uncertainty as to the whereabouts of Alicia Hauck. In this type situation the court must balance the rights of the individual against the rights of society as a whole. There is no question but Attorney Belge's failure to bring to the attention of the authorities the whereabouts of Alicia Hauck when he first verified it, prevented bringing Garrow to the immediate bar of justice for this particular murder. This was in a sense, obstruction of justice. This duty, I am sure, loomed large in the mind of Attorney Belge. However, against this was the Fifth Amendment right of his client, Garrow, not to incriminate himself. If the Grand Jury had returned an indictment charging Mr. Belge with obstruction of justice under a proper statute, the work of this court would have been much more difficult than it is.

There must always be a conflict between the obstruction of the administration of criminal justice and the preservation of the right against self incrimination which permeates the mind of the attorney as the alter ego of his client. But that is not the situation before this court. We have the Fifth Amendment right, derived from the Constitution, on the one hand, as against the trivia of a pseudo-criminal statute on the other, which has seldom been brought into play. Clearly the latter is completely out of focus when placed alongside the client-attorney privilege. An examination of the Grand Jury testimony sheds little light on their reasoning. The testimony of Mr. Armani added nothing new to the facts as already presented to the Grand Jury. He and Mr. Belge were cocounsel. Both were answerable to the Canons of professional ethics. The Grand Jury chose to indict one and not the other. It appears as if that body were grasping at straws.

It is the decision of this court that Francis R. Belge conducted himself as an officer of the court with all the zeal at his command to protect the constitutional rights of his client. Both on the grounds of a privileged communication and in the interests of justice the indictment is dismissed.

#### @CorpDoe_EDVirginia1992

Few problems are as vexing as determining what evidence justifies a lawyer's disclosure of a client's confidential information and documents, which the lawyer believes reflect an ongoing or future crime or fraud. This case presents precisely this problem. Plaintiff, X Corp. brings this suit, in part, to prevent defendant, John Doe, X Corp.'s former in-house counsel, from disclosing X Corp.'s confidential information and documents retained by Doe following his discharge from X Corp. X Corp. also seeks return of the documents. In support of the relief sought, X Corp. cites the attorney-client privilege, the parties' confidentiality agreement, and the lawyer's general duty to preserve a client's confidences. For his part, Doe claims that the documents in issue disclose ongoing civil and criminal frauds perpetrated by X Corp. against the federal government. As such, according to Doe, the documents fall within the public policy crime-fraud exception to the attorney-client privilege and to any general or contractual duty of confidentiality.

The matter is before the Court on X Corp.'s motion for a preliminary injunction. For the reasons stated here, the motion is granted in part and denied in part.

[Facts]{.casesection}

X Corp. hired Doe in March 1989 as a member of its in-house legal staff based in Northern California. Formerly an Associate Deputy Attorney General of the United States and Chief of Staff to the Attorney General, Doe was a member of the bar of the state of Pennsylvania. When he was hired, Doe executed an "Employment, Invention and Confidential Information Agreement", in which he expressly agreed (i) to return to X Corp. all records obtained during, or in connection with, his employment and (ii) to preserve X Corp.'s confidential information. Thereafter, in the course of his employment, Doe regularly received confidential information from X Corp. management and its employees in order to provide legal opinions and advice. During approximately two years with X Corp., Doe apparently excelled; his professional performance was regarded as excellent. Eventually he was promoted to Group Counsel with primary responsibility worldwide for X Corp.'s compliance with numerous government regulations and antitrust laws.

In November 1990, Doe was transferred from X Corp.'s California office to Virginia as X Corp.'s only United States-based lawyer outside California. The parties sharply dispute the reason for the transfer. In X Corp.'s view, the transfer occurred because Doe failed the California bar examination. Doe, on the other hand, asserts that he initiated the transfer to escape California's high cost of living and because he and his wife wanted to live closer to their relatives in Virginia. Doe also contends that X Corp. negotiated with him to retain his services because he was "an important contributor and asset" and because X Corp. wanted to locate a regulatory and antitrust attorney near Washington, D.C.

X Corp. terminated Doe's employment effective February 28, 1992, providing him with thirty-one weeks severance pay. The reason for Doe's discharge is as hotly disputed as the reason for the transfer. X Corp. claims Doe was laid-off as part of a company-wide reduction in force involving over 700 employees. Doe counters, however, that he was unlawfully fired in retaliation for actions X Corp. believed he was taking in furtherance of a possible qui tam suit. On leaving X Corp.'s employ, Doe took with him copies of certain documents and files, leaving the originals with X Corp. Doe claims these documents reveal that X Corp. is defrauding the federal government, in violation of the False Claims Act. The documents submitted in camera are plainly relevant to these allegations. But without explanatory testimony or evidence, their significance in terms of establishing an ongoing fraudulent scheme is not entirely clear.

By letter dated February 28, 1992, Doe, through counsel, asserted a state law wrongful termination claim against X Corp., provided X Corp. with a draft complaint, and offered to discuss the matter prior to filing the complaint in this Court. The draft complaint contained specific references to, as well as excerpts from, X Corp.'s allegedly confidential documents. Thereafter, on March 5, 1992, X Corp. filed this lawsuit on the public record of this Court, but at that time, neither served Doe nor informed him of the suit's existence. X Corp.'s complaint asserts five causes of action: (i) breach of fiduciary duty by allegedly revealing confidences to his own attorney; (ii) breach of the Confidentiality Agreement; (iii) recovery of the allegedly misappropriated documents and records; (iv) injunctive relief to prevent disclosure of alleged confidential information in his personal claim against X Corp. or for any purpose; and (v) a declaratory judgment that Doe may not disclose the allegedly confidential information. X Corp. claims that filing this action was necessary to prevent disclosure of X Corp.'s confidential information in the event Doe filed his draft complaint on the public record. That circumstance never materialized, as Doe ultimately consented to delay filing his wrongful termination action and then to do so under temporary seal, which he did on April 7, 1992. One week later, X Corp. notified Doe of the existence of this action.

On April 20, 1992, X Corp. moved this Court for a preliminary injunction (i) to maintain Doe's wrongful termination lawsuit, and all pleadings and papers filed therein, under seal until its conclusion; (ii) to prohibit Doe and his lawyer from making any disclosures of X Corp.'s allegedly privileged and confidential information; and (iii) to compel Doe to return all allegedly misappropriated documents. Doe, by counsel, agreed to refrain from further disclosures of X Corp.'s claimed confidential information until the Court's ruling. On May 4, 1992, Doe filed his counterclaim alleging retaliatory discharge.

[Analysis]{.casesection}

Without doubt, this litigation presents "grave or serious questions," questions involving difficult and troubling ethical issues arising in the context of attorney-client confidentiality. Few questions are graver or more serious in the practice of law than determining what evidence of crime or fraud justifies a lawyer's disclosure of his client's confidential information. Moreover, allegations of attorney misconduct, or even potential misconduct, engender significant and serious questions of professional conduct critical to the client, to the accused attorney, and to the bar as a whole. Such allegations, regardless of their veracity, erode the already fragile public confidence in the legal profession and in the administration of justice. And it is undeniable that our legal system cannot function effectively unless the public has confidence in the integrity and competence of the system and its participants. Thus, it is paramount that lawyers understand and abide by settled and accepted norms of professional conduct. But even settled and accepted norms frequently provide inadequate or ambiguous guidance in the face of specific factual circumstances. So it is here.

This litigation focuses on two professional standards of attorney confidentiality---(i) the evidentiary attorney-client privilege and (ii) the broader ethical duty of confidentiality---and their application to the specific facts presented. Understanding the distinction between these two standards is essential to the matter at bar. For that reason, it is worth describing them here in some detail.

The first of these standards, the evidentiary attorney-client privilege, is quite familiar, and the principles associated with it are well-settled. This evidentiary privilege applies to disclosures of certain types of confidences communicated between client and attorney during the course of the attorney's representation of the client. To prevent such disclosures, the client, through counsel or otherwise, may invoke the privilege. The purpose of the attorney-client privilege

> is to encourage full and frank communication between attorneys and their clients and thereby promote broader public interests in the observance of law and administration of justice. The privilege recognizes that sound legal advice or advocacy serves public ends and that such advice or advocacy depends upon the lawyer's being fully informed by the client.

*Upjohn Co. v. United States*, 449 U.S. 383, 389 (1981). Nevertheless, because it "impedes the full and free discovery of the truth," and is "in derogation of the public's 'right to every man's evidence,'" the attorney-client privilege is not "favored" by federal courts. Accordingly, the privilege is narrowly construed to apply only to those situations in which the party invoking the privilege consulted an attorney for the purpose of securing a legal opinion or services and in connection with that consultation communicated information intended to be kept confidential.

The privilege is determined on a case-by-case basis. It well-settled that the privilege protects corporate as well as individual clients, and that it attaches to in-house as well as outside counsel. The party seeking to invoke the privilege bears the burden of establishing that the attorney-client relationship existed, that the particular communications at issue are privileged, and that the privilege has not been waived. The Fourth Circuit has adopted the "classic test" for application of the attorney-client privilege announced in *United Shoe Machinery Corp.*:

> The privilege applies only if (1\) the asserted holder of the privilege is or sought to become a client; (2\) the person to whom the communication was made (a) is a member of the bar of a court, or his subordinate and (b) in connection with this communication is acting as a lawyer; (3\) the communication relates to a fact of which the attorney was informed (a) by his client (b) without the presence of strangers (c) for the purpose of securing primarily either (i) an opinion on law or (ii) legal services or (iii) assistance in some legal proceeding, and not (d) for the purpose of committing a crime or tort; and (4\) the privilege as been (a) claimed and (b) not waived by the client.

Under the exception to the privilege commonly known as the "crime-fraud exception," communications made for an unlawful purpose or to further an illegal scheme are not privileged. For example, the attorney-client privilege is extinguished when an attorney "is consulted not with respect to past wrongdoings but rather to further a continuing or contemplated criminal or fraudulent scheme." But the privilege may also be overcome even in circumstances where the attorney is not consulted for the purpose of furthering a crime or fraudulent scheme. Thus, the privilege cannot be used as a shield to preclude disclosure of information concerning an ongoing or future crime or fraud collaterally learned by a lawyer during the course of his representation.

To overcome an established privilege using the crime-fraud exception, the party opposing the privilege need make only a prima facie showing that the communications either (i) were made for an unlawful purpose or to further an illegal scheme or (ii) reflect an ongoing or future unlawful or illegal scheme or activity. The purported crime or fraud need not be proved. Requiring only a prima facie showing may lead to the disclosure of confidential communications that do not reflect a genuine crime or fraud. Presumably, this would occur infrequently. The alternative---requiring actual proof of the crime or fraud in lieu of the prima facie showing---imposes an impractical and unduly burdensome standard that tips the balance too far in favor of confidentiality and against the "full and free discovery of the truth."

The evidentiary attorney-client privilege, while more familiar, is not the lawyer's only duty of confidentiality to a client. Too often unrecognized is the broader ethical duty of an attorney to preserve a client's confidences and secrets that may fall outside the attorney-client privilege. The leading case discussing this ethical duty is the Fifth Circuit's decision in Brennan's Inc. v. Brennan's Restaurants, Inc., 590 F.2d 168 (5th Cir.1979). There, defendants took the position that the attorney-client privilege barred an attorney from further representation of a former joint client. The Fifth Circuit disagreed, noting that "the fundamental flaw in defendants' position is a confusion of the attorney-client evidentiary privilege with the ethical duty to preserve a client's confidences." The panel held that although a former joint client could not assert the attorney-client privilege as to matters encompassed by the former joint representation because confidences cannot arise between joint clients, a broader ethical duty protects joint clients. In this regard, the court stated:

> Information acquired \[from a client\] is sheltered from use by the attorney against his client by virtue of the existence of the attorney-client relationship. This is true without regard to whether someone else may be privy to it. The obligation of an attorney not to misuse information acquired in the course of representation serves to vindicate the trust and reliance that client's place in their attorneys. A client would feel wronged if an opponent prevailed against him with the aid of an attorney who formerly represented the client in the same matter this would undermine public confidence in the legal system as a means for adjudicating disputes.

As the Fifth Circuit sensibly recognized in Brennan's and Doe, attorney confidentiality is essential to sustaining public confidence in the legal profession and the legal system. Clients therefore have a right to enforce that confidentiality, absent specific circumstances abrogating 1308\*1308 that right. Of course, an attorney's duty to his client is limited by his duty to comply with the law and the standards of professional conduct.

Consistent with most jurisdictions, Virginia recognizes a broad duty of confidentiality in Canon 4 of the Virginia Code of Professional Responsibility, which states: "A Lawyer Should Preserve the Confidences and Secrets of a Client." The corresponding Disciplinary Rules provide in relevant part:

> DR4-101. Preservation of Confidences and Secrets of a Client.---(A) "Confidence" refers to information protected by the attorney-client privilege under applicable law, and "secret" refers to other information gained in the professional relationship that the client has requested be held inviolate or the disclosure of which would be embarrassing or would be likely to be detrimental to the client.
>
> \(B\) Except as provided by DR 4-101(C) and (D), a lawyer shall not knowingly:
>
> > \(1\) Reveal a confidence or secret of his client.
> >
> > \(2\) Use a confidence or secret of his client to the disadvantage of the client.
> >
> > \(3\) Use a confidence or secret of his client for the advantage of himself or a third person, unless the client consents after full disclosure.

Thus, mandatory Disciplinary Rule 4-101 defines two categories of protected information: (i) a narrow category of "confidences," comprising information protected by the attorney-client privilege, and (ii) a broader category of "secrets," encompassing "other information gained in the professional relationship that the client has requested be held inviolate or the disclosure of which would be embarrassing or would be likely to be detrimental to the client." In distinguishing between these two categories, Virginia has manifest its intention to protect from disclosure a range of communications broader than that protected by the attorney-client privilege. Confidentiality of both categories of information must be maintained. Yet the duty of confidentiality imposed by the Virginia Code of Professional Responsibility is not absolute. A lawyer may reveal confidences and secrets in specific circumstances. Relevant here is a provision, similar in purpose and effect to the crime-fraud exception to the attorney-client privilege, permitting an attorney to reveal "information which clearly establishes that his client has, in the course of the representation, perpetuated upon a third party a fraud related to the subject matter of the representation." Information "clearly establishes" the perpetration of a fraud if it is information that a reasonable attorney in the same circumstances would find convincing evidence of the alleged fraudulent activities.

Yet despite its similar purpose, DR4-101(C)(3)'s "clearly establishes" standard imposes a heavier burden on the party seeking disclosure than the prima facie standard of the crime-fraud exception to the attorney-client privilege. In other words, matters subject to the attorney-client privilege seem to be less stringently protected from disclosure than matters subject to the ethical privilege. This, at first blush, seems puzzling, indeed paradoxical, for one would think that the attorney-client privilege deserves the greater protection. On reflection, however, the two different standards make sense given that they apply in different contexts. Succinctly put, the evidentiary attorney-client privilege arises only where disclosures are sought to be compelled in some litigation context, whereas the broader ethical duty arises in the context of voluntary or uncompelled disclosures, typically outside a litigation context. More particularly, the attorney-client privilege is an evidentiary privilege applicable where someone seeks to compel an attorney or his client to reveal communications between lawyer and client made for the purpose of securing a legal opinion or legal services and intended to be kept confidential. Thus, the privilege arises in the context of litigation and is therefore subject to discipline of the adversary process and the safeguard of judicial scrutiny, if the affected client invokes the privilege and the opposing party seeks to overcome it. Significantly, however, the evidentiary attorney-client privilege does not control where disclosures occur, or potential disclosures are contemplated, in circumstances involving uncompelled disclosure and no judicial scrutiny. In such circumstances, the ethical duty---with its appropriately higher standard of protection against unwarranted disclosure of suspected fraudulent activities---governs. The voluntary nature of the actual or potential disclosures and the absence of judicial scrutiny justify the higher "clearly establishes" standard for disclosure of purported evidence of ongoing or future fraud. In sum, the prima facie standard under the crime-fraud exception to the attorney-client privilege is a standard applied in the litigation context by judges, not lawyers, for the purpose of deciding whether to compel the disclosure of putatively privileged material. By contrast, the more stringent "clearly establishes" standard for disclosure of confidential information is one that is applied in the first instance by lawyers, not judges, as they struggle with the decision whether voluntarily to disclose certain confidential information they believe reflects an ongoing or future fraud. Judges apply the "clearly establishes" standard in the second instance only to review post hoc whether a voluntary disclosure was ethically appropriate or, as here, to decide whether to enjoin a potential voluntary disclosure.

In light of these principles, any reliance here on the evidentiary attorney-client privilege and its crime-fraud exception is misplaced. This is not a case involving compelled disclosures. No one seeks to compel Doe to disclose privileged material against X Corp.'s invocation of the attorney-client privilege. Rather, this is a case of voluntary disclosure; Doe voluntarily has disclosed or wishes to disclose a broad range of information X Corp. believes should be treated confidentially. Thus, applicable here is the broader ethical duty of confidentiality and the "clearly establishes" standard for disclosure of evidence of fraud.

Given this, in proving its claim that Doe is obligated to maintain its confidences pursuant to the ethical duty, X Corp. bears the initial burden of establishing that the duty exists and that the disputed communications are subject to it. To do so, X Corp. must show, *inter alia*, that the communications sought to be protected are "confidences" or "secrets" within the meaning of Virginia Code of Professional Responsibility DR4-101(A). If X Corp. carries this burden and establishes that Doe is ethically bound not to disclose this material, the burden then shifts to Doe to show that the material and information he voluntarily disclosed or seeks to disclose "clearly establish\[\]" that during the course of Doe's representation, X Corp. perpetrated a fraud related to the subject matter of the representation upon a third party, namely, the federal government. To accomplish this, Doe must demonstrate more than mere suspicion of fraud; he must show that a reasonable attorney in his position would find the communications at issue to be convincing evidence of the perpetration of a fraud on the government during the course of his representation related to the subject matter of that representation. But the fraud itself need not be conclusively proved. Thus, the issue for trial is not whether X Corp. was in fact perpetrating a fraud on the government. Rather, the primary issues for trial are (i) what Doe knew or should have known at the time of the intended disclosures (or the time X Corp. sought to enjoin disclosures) and (ii) whether a reasonable attorney with that knowledge would find that it clearly establishes an ongoing or planned fraud, that is, that it constitutes convincing evidence of an ongoing or planned fraud. If Doe satisfies the "clearly establishes" standard, disclosure is permissible (but not required), even if X Corp. ultimately proves that no fraud existed.

There may be circumstances where ongoing or contemplated frauds actually exist, but disclosure is impermissible because the evidence relied on by the attorney falls short of clearly establishing the fraud. This result might permit the fraud to continue. But neither mere suspicion of fraud, nor the mere risk of undiscovered fraud, justify abrogating the duty of attorney confidentiality. A windfall to a wrongdoer may be the price exacted for the benefits conferred on the public and the legal system by vigilantly-maintained attorney confidentiality.

#### @MatterGrandJuryInvestigation_Massachusetts2009

This case requires us to decide whether the attorney-client privilege applies where a client leaves messages on his counsel's telephone answering machine threatening to harm others and the attorney discloses those communications in order to protect those threatened.

The salient facts are not in dispute. Attorney John Doe was representing Michael Moe, a father, in a care and protection proceeding in the Juvenile Court. On November 8, 2007, two days after an adverse ruling by a Juvenile Court judge, Moe left six messages on Attorney Doe's answering machine between 1:08 A.M. and 1:24 A.M. Moe indicated that he knew where the judge lived and that she had two children. In the fourth message, a voice that Attorney Doe recognized as Moe's wife stated that she and Moe were going to "raise some hell." In the fifth message, Moe stated that "some people need to be exterminated with prejudice." Attorney Doe subsequently erased the messages from the answering machine.

During the following week, Attorney Doe observed that Moe had become "more and more angry," and on November 13, 2007, he filed a motion to withdraw as Moe's counsel, which was subsequently allowed. Concerned for the safety of the judge and her family, he disclosed the substance of the messages to the judge.

On November 21, 2007, Attorney Doe was interviewed by a State trooper regarding the substance of the messages, but declined to sign a written statement.

A District Court complaint alleging threats to commit a crime and intimidation of a witness subsequently issued against Moe. The Commonwealth then initiated grand jury proceedings and filed a motion to summons Attorney Doe before the grand jury. That motion was allowed. On December 21, 2007, Attorney Doe, citing the attorney-client privilege, moved to quash the summons. A judge in the Superior Court denied Attorney Doe's motion, reasoning that Attorney Doe and Moe had not carried their burden of demonstrating that the attorney-client privilege applied "because they failed to show that the messages were left in an attempt to obtain legal services." Attorney Doe filed a motion to reconsider, requesting, *inter alia*, an evidentiary hearing. The motion was denied. The Commonwealth and Attorney Doe submitted a joint request to report the decision to the Appeals Court. The Superior Court judge reported the case, and we transferred the case here on our own motion.

Neither party disputes that Attorney Doe could, consistent with rule 1.6, disclose the substance of Moe's messages. Rule 1.6 provides, in pertinent part:

> \(a\) A lawyer shall not reveal confidential information relating to representation of a client unless the client consents after consultation, except for disclosures that are impliedly authorized in order to carry out the representation, and except as stated in paragraph (b). (b) A lawyer may reveal, and to the extent required by Rule 3.3, Rule 4.1(b), or Rule 8.3 must reveal, such information: (1\) to prevent the commission of a criminal or fraudulent act that the lawyer reasonably believes is likely to result in death or substantial bodily harm.

While nothing in rule 1.6(b) required Attorney Doe to disclose Moe's communications to the judge or police, he had discretion to do so. However, the ethical permissibility of Attorney Doe's disclosure does not resolve the distinct issue presented here: whether Attorney Doe can be compelled to testify before the grand jury.

Evidentiary privileges "are exceptions to the general duty imposed on all people to testify." We accept such privileges "only to the very limited extent that permitting a refusal to testify or excluding relevant evidence has a public good transcending the normally predominant principle of utilizing all rational means for ascertaining truth." The attorney-client privilege "is founded upon the necessity, in the interest and administration of justice, of the aid of persons having knowledge of the law and skilled in its practice, which assistance can only be safely and readily availed of when free from the consequences or the apprehension of disclosure." A party asserting the privilege must show that (1\) the communications were received from the client in furtherance of the rendition of legal services; (2\) the communications were made in confidence; and (3\) the privilege has not been waived.

The Commonwealth contends that the attorney-client privilege does not apply because Moe's communications were not made "for the purpose of facilitating the rendition of legal services." In making this argument, the Commonwealth implicitly asks us to reconsider a portion of our discussion in the *Purcell* case.

In *Purcell*, the client was discharged as a maintenance man at the apartment building in which his apartment was located and had received an order to vacate his apartment. During consultation with an attorney, the client stated an intent to burn the apartment building. The attorney disclosed these communications to police and criminal charges were brought against the client. When the prosecutor subpoenaed the attorney to testify at trial, the attorney filed a motion to quash, which was denied. The central issue in that case was whether the crime-fraud exception to the attorney-client privilege applied. We concluded that the communications would not fall within the crime-fraud exception unless the district attorney could establish facts by a preponderance of the evidence showing that the client's communication sought assistance in or furtherance of future criminal conduct.

Recognizing that whether the attorney-client privilege applied at all was open on remand, we also considered whether a communication of an intention to commit a crime, if not within the crime-fraud exception, could be considered a communication for the purposes of facilitating the rendition of legal services. We held that a "statement of an intention to commit a crime made in the course of seeking legal advice is protected by the privilege, unless the crime-fraud exception applies." We reasoned that a gap between the crime-fraud exception and the applicability of the privilege "would make no sense," because the attorney-client privilege was premised on the benefits of unimpeded communication between attorney and client, and noted that "an informed lawyer may be able to dissuade the client from improper future conduct and, if not, under the ethical rules may elect in the public interest to make a limited disclosure of the client's threatened conduct."

The limited disclosure adverted to in the *Purcell* case occurred here. Concerned for the safety of the judge, her family, and a social worker, Attorney Doe disclosed Moe's communications to the judge and law enforcement authorities to protect them from harm.

We discern no reason to depart from the *Purcell* decision, and hold that Moe's communications were made in furtherance of the rendition of legal services and thus protected by the attorney-client privilege. The Commonwealth's argument to the contrary essentially raises an issue of germaneness. Scholars, commentators, and courts have formulated a number of tests for determining the germaneness of a client's communication. However, none of these formulations appears to give clients breathing room to express frustration and dissatisfaction with the legal system and its participants. The expression of such sentiments is a not uncommon incident of the attorney-client relationship, particularly in an adversarial context, and may serve as a springboard for further discussion regarding a client's legal options. If a lawyer suspects that the client intends to act on an expressed intent to commit a crime, the lawyer may attempt to dissuade the client from such action, and failing that, may make a limited disclosure to protect the likely targets. Requiring the privilege to yield for purposes of a criminal prosecution not only would hamper attorney-client discourse, but also would discourage lawyers from exercising their discretion to make such disclosures, as occurred here, and thereby frustrate the beneficial public purpose underpinning the discretionary disclosure provision of rule 1.6. Furthermore, any test to ascertain the germaneness of an ostensibly threatening communication on a case-by-case basis would make the privilege's applicability uncertain, rendering the privilege "little better than no privilege." Warning clients that communications deemed irrelevant to the matter for which they have retained counsel will not be protected not only may discourage clients from disclosing germane information, but also may disincline clients to share their intentions to engage in criminal behavior. In the latter circumstance, a lawyer's ability to aid in the administration of justice by dissuading a client from engaging in such behavior is impaired. The lawyer also may never receive the very information necessary for him or her to determine whether to make a limited disclosure to prevent the harm contemplated by the client.

In sum, we reaffirm that a client's communications to his lawyer threatening harm are privileged unless the crime-fraud exception applies. Because the Commonwealth does not assert that Moe's communications come within the crime-fraud exception, they were privileged. The order denying Attorney Doe's motion to quash is hereby vacated and the case is remanded to the Superior Court for further proceedings consistent with this opinion.

## Attorney Work Product

#### @Rest2dLawGoverningLawyers

::: legalcode
##### § 87. Lawyer Work-Product Immunity

-   \(1\) Work product consists of tangible material or its intangible equivalent in unwritten or oral form, other than underlying facts, prepared by a lawyer for litigation then in progress or in reasonable anticipation of future litigation.
-   \(2\) Opinion work product consists of the opinions or mental impressions of a lawyer; all other work product is ordinary work product.
-   \(3\) Except for material which by applicable law is not so protected, work product is immune from discovery or other compelled disclosure to the extent stated in §§ 88 (ordinary work product) and 89 (opinion work product) when the immunity is invoked as described in § 90.

##### § 88. Ordinary Work Product

When work product protection is invoked as described in § 90, ordinary work product (§ 87(2)) is immune from discovery or other compelled disclosure unless either an exception recognized in §§ 91-93 applies or the inquiring party:

-   \(1\) has a substantial need for the material in order to prepare for trial; and
-   \(2\) is unable without undue hardship to obtain the substantial equivalent of the material by other means.

##### § 89. Opinion Work Product

When work product protection is invoked as described in § 90, opinion work product (§ 87(2)) is immune from discovery or other compelled disclosure unless either the immunity is waived or an exception applies (§§ 91-93) or extraordinary circumstances justify disclosure.

##### § 90. Invoking the Lawyer Work-Product Immunity and Its Exceptions

-   \(1\) Work-product immunity may be invoked by or for a person on whose behalf the work product was prepared.
-   \(2\) The person invoking work-product immunity must object and, if the objection is contested, demonstrate each element of the immunity.
-   \(3\) Once a claim of work product has been adequately supported, a person entitled to invoke a waiver or exception must assert it and, if the assertion is contested, demonstrate each element of the waiver or exception.
:::

##### @FRCP26

::: legalcode
##### Duty to Disclose; General Provisions Governing Discovery

-   \(b\) Discovery Scope and Limits.
    -   \(3\) Trial Preparation: Materials.
        -   \(A\) Documents and Tangible Things. Ordinarily, a party may not discover documents and tangible things that are prepared in anticipation of litigation or for trial by or for another party or its representative (including the other party's attorney, consultant, surety, indemnitor, insurer, or agent). But, subject to Rule 26(b)(4), those materials may be discovered if:
            -   \(i\) they are otherwise discoverable under Rule 26(b)(1); and
            -   \(ii\) the party shows that it has substantial need for the materials to prepare its case and cannot, without undue hardship, obtain their substantial equivalent by other means.
        -   \(B\) Protection Against Disclosure. If the court orders discovery of those materials, it must protect against disclosure of the mental impressions, conclusions, opinions, or legal theories of a party's attorney or other representative concerning the litigation.
        -   \(C\) Previous Statement. Any party or other person may, on request and without the required showing, obtain the person's own previous statement about the action or its subject matter. If the request is refused, the person may move for a court order, and Rule 37(a)(5) applies to the award of expenses. A previous statement is either:
            -   \(i\) a written statement that the person has signed or otherwise adopted or approved; or
            -   \(ii\) a contemporaneous stenographic, mechanical, electrical, or other recording—or a transcription of it—that recites substantially verbatim the person's oral statement.
:::

#### @USDeloitteLLP_DCCircuit2010

The United States appeals from a district court order denying its motion to compel Dow Chemical Company's independent auditor, Deloitte & Touche USA, LLP, to produce three documents in connection with ongoing tax litigation between Dow and the government. The district court ruled that all three documents were protected from discovery under the work-product doctrine. On appeal, the government contends that one of the documents is not work product because it was prepared by Deloitte during the audit process. In addition, while it concedes that the other two documents are work product, it argues that Dow waived work-product protection when it disclosed them to Deloitte. We vacate the district court's decision that the document prepared by Deloitte is work product and remand for in camera review to determine whether it is entirely work product. With respect to the other two documents, we affirm the district court's decision that Dow did not waive work-product protection when it disclosed them to Deloitte.

[I. Background]{.casesection}

This discovery dispute arises from ongoing tax litigation in the U.S. District Court for the Middle District of Louisiana. The litigation concerns the tax treatment of two partnerships owned by Dow Chemical Company and two of its wholly-owned subsidiaries. The first of these partnerships was Chemtech I; it was succeeded by Chemtech II. In 2005, Dow filed a civil suit challenging IRS adjustments to partnership returns filed by Chemtech I and Chemtech II. During discovery, the government subpoenaed documents from Dow's independent auditor, Deloitte & Touche USA, LLP. Since the subpoena sought production in Washington, D.C., it issued from the U.S. District Court for the District of Columbia. Deloitte produced a number of documents, but refused to produce three documents Dow identified as attorney work product. In response, the government filed a motion to compel production.

The three disputed documents are described in Dow's privilege log and in a declaration by William Curry, Dow's Director of Taxes. The first document is a 1993 draft memorandum prepared by Deloitte that summarizes a meeting between Dow employees, Dow's outside counsel, and Deloitte employees about the possibility of litigation over the Chemtech I partnership, and the necessity of accounting for such a possibility in an ongoing audit. This meeting took place after Dow informed Deloitte about the likelihood of litigation over the Chemtech I transaction. The second is a 1998 memorandum and flow chart prepared by two Dow employees---an accountant and an in-house attorney. The third is a 2005 tax opinion prepared by Dow's outside counsel. Curry's declaration explains that the second and third documents were disclosed to Deloitte so that it could "review the adequacy of Dow's contingency reserves for the Chemtech transactions." According to Curry, Deloitte "compelled Dow's production of these documents by informing the company that access to these documents was required in order to provide Dow with an unqualified audit opinion for its public financial statements." The privilege log describes the subject matter of these documents as "tax issues related to the Chemtech partnership" and states that each one is a "document prepared in anticipation of litigation." We will refer to the first document, which was prepared by Deloitte, as the "Deloitte Memorandum," and the second and third documents, which were created by Dow, as the "Dow Documents."

The district court denied the government's motion to compel without reviewing the disputed documents in camera. It concluded that the Deloitte Memorandum was work product because it was "prepared because of the prospect of litigation with the IRS over the tax treatment of Chemtech." The court further concluded that, although the document was created by Deloitte, it was nonetheless Dow's work product because "its contents record the thoughts of Dow's counsel regarding the prospect of litigation." In addition, the court rejected the government's contention that Dow had waived work-product protection for the three documents. The court acknowledged that disclosing work product to a third party can waive protection if that disclosure is "inconsistent with the maintenance of secrecy from the disclosing party's adversary," but concluded that Dow's disclosure to Deloitte was not inconsistent with maintaining secrecy because (1\) Deloitte was not a potential adversary and (2\) nothing suggested that it was unreasonable for Dow to expect Deloitte to maintain confidentiality. The government appeals this ruling, and Dow has intervened to assert work-product protection.

[II. Analysis]{.casesection}

The government contends that the Deloitte Memorandum is not attorney work product. Alternatively, it argues that even if the Deloitte Memorandum is work product, Dow waived work-product protection when it orally disclosed the information recorded therein to Deloitte. Turning to the Dow Documents, the government concedes they are attorney work product, but argues that Dow waived work-product protection when it gave them to Deloitte.

[A. The Work-Product Doctrine]{.casesubsection}

The Supreme Court established the work-product doctrine in *Hickman v. Taylor*, which held that an attorney's notes recording his interviews with witnesses to the litigation-prompting incident were protected from discovery. The Court recognized that to prepare for litigation, an attorney must "assemble information, sift what he considers to be the relevant from the irrelevant facts, prepare his legal theories and plan his strategy without undue and needless interference." This preparation "is reflected in interviews, statements, memoranda, correspondence, briefs, mental impressions, personal beliefs, and countless other tangible and intangible ways." The Court reasoned that giving opposing counsel access to such work product would cause significant problems:

> Much of what is now put down in writing would remain unwritten. An attorney's thoughts, heretofore inviolate, would not be his own. Inefficiency, unfairness and sharp practices would inevitably develop in the giving of legal advice and in the preparation of cases for trial. The effect on the legal profession would be demoralizing. And the interests of the clients and the cause of justice would be poorly served.

Consequently, the Court concluded that attorney work product is protected from discovery unless "the one who would invade that privacy" carries the burden of "establishing adequate reasons to justify production through a subpoena or court order."

The work-product doctrine announced in Hickman was subsequently partially codified in Federal Rule of Civil Procedure 26(b)(3), which states:

> \(A\) Documents and Tangible Things. Ordinarily, a party may not discover documents and tangible things that are prepared in anticipation of litigation or for trial by or for another party or its representative (including the other party's attorney, consultant, surety, indemnitor, insurer, or agent).

Rule 26(b)(3) allows a court to order disclosure when the requesting party can show a "substantial need" for the material and an inability to procure equivalent information "without undue hardship." When a court orders disclosure under this exception, however, it must still "protect against disclosure of the mental impressions, conclusions, opinions, or legal theories of a party's attorney or other representative concerning the litigation." This type of work product, which is often described as opinion work product, "is virtually undiscoverable."

[B. The Deloitte Memorandum]{.casesubsection}

The government makes two categorical arguments that the Deloitte Memorandum cannot be work product. First, it argues that the Deloitte Memorandum cannot be work product because it was created by Deloitte, not Dow or its representative. Second, it argues that the Deloitte Memorandum cannot be work product because it was generated as part of the routine audit process, not in anticipation of litigation. If either argument is correct, the Deloitte Memorandum cannot be work product, regardless of its contents. We reject both arguments, but nevertheless conclude that the district court lacked sufficient information to determine that the entire Deloitte Memorandum is work product.

[1]{.casesubsubsection}

The government first contends that Dow cannot claim work-product protection for the Deloitte Memorandum because it was prepared by Deloitte. Rule 26(b)(3) only protects "documents and tangible things that are prepared by or for another party or its representative." Given this language, the government argues that the Deloitte Memorandum is not work product because Deloitte is not Dow's representative. It relies principally on *United States v. Arthur Young & Co.*, in which the Supreme Court refused to recognize an accountant work-product privilege. In *Arthur Young*, the Court contrasted the role of an attorney with that of an accountant, explaining that an attorney is "a loyal representative whose duty it is to present the client's case in the most favorable possible light," whereas an independent certified public accountant has a "public responsibility" and "owes ultimate allegiance to the corporation's creditors and stockholders, as well as to the investing public." In the government's view, *Arthur Young* demonstrates that Deloitte cannot be Dow's representative, which in turn means that the Deloitte Memorandum cannot be work product under the plain language of Rule 26(b)(3). Dow counters that the "representative" for purposes of Rule 26(b)(3) is its counsel, whose thoughts and opinions are recorded in the document. In addition, it argues that the Deloitte Memorandum is work product because it contains the same type of opinion work product that is found in the Dow Documents, which the government concedes are work product.

Even if the government is correct in asserting that the Deloitte Memorandum falls outside the definition given by Rule 26(b)(3), this does not conclusively establish that it is not work product. The government mistakenly assumes that Rule 26(b)(3) provides an exhaustive definition of what constitutes work product. On the contrary, Rule 26(b)(3) only partially codifies the work-product doctrine announced in *Hickman*. Rule 26(b)(3) addresses only "documents and tangible things," but *Hickman*'s definition of work product extends to "intangible" things. Moreover, in *Hickman*, the Court explained that the attorney's "mental impressions" were protected from discovery, so that he could not be forced to "repeat or write out" that information in discovery. Thus *Hickman* provides work-product protection for intangible work product independent of Rule 26(b)(3).

The government focuses on Deloitte's role in creating the document and on its relationship to Dow. Under *Hickman*, however, the question is not who created the document or how they are related to the party asserting work-product protection, but whether the document contains work product---the thoughts and opinions of counsel developed in anticipation of litigation. The district court found that the memorandum records those thoughts, even though Deloitte and not Dow or its attorney committed them to paper. The work product privilege does not depend on whether the thoughts and opinions were communicated orally or in writing, but on whether they were prepared in anticipation of litigation. Thus Deloitte's preparation of the document does not exclude the possibility that it contains Dow's work product.

[2]{.casesubsubsection}

The government next contends that the Deloitte Memorandum cannot be work product because it was generated during an annual audit, not prepared in anticipation of litigation. The courts are not unanimous on the proper test for determining whether a document was prepared "in anticipation of litigation." Under the test adopted by most circuits, the question is whether the document was created "because of" the anticipated litigation. The Fifth Circuit, however, requires that anticipation of litigation be the "primary motivating purpose" behind the document's creation.

Like most circuits, we apply the "because of" test, asking "whether, in light of the nature of the document and the factual situation in the particular case, the document can fairly be said to have been prepared or obtained because of the prospect of litigation." In addition, while this standard addresses a "document," it applies equally to work product in other forms. Thus for the Deloitte Memorandum, the question is whether it records information prepared by Dow or its representatives because of the prospect of litigation.

In the government's view, the Deloitte Memorandum was prepared not "because of the prospect of litigation," but as part of the routine audit process. The government asserts that a document's function, not its content, determines whether it is work product. For this proposition the government relies on *Delaney, Migdail & Young, Chartered v. IRS*. In *Delaney*, a law firm sought to obtain under the Freedom of Information Act memoranda and supporting documents relating to the government's legal analysis of an Internal Revenue Service program concerning the use of statistical sampling in auditing large accounts. In that case it was the IRS that asserted work-product protection. The court held that the documents were work product because they "advised the agency of the types of legal challenges likely to be mounted against a proposed program, potential defenses available to the agency, and the likely outcome." In its reasoning, the court noted that a previous work-product decision had identified "the function of the documents as the critical issue." The government seizes on this language, arguing that the Deloitte Memorandum is not work product because its function was to facilitate Deloitte's audit, not to prepare Dow for litigation.

We think the government misreads *Delaney*. While *Delaney* used the term "function," it was not considering any distinction between function and content in determining whether a document constituted work product. On the contrary, the court evaluated the function of the IRS documents at issue by examining their contents. It contrasted the documents at issue in the *Coastal States* case, which were like "an agency manual, fleshing out the meaning of the statute it was authorized to enforce," with the documents at issue in *Delaney*, which were memoranda describing potential legal challenges, possible defenses, and likely outcomes. *Delaney* does not support the proposition that we should look solely to a document's function divorced from its contents in determining its status as work product.

In short, a document can contain protected work-product material even though it serves multiple purposes, so long as the protected material was prepared because of the prospect of litigation.

[3]{.casesubsubsection}

Rejecting the government's categorical arguments establishes only that the Deloitte Memorandum may be protected work product under the law; we must now determine whether it is. On examination of the record, we conclude that the district court did not have a sufficient evidentiary foundation for its holding that the memorandum was purely work product. According to the record, the document was created during Deloitte's preparation of an audit report which in Deloitte's view required consideration of potential litigation. The meeting generating the document included both Deloitte and Dow employees, as well as Dow's outside counsel. The document itself was prepared by a third party. While none of this negates the possibility of work-product privilege, it could make it likely that the document includes other information that is not work product. According to Dow's privilege log and the Curry declaration, the memorandum does contain thoughts and analyses by legal counsel, but this does not rule out or even render unlikely the possibility that it also includes other facts, other thoughts, other analyses by non-attorneys which may not be so intertwined with the legal analysis as to warrant protection under the work-product doctrine. We will therefore remand this question to the district court for the purpose of independently assessing whether the document was entirely work product, or whether a partial or redacted version of the document could have been disclosed. Accordingly, we vacate the district court's decision that the Deloitte Memorandum was work product and remand so that the district court can examine the document in camera to determine whether it is entirely work product.

[C. The Dow Documents]{.casesubsection}

Although the government concedes that the Dow Documents are work product, it contends that Dow waived work-product protection by disclosing them to Deloitte. To the best of our knowledge, no circuit has addressed whether disclosing work product to an independent auditor constitutes waiver. Among the district courts that have addressed this issue, most have found no waiver.

While voluntary disclosure waives the attorney-client privilege, it does not necessarily waive work-product protection. The attorney-client privilege and the work-product doctrine serve different purposes: the former protects the attorney-client relationship by safeguarding confidential communications, whereas the latter promotes the adversary process by insulating an attorney's litigation preparation from discovery. Voluntary disclosure waives the attorney-client privilege because it is inconsistent with the confidential attorney-client relationship. Voluntary disclosure does not necessarily waive work-product protection, however, because it does not necessarily undercut the adversary process. Nevertheless, disclosing work product to a third party can waive protection if "such disclosure, under the circumstances, is inconsistent with the maintenance of secrecy from the disclosing party's adversary." Under this standard, the voluntary disclosure of attorney work product to an adversary or a conduit to an adversary waives work-product protection for that material.

Applying this standard, the government contends that Dow has waived work-product protection for the Dow Documents because Deloitte is (1\) a potential adversary and (2\) a conduit to other adversaries. We reject both contentions and conclude that Dow has not waived the protection.

[1]{.casesubsubsection}

The government contends that Deloitte is a potential adversary of Dow because disputes sometimes arise between independent auditors and their clients and because independent auditors have the power to issue opinions that adversely affect their clients. Neither argument demonstrates that Deloitte is a potential adversary for purposes of waiver analysis. First, as an independent auditor, Deloitte cannot be Dow's adversary. Even the threat of litigation between an independent auditor and its client can compromise the auditor's independence and necessitate withdrawal. Further, Deloitte's power to issue an adverse opinion, while significant, does not make it the sort of litigation adversary contemplated by the waiver standard. Similarly, "any tension between an auditor and a corporation that arises from an auditor's need to scrutinize and investigate a corporation's records and book-keeping practices simply is not the equivalent of an adversarial relationship contemplated by the work product doctrine." Second, the possibility of a future dispute between Deloitte and Dow does not render Deloitte a potential adversary for the present purpose. If it did, any voluntary disclosure would constitute waiver. Yet the work-product doctrine allows disclosures as long as they do not undercut the adversary process.

Here, the question is not whether Deloitte could be Dow's adversary in any conceivable future litigation, but whether Deloitte could be Dow's adversary in the sort of litigation the Dow Documents address. We conclude that the answer must be no. In preparing the Dow Documents, Dow anticipated a dispute with the IRS, not a dispute with Deloitte. The documents, which concern the tax implications of the Chemtech partnerships, would not likely be relevant in any dispute Dow might have with Deloitte. Thus Deloitte cannot be considered a potential adversary with respect to the Dow Documents.

[2]{.casesubsubsection}

The government also asserts that Deloitte is a conduit to Dow's adversaries. It claims the district court failed to address this question, but this ignores the district court's explicit statement that "no evidence suggests that it was unreasonable for Dow to expect Deloitte USA to maintain confidentiality." Like the district court, we conclude that Deloitte is not a conduit to Dow's adversaries.

Our prior decisions applying the "maintenance of secrecy" standard, while fact-intensive, have generally made two discrete inquiries in assessing whether disclosure constitutes waiver. First, we have considered whether the disclosing party has engaged in self-interested selective disclosure by revealing its work product to some adversaries but not to others. Such conduct militates in favor of waiver, for it is "inconsistent and unfair to allow parties to select according to their own self-interest to which adversaries they will allow access to the materials."

Second, we have examined whether the disclosing party had a reasonable basis for believing that the recipient would keep the disclosed material confidential. A reasonable expectation of confidentiality may derive from common litigation interests between the disclosing party and the recipient. "The existence of common interests between transferor and transferee is relevant to deciding whether the disclosure is consistent with the nature of the work product privilege." This is true because when common litigation interests are present, "the transferee is not at all likely to disclose the work product material to the adversary." Alternately, a reasonable expectation of confidentiality may be rooted in a confidentiality agreement or similar arrangement between the disclosing party and the recipient. Nevertheless, a confidentiality agreement must be relatively strong and sufficiently unqualified to avoid waiver. In *Williams*, for example, we concluded that the government's assurance that it would maintain confidentiality "to the extent possible" was not sufficiently strong or sufficiently unqualified to prevent the government from disclosing the information to a criminal defendant under *Brady v. Maryland*. Likewise, we have determined that a mere promise to give the disclosing party notice before releasing documents does not support a reasonable expectation of confidentiality.

The selective disclosure inquiry is straightforward. Selective disclosure involves disclosing work product to at least one adversary. As we have explained, Deloitte is not an adversary, so Dow's disclosure to Deloitte was not selective disclosure. The "reasonable expectation of confidentiality" inquiry is more complicated. As to common interests, Dow and Deloitte do not have common litigation interests in the Dow Documents---Dow has a litigation interest in the documents because of its interest in the Chemtech partnerships, but Deloitte has no similar interest in the documents. Absent common interests, the question is whether a confidentiality agreement or similar assurance gave Dow a reasonable expectation that Deloitte would keep its work product confidential.

We conclude that Dow had a reasonable expectation of confidentiality because Deloitte, as an independent auditor, has an obligation to refrain from disclosing confidential client information. Rule 301 of the American Institute of Certified Public Accountants Code of Professional Conduct provides: "A member in public practice shall not disclose any confidential client information without the specific consent of the client." William Curry's declaration explains that "Dow furnished these documents to Deloitte with the expectation that Deloitte would retain the confidentiality of the two documents." Given the obligation imposed by Rule 301, we think this expectation was reasonable.

The government responds that this is a "qualified assurance" that does not suffice to prevent waiver because Rule 301 also explains that it "shall not be construed to affect in any way the member's obligation to comply with a validly issued and enforceable subpoena or summons." But an assertion of work-product protection challenges the enforceability of a subpoena with respect to those materials. Thus Deloitte could refuse to produce the documents, thereby allowing Dow to intervene and assert work-product protection, without violating its obligation to comply with enforceable subpoenas. Indeed, this is exactly what Deloitte did. Accordingly, this caveat does not significantly diminish the reasonableness of Dow's expectation of confidentiality.

The government also attempts to bolster its waiver argument by identifying instances in which an independent auditor might disclose information obtained from a company whose finances it audits. For example, it asserts that Deloitte could make Dow disclose its confidential tax analysis in footnotes to its public financial statements. Likewise, Deloitte could testify about confidential information obtained from Dow in proceedings brought by the SEC or private parties. Or Deloitte might report illegal acts it detects during its audit. Finally, the government returns to *Arthur Young*, arguing that as an independent auditor, Deloitte is a "public watchdog" whose ultimate allegiance is to Dow's creditors, stockholders, and the investing public---all potential adversaries of Dow. In sum, the government contends that Dow could not reasonably expect confidentiality from Deloitte after giving it the Dow Documents, given the myriad ways Deloitte could reveal that information.

Of course Deloitte might disclose some information relevant to Dow's finances. But the government has neither pointed to any regulatory provision nor posited any specific circumstance under which Deloitte would be required to disclose attorney work product like that contained in the Dow Documents. An independent auditor can fulfill its duties and render an opinion concerning a company's public financial statements without revealing every piece of information it reviews during the audit process. In short, Deloitte's independent auditor obligations do not make it a conduit to Dow's adversaries.

Likewise, the government's reliance on *Arthur Young* is misplaced. In *Arthur Young*, the Court considered whether accountant work-product should be granted the same protection attorney work product receives. The government quotes the Court's statement that "To insulate from disclosure a certified public accountant's interpretations of the client's financial statements would be to ignore the significance of the accountant's role as a disinterested analyst charged with public obligations." All well and good. In this case, however, the government attempts to discover not an independent auditor's "interpretations of the client's financial statements," which *Arthur Young* would permit, but an attorney's thoughts and opinions developed in anticipation of litigation, which the work-product doctrine forbids.

Furthermore, we are mindful that independent auditors have significant leverage over the companies whose finances they audit. An auditor can essentially compel disclosure by refusing to provide an unqualified opinion otherwise. Finding waiver based on such disclosures could well encourage the sort of "inefficiency, unfairness and sharp practices" that *Hickman* sought to avoid. For example, it might discourage companies from seeking legal advice and candidly disclosing that information to independent auditors. Moreover, the government has not proffered any good reason for wanting the Dow Documents other than its desire to know what Dow's counsel thought about the Chemtech partnerships. Granting discovery under these circumstances would undercut the adversary process and let the government litigate "on wits borrowed from the adversary," We conclude that the district court applied the correct legal standard and acted within its discretion in determining that Dow had not waived work-product protection. Consequently, we affirm the district court's decision denying the government's motion to compel with respect to the Dow Documents.

## Attorney-Client Privilege & Work Product for Organizational Clients

#### @Rest2dLawGoverningLawyers

::: legalcode
##### § 73. The Privilege for an Organizational Client

When a client is a corporation, unincorporated association, partnership, trust, estate, sole proprietorship, or other for-profit or not-for-profit organization, the attorney-client privilege extends to a communication that:

-   \(1\) otherwise qualifies as privileged under §§ 68-72;
-   \(2\) is between an agent of the organization and a privileged person as defined in § 70;
-   \(3\) concerns a legal matter of interest to the organization; and
-   \(4\) is disclosed only to:
    -   \(a\) privileged persons as defined in § 70; and
    -   \(b\) other agents of the organization who reasonably need to know of the communication in order to act for the organization.

##### § 74. The Privilege for a Governmental Client

Unless applicable law otherwise provides, the attorney-client privilege extends to a communication of a governmental organization as stated in § 73 and of an individual employee or other agent of a governmental organization as a client with respect to his or her personal interest as stated in §§ 68-72.
:::

#### @UpjohnCoUnitedStates_US1981

##### Justice Rehnquist delivered the opinion of the Court.

We granted certiorari in this case to address important questions concerning the scope of the attorney-client privilege in the corporate context and the applicability of the work-product doctrine in proceedings to enforce tax summonses. With respect to the privilege question the parties and various amici have described our task as one of choosing between two "tests" which have gained adherents in the courts of appeals. We are acutely aware, however, that we sit to decide concrete cases and not abstract propositions of law. We decline to lay down a broad rule or series of rules to govern all conceivable future questions in this area, even were we able to do so. We can and do, however, conclude that the attorney-client privilege protects the communications involved in this case from compelled disclosure and that the work-product doctrine does apply in tax summons enforcement proceedings.

[I]{.casesection}

Petitioner Upjohn Co. manufactures and sells pharmaceuticals here and abroad. In January 1976 independent accountants conducting an audit of one of Upjohn's foreign subsidiaries discovered that the subsidiary made payments to or for the benefit of foreign government officials in order to secure government business. The accountants so informed petitioner Mr. Gerard Thomas, Upjohn's Vice President, Secretary, and General Counsel. Thomas is a member of the Michigan and New York Bars, and has been Upjohn's General Counsel for 20 years. He consulted with outside counsel and R. T. Parfet, Jr., Upjohn's Chairman of the Board. It was decided that the company would conduct an internal investigation of what were termed "questionable payments." As part of this investigation the attorneys prepared a letter containing a questionnaire which was sent to "All Foreign General and Area Managers" over the Chairman's signature. The letter began by noting recent disclosures that several American companies made "possibly illegal" payments to foreign government officials and emphasized that the management needed full information concerning any such payments made by Upjohn. The letter indicated that the Chairman had asked Thomas, identified as "the company's General Counsel," "to conduct an investigation for the purpose of determining the nature and magnitude of any payments made by the Upjohn Company or any of its subsidiaries to any employee or official of a foreign government." The questionnaire sought detailed information concerning such payments. Managers were instructed to treat the investigation as "highly confidential" and not to discuss it with anyone other than Upjohn employees who might be helpful in providing the requested information. Responses were to be sent directly to Thomas. Thomas and outside counsel also interviewed the recipients of the questionnaire and some 33 other Upjohn officers or employees as part of the investigation.

On March 26, 1976, the company voluntarily submitted a preliminary report to the Securities and Exchange Commission on Form 8-K disclosing certain questionable payments. A copy of the report was simultaneously submitted to the Internal Revenue Service, which immediately began an investigation to determine the tax consequences of the payments. Special agents conducting the investigation were given lists by Upjohn of all those interviewed and all who had responded to the questionnaire. On November 23, 1976, the Service issued a summons demanding production of:

> All files relative to the investigation conducted under the supervision of Gerard Thomas to identify payments to employees of foreign governments and any political contributions made by the Upjohn Company or any of its affiliates since January 1, 1971 and to determine whether any funds of the Upjohn Company had been improperly accounted for on the corporate books during the same period. The records should include but not be limited to written questionnaires sent to managers of the Upjohn Company's foreign affiliates, and memorandums or notes of the interviews conducted in the United States and abroad with officers and employees of the Upjohn Company and its subsidiaries.

The company declined to produce the documents specified in the second paragraph on the grounds that they were protected from disclosure by the attorney-client privilege and constituted the work product of attorneys prepared in anticipation of litigation. On August 31, 1977, the United States filed a petition seeking enforcement of the summons in the United States District Court for the Western District of Michigan. That court adopted the recommendation of a Magistrate who concluded that the summons should be enforced. Petitioners appealed to the Court of Appeals for the Sixth Circuit which rejected the Magistrate's finding of a waiver of the attorney-client privilege, but agreed that the privilege did not apply "to the extent that the communications were made by officers and agents not responsible for directing Upjohn's actions in response to legal advice for the simple reason that the communications were not the 'client's.'" The court reasoned that accepting petitioners' claim for a broader application of the privilege would encourage upper-echelon management to ignore unpleasant facts and create too broad a "zone of silence." Noting that Upjohn's counsel had interviewed officials such as the Chairman and President, the Court of Appeals remanded to the District Court so that a determination of who was within the "control group" could be made. In a concluding footnote the court stated that the work-product doctrine "is not applicable to administrative summonses."

[II]{.casesection}

Federal Rule of Evidence 501 provides that "the privilege of a witness shall be governed by the principles of the common law as they may be interpreted by the courts of the United States in light of reason and experience." The attorney-client privilege is the oldest of the privileges for confidential communications known to the common law. Its purpose is to encourage full and frank communication between attorneys and their clients and thereby promote broader public interests in the observance of law and administration of justice. The privilege recognizes that sound legal advice or advocacy serves public ends and that such advice or advocacy depends upon the lawyer's being fully informed by the client. "The lawyer-client privilege rests on the need for the advocate and counselor to know all that relates to the client's reasons for seeking representation if the professional mission is to be carried out." The purpose of the privilege is "to encourage clients to make full disclosure to their attorneys." This rationale for the privilege has long been recognized by the Court. Admittedly complications in the application of the privilege arise when the client is a corporation, which in theory is an artificial creature of the law, and not an individual; but this Court has assumed that the privilege applies when the client is a corporation, and the Government does not contest the general proposition.

The Court of Appeals, however, considered the application of the privilege in the corporate context to present a "different problem," since the client was an inanimate entity and "only the senior management, guiding and integrating the several operations, can be said to possess an identity analogous to the corporation as a whole."

Such a view, we think, overlooks the fact that the privilege exists to protect not only the giving of professional advice to those who can act on it but also the giving of information to the lawyer to enable him to give sound and informed advice. The first step in the resolution of any legal problem is ascertaining the factual background and sifting through the facts with an eye to the legally relevant. See ABA Code of Professional Responsibility, Ethical Consideration 4-1:

> A lawyer should be fully informed of all the facts of the matter he is handling in order for his client to obtain the full advantage of our legal system. It is for the lawyer in the exercise of his independent professional judgment to separate the relevant and important from the irrelevant and unimportant. The observance of the ethical obligation of a lawyer to hold inviolate the confidences and secrets of his client not only facilitates the full development of facts essential to proper representation of the client but also encourages laymen to seek early legal assistance.

In the case of the individual client the provider of information and the person who acts on the lawyer's advice are one and the same. In the corporate context, however, it will frequently be employees beyond the control group as defined by the court below—"officers and agents responsible for directing the company's actions in response to legal advice" —who will possess the information needed by the corporation's lawyers. Middle-level—and indeed lower-level—employees can, by actions within the scope of their employment, embroil the corporation in serious legal difficulties, and it is only natural that these employees would have the relevant information needed by corporate counsel if he is adequately to advise the client with respect to such actual or potential difficulties.

> In a corporation, it may be necessary to glean information relevant to a legal problem from middle management or non-management personnel as well as from top executives. The attorney dealing with a complex legal problem "is thus faced with a 'Hobson's choice'. If he interviews employees not having 'the very highest authority', their communications to him will not be privileged. If, on the other hand, he interviews only those employees with 'the very highest authority', he may find it extremely difficult, if not impossible, to determine what happened."

The control group test adopted by the court below thus frustrates the very purpose of the privilege by discouraging the communication of relevant information by employees of the client to attorneys seeking to render legal advice to the client corporation. The attorney's advice will also frequently be more significant to noncontrol group members than to those who officially sanction the advice, and the control group test makes it more difficult to convey full and frank legal advice to the employees who will put into effect the client corporation's policy.

The narrow scope given the attorney-client privilege by the court below not only makes it difficult for corporate attorneys to formulate sound advice when their client is faced with a specific legal problem but also threatens to limit the valuable efforts of corporate counsel to ensure their client's compliance with the law. In light of the vast and complicated array of regulatory legislation confronting the modern corporation, corporations, unlike most individuals, "constantly go to lawyers to find out how to obey the law," particularly since compliance with the law in this area is hardly an instinctive matter. The test adopted by the court below is difficult to apply in practice, though no abstractly formulated and unvarying "test" will necessarily enable courts to decide questions such as this with mathematical precision. But if the purpose of the attorney-client privilege is to be served, the attorney and client must be able to predict with some degree of certainty whether particular discussions will be protected. An uncertain privilege, or one which purports to be certain but results in widely varying applications by the courts, is little better than no privilege at all. The very terms of the test adopted by the court below suggest the unpredictability of its application. The test restricts the availability of the privilege to those officers who play a "substantial role" in deciding and directing a corporation's legal response. Disparate decisions in cases applying this test illustrate its unpredictability.

The communications at issue were made by Upjohn employees to counsel for Upjohn acting as such, at the direction of corporate superiors in order to secure legal advice from counsel. As the Magistrate found, "Mr. Thomas consulted with the Chairman of the Board and outside counsel and thereafter conducted a factual investigation to determine the nature and extent of the questionable payments and to be in a position to give legal advice to the company with respect to the payments." Information, not available from upper-echelon management, was needed to supply a basis for legal advice concerning compliance with securities and tax laws, foreign laws, currency regulations, duties to shareholders, and potential litigation in each of these areas. The communications concerned matters within the scope of the employees' corporate duties, and the employees themselves were sufficiently aware that they were being questioned in order that the corporation could obtain legal advice. The questionnaire identified Thomas as "the company's General Counsel" and referred in its opening sentence to the possible illegality of payments such as the ones on which information was sought. A statement of policy accompanying the questionnaire clearly indicated the legal implications of the investigation. The policy statement was issued "in order that there be no uncertainty in the future as to the policy with respect to the practices which are the subject of this investigation." It began "Upjohn will comply with all laws and regulations," and stated that commissions or payments "will not be used as a subterfuge for bribes or illegal payments" and that all payments must be "proper and legal." Any future agreements with foreign distributors or agents were to be approved "by a company attorney" and any questions concerning the policy were to be referred "to the company's General Counsel." This statement was issued to Upjohn employees worldwide, so that even those interviewees not receiving a questionnaire were aware of the legal implications of the interviews. Pursuant to explicit instructions from the Chairman of the Board, the communications were considered "highly confidential" when made, and have been kept confidential by the company. Consistent with the underlying purposes of the attorney-client privilege, these communications must be protected against compelled disclosure.

The Court of Appeals declined to extend the attorney-client privilege beyond the limits of the control group test for fear that doing so would entail severe burdens on discovery and create a broad "zone of silence" over corporate affairs. Application of the attorney-client privilege to communications such as those involved here, however, puts the adversary in no worse position than if the communications had never taken place. The privilege only protects disclosure of communications; it does not protect disclosure of the underlying facts by those who communicated with the attorney:

> The protection of the privilege extends only to communications and not to facts. A fact is one thing and a communication concerning that fact is an entirely different thing. The client cannot be compelled to answer the question, "What did you say or write to the attorney?" but may not refuse to disclose any relevant fact within his knowledge merely because he incorporated a statement of such fact into his communications to his attorney.

Here the Government was free to question the employees who communicated with Thomas and outside counsel. Upjohn has provided the IRS with a list of such employees, and the IRS has already interviewed some 25 of them. While it would probably be more convenient for the Government to secure the results of petitioner's internal investigation by simply subpoenaing the questionnaires and notes taken by petitioner's attorneys, such considerations of convenience do not overcome the policies served by the attorney-client privilege. As Justice Jackson noted in his concurring opinion in *Hickman v. Taylor*: "Discovery was hardly intended to enable a learned profession to perform its functions on wits borrowed from the adversary."

Needless to say, we decide only the case before us, and do not undertake to draft a set of rules which should govern challenges to investigatory subpoenas. Any such approach would violate the spirit of Federal Rule of Evidence 501. While such a "case-by-case" basis may to some slight extent undermine desirable certainty in the boundaries of the attorney-client privilege, it obeys the spirit of the Rules. At the same time we conclude that the narrow "control group test" sanctioned by the Court of Appeals in this case cannot, consistent with "the principles of the common law as interpreted in the light of reason and experience," govern the development of the law in this area.

## Exceptions to Attorney-Client Privilege and Work Product Protection

#### @Rest2dLawGoverningLawyers

::: legalcode

##### § 78. Agreement, Disclaimer, or Failure to Object

The attorney-client privilege is waived if the client, the client's lawyer, or another authorized agent of the client:

-   \(1\) agrees to waive the privilege;
-   \(2\) disclaims protection of the privilege and
    -   \(a\) another person reasonably relies on the disclaimer to that person's detriment; or
    -   \(b\) reasons of judicial administration require that the client not be permitted to revoke the disclaimer; or
-   \(3\) in a proceeding before a tribunal, fails to object properly to an attempt by another person to give or exact testimony or other evidence of a privileged communication.

##### § 79. Subsequent Disclosure

The attorney-client privilege is waived if the client, the client's lawyer, or another authorized agent of the client voluntarily discloses the communication in a nonprivileged communication.

##### § 80. Putting Assistance or a Communication in Issue

-   \(1\) The attorney-client privilege is waived for any relevant communication if the client asserts as to a material issue in a proceeding that:
    -   \(a\) the client acted upon the advice of a lawyer or that the advice was otherwise relevant to the legal significance of the client's conduct; or
    -   \(b\) a lawyer's assistance was ineffective, negligent, or otherwise wrongful.
-   \(2\) The attorney-client privilege is waived for a recorded communication if a witness:
    -   \(a\) employs the communication to aid the witness while testifying; or
    -   \(b\) employed the communication in preparing to testify, and the tribunal finds that disclosure is required in the interests of justice.

##### § 81. A Dispute Concerning a Decedent's Disposition of Property

The attorney-client privilege does not apply to a communication from or to a decedent relevant to an issue between parties who claim an interest through the same deceased client, either by testate or intestate succession or by an inter vivos transaction.

##### § 82. Client Crime or Fraud

The attorney-client privilege does not apply to a communication occurring when a client:

-   \(a\) consults a lawyer for the purpose, later accomplished, of obtaining assistance to engage in a crime or fraud or aiding a third person to do so, or
-   \(b\) regardless of the client's purpose at the time of consultation, uses the lawyer's advice or other services to engage in or assist a crime or fraud.

##### § 83. Lawyer Self-Protection

The attorney-client privilege does not apply to a communication that is relevant and reasonably necessary for a lawyer to employ in a proceeding:

-   \(1\) to resolve a dispute with a client concerning compensation or reimbursement that the lawyer reasonably claims the client owes the lawyer; or
-   \(2\) to defend the lawyer or the lawyer's associate or agent against a charge by any person that the lawyer, associate, or agent acted wrongfully during the course of representing a client.

##### § 84. Fiduciary-Lawyer Communications

In a proceeding in which a trustee of an express trust or similar fiduciary is charged with breach of fiduciary duties by a beneficiary, a communication otherwise within § 68 is nonetheless not privileged if the communication:

-   \(a\) is relevant to the claimed breach; and
-   \(b\) was between the trustee and a lawyer (or other privileged person within the meaning of § 70) who was retained to advise the trustee concerning the administration of the trust.

##### § 85. Communications Involving a Fiduciary Within an Organization

In a proceeding involving a dispute between an organizational client and shareholders, members, or other constituents of the organization toward whom the directors, officers, or similar persons managing the organization bear fiduciary responsibilities, the attorney-client privilege of the organization may be withheld from a communication otherwise within § 68 if the tribunal finds that:

-   \(a\) those managing the organization are charged with breach of their obligations toward the shareholders, members, or other constituents or toward the organization itself;
-   \(b\) the communication occurred prior to the assertion of the charges and relates directly to those charges; and
-   \(c\) the need of the requesting party to discover or introduce the communication is sufficiently compelling and the threat to confidentiality sufficiently confined to justify setting the privilege aside.

##### § 91. Voluntary Acts

Work-product immunity is waived if the client, the client's lawyer, or another authorized agent of the client:

-   \(1\) agrees to waive the immunity;
-   \(2\) disclaims protection of the immunity and:
    -   \(a\) another person reasonably relies on the disclaimer to that person's detriment; or
    -   \(b\) reasons of judicial administration require that the client not be permitted to revoke the disclaimer; or
-   \(3\) in a proceeding before a tribunal, fails to object properly to an attempt by another person to give or exact testimony or other evidence of work product; or
-   \(4\) discloses the material to third persons in circumstances in which there is a significant likelihood that an adversary or potential adversary in anticipated litigation will obtain it.

##### § 92. Use of Lawyer Work Product in Litigation

-   \(1\) Work-product immunity is waived for any relevant material if the client asserts as to a material issue in a proceeding that:
    -   \(a\) the client acted upon the advice of a lawyer or that the advice was otherwise relevant to the legal significance of the client's conduct; or
    -   \(b\) a lawyer's assistance was ineffective, negligent, or otherwise wrongful.
-   \(2\) The work-product immunity is waived for recorded material if a witness:
    -   \(a\) employs the material to aid the witness while testifying, or
    -   \(b\) employed the material in preparing to testify, and the tribunal finds that disclosure is required in the interests of justice.

##### § 93. Client Crime or Fraud

Work-product immunity does not apply to materials prepared when a client consults a lawyer for the purpose, later accomplished, of obtaining assistance to engage in a crime or fraud or to aid a third person to do so or uses the materials for such a purpose.
:::

#### @FederalRulesEvidenceRule502

::: legalcode
##### Attorney-Client Privilege and Work Product; Limitations on Waiver

The following provisions apply, in the circumstances set out, to disclosure of a communication or information covered by the attorney-client privilege or work-product protection.

-   \(a\) Disclosure Made in a Federal Proceeding or to a Federal Office or Agency; Scope of a Waiver. When the disclosure is made in a federal proceeding or to a federal office or agency and waives the attorney-client privilege or work-product protection, the waiver extends to an undisclosed communication or information in a federal or state proceeding only if:
    -   \(1\) the waiver is intentional;
    -   \(2\) the disclosed and undisclosed communications or information concern the same subject matter; and
    -   \(3\) they ought in fairness to be considered together.
-   \(b\) Inadvertent Disclosure. When made in a federal proceeding or to a federal office or agency, the disclosure does not operate as a waiver in a federal or state proceeding if:
    -   \(1\) the disclosure is inadvertent;
    -   \(2\) the holder of the privilege or protection took reasonable steps to prevent disclosure; and
    -   \(3\) the holder promptly took reasonable steps to rectify the error, including (if applicable) following Federal Rule of Civil Procedure 26 (b)(5)(B).
-   \(c\) Disclosure Made in a State Proceeding. When the disclosure is made in a state proceeding and is not the subject of a state-court order concerning waiver, the disclosure does not operate as a waiver in a federal proceeding if the disclosure:
    -   \(1\) would not be a waiver under this rule if it had been made in a federal proceeding; or
    -   \(2\) is not a waiver under the law of the state where the disclosure occurred.
-   \(d\) Controlling Effect of a Court Order. A federal court may order that the privilege or protection is not waived by disclosure connected with the litigation pending before the court — in which event the disclosure is also not a waiver in any other federal or state proceeding.
-   \(e\) Controlling Effect of a Party Agreement. An agreement on the effect of disclosure in a federal proceeding is binding only on the parties to the agreement, unless it is incorporated into a court order.
-   \(f\) Controlling Effect of this Rule. Notwithstanding Rules 101 and 1101, this rule applies to state proceedings and to federal court-annexed and federal court-mandated arbitration proceedings, in the circumstances set out in the rule. And notwithstanding Rule 501, this rule applies even if state law provides the rule of decision.
-   \(g\) Definitions. In this rule:
    -   \(1\) “attorney-client privilege” means the protection that applicable law provides for confidential attorney-client communications; and
    -   \(2\) “work-product protection” means the protection that applicable law provides for tangible material (or its intangible equivalent) prepared in anticipation of litigation or for trial.
:::

#### @ClarkCapitalManagementAnnuity_EDPa2001

There is a privilege protecting communications between attorney and client. The privilege takes flight if the relation is abused. A client who consults an attorney for advice that will serve him in the commission of a fraud will have no help from the law. He must let the truth be told. There are early cases apparently to the effect that a mere charge of illegality, not supported by any evidence, will set the confidences free. But this conception of the privilege is without support in later rulings. "It is obvious that it would be absurd to say that the privilege could be got rid of merely by making a charge of fraud." To drive the privilege away, there must be "something to give colour to the charge;" there must be "prima facie evidence that it has some foundation in fact." When that evidence is supplied, the seal of secrecy is broken. Nor does the loss of the privilege depend upon the showing of a conspiracy, upon proof that client and attorney are involved in equal guilt. The attorney may be innocent, and still the guilty client must let the truth come out.

#### @BlumenthalKimberMfgInc_Connecticut2003

The petitioner, Richard Blumenthal, the attorney general of the state of Connecticut, appeals from the decision of the trial court denying his application for an order requiring the respondents, Kimber Manufacturing, Inc., a firearms manufacturer with its principal place of business in Yonkers, New York, and Leslie Edelman, Kimber's president, to comply with the petitioner's discovery request for a certain document sent from one Kimber employee to an attorney and three other Kimber employees. The petitioner contends that the trial court improperly determined that: (1\) the communication was protected by the attorney-client privilege; and (2\) the communication was not otherwise subject to disclosure under the crime-fraud exception to that privilege. We conclude that the trial court properly determined that the document was protected by the attorney-client privilege and that the petitioner did not meet his burden of establishing that the crime-fraud exception applies to exclude the document from protection under the privilege. Accordingly, we affirm the decision of the trial court.

The record discloses the following relevant facts. On March 17, 2000, Smith and Wesson Corporation (Smith & Wesson), a firearms manufacturer located in Springfield, Massachusetts, entered into an agreement with representatives of various federal, state and local governmental agencies (agreement). The agreement was an attempt to settle both pending and threatened litigation by these governmental agencies against various firearms manufacturers. The agreement required Smith & Wesson, as well as all other potential signatories to the agreement, to engage in certain practices, opposed by most of the firearms industry, regarding the manufacturing, sale and marketing of firearms. At the time of the proceeding before the trial court, Smith & Wesson was the only firearms manufacturer to have signed the agreement.

On May 2, 2000, based on his suspicion of the respondents' participation in a retaliatory economic boycott against Smith & Wesson, the petitioner issued to the respondents interrogatories and a subpoena duces tecum, pursuant to the petitioner's investigatory authority under General Statutes § 35-42, seeking documents "as to any matter relevant to any alleged violation of the Connecticut Antitrust Act"; and specifically any documents related to Smith & Wesson. On May 31, 2000, the respondents submitted responses, and thereafter submitted supplemental responses on July 20 and December 28, 2000. Unsatisfied with the respondents' disclosure, on March 20, 2001, the petitioner filed with the trial court an application for compliance. Thereafter, the respondents submitted five additional supplemental responses, leading to a total disclosure of approximately 577 pages of documents. After negotiation between the parties as to outstanding documents sought, the hearing on the petitioner's application for compliance was reduced to one issue---a claim of attorney-client privilege on a document sent via electronic mail (e-mail) by Dwight Van Brunt, a Kimber employee, to Edelman, Denis Schusterman, another Kimber employee, and Jerry S. Goldman, an attorney in private practice. The e-mail also was copied to Ryan Busse, another Kimber employee. The e-mail expressly referred to the Smith & Wesson agreement, and the firearms industry's initial reaction to it.

In response to a joint motion for entry of consent order, the trial court directed the respondents to submit the e-mail to the court for an in camera determination of the privilege issue. The parties submitted to the court a joint stipulation of facts, setting forth the factual and procedural background of the matter. At a hearing on the consent order, following a joint request, the trial court sealed the record.

Goldman, one of the parties to whom the e-mail had been sent, appeared as counsel on behalf of the respondents. Goldman represented to the court that, because the agreement arose out of a series of lawsuits that all named John Doe as a defendant in the complaints, potential firearms manufacturer defendants, like Kimber, needed to evaluate the agreement and the firearms industry's reaction to the agreement in order to plan an effective legal strategy of their own. Goldman also provided the court with the corporate titles of each of the e-mail recipients, which identified them as senior Kimber officers. Goldman contended that, because the reactions of others in the firearms industry to the agreement---such as whether to sign similar agreements or litigate---would inform Kimber's legal decision making, Kimber's management needed to keep track of these developments and communicate them to him, as Kimber's counsel.

The petitioner contended that the e-mail was not subject to the attorney-client privilege because it was not marked as confidential and did not request legal advice; rather, according to the petitioner, the subject matter of the e-mail concerned ongoing business developments. The petitioner also contended that the respondents had presented no evidence that litigation had been filed or even threatened against Kimber, nor any evidence of the existence of "John Doe" defendants in such litigation. The petitioner further claimed that, because reference to the e-mail itself did not indicate that it satisfied the requirements of the attorney-client privilege, and because the respondents did not produce any evidence beyond the e-mail and the stipulated facts, the respondents had failed to satisfy their burden of proof to invoke the privilege. Furthermore, the petitioner argued that, even if the trial court were to infer that the e-mail had been a request for legal advice, and therefore privileged, it would be subject to disclosure under the crime-fraud exception to the privilege.

On September 10, 2001, the same day as the consent order hearing, the trial court issued an order stating that the e-mail was subject to a valid claim of attorney-client privilege. On January 30, 2002, in response to the petitioner's motion for articulation, the trial court issued a memorandum of decision setting forth the reasons for its decision. Specifically, the trial court set forth and applied the four part test that we articulated in *Shew v. Freedom of Information Commission,* for determining whether the attorney-client privilege applies to protect communications between corporate employees and attorneys retained by the corporation. The court determined that, under the test, the e-mail qualified for protection from disclosure. Additionally, the court concluded that the crime-fraud exception did not apply because the e-mail "is a patent update of firearms litigation developments and does not advocate any criminal or illegal activity." This appeal followed.

[I]{.casesection}

We turn to the petitioner's claim that, even if we were to assume that the privilege generally applied, the trial court improperly determined that the e-mail was not subject to disclosure under the crime-fraud exception to the attorney-client privilege. Specifically, the petitioner contends that other documents submitted as exhibits to the trial court provide probable cause to believe that the respondents engaged in an unlawful boycott of Smith & Wesson and that the e-mail was in direct furtherance of the boycott. We conclude that the trial court properly concluded that the e-mail did not fall under the crime-fraud exception.

As an initial matter, we note that "exceptions to the attorney-client privilege should be made only when the reason for disclosure outweighs the potential chilling of essential communications." The crime-fraud exception to the attorney-client privilege, therefore, is a limited one, and the burden of proof is on the party seeking to pierce the privilege. We also recognize, however, "that since the attorney-client privilege has the effect of withholding relevant information from the fact-finder, it applies only where necessary to achieve its purpose." In *Olson* v. *Accessory Controls & Equipment Corp.,* we set forth the proper inquiry for determining when the crime-fraud exception extinguishes the attorney-client privilege. The exception applies only after a determination by the trial court "that there is probable cause to believe that a crime or fraud has been attempted or committed and that the communication was in furtherance thereof."

Probable cause "requires that a prudent person have a reasonable basis to suspect the perpetration or attempted perpetration of a crime or fraud, and that the communication was in furtherance thereof." "The appropriate inquiry under the probable cause standard targets the client's intent in obtaining legal advice; only if there is probable cause to believe that the client intended to perpetrate a crime or fraud does the exception properly come to bear." We have explained that, "without reference to intent, the attorney-client privilege would be pierced whenever probable cause could be made that an illegal act occurred after the client conferred with an attorney---even if the consultation was part of a good-faith attempt to follow the law. Good-faith consultations with attorneys by clients who are uncertain about the legal implications of a proposed course of action however are entitled to the protection of the privilege, even if that action should later be held improper."

We note that, in the present case, the trial court did not determine specifically whether the petitioner had met this probable cause requirement. Even if we were to assume, however, that there was probable cause to believe that the respondents had committed or intended to commit a crime by engaging in an economic boycott in violation of antitrust law, we nevertheless conclude that the petitioner failed to meet his burden of proof.

In addition to probable cause, the crime-fraud exception is limited by a second requirement that the communication sought in discovery was made in furtherance of that unlawful act. "The crime-fraud exception does not apply simply because privileged communications would provide an adversary with evidence of a crime or fraud. Mere relevance is insufficient; there must be a showing that the communications at issue were made with an intent to further an unlawful act."

Our analysis as to the "in furtherance" requirement is informed largely by our reasoning in part I of this opinion. As we previously stated, the trial court reasonably could have found that the e-mail concerned matters involving the agreement by a major firearms manufacturer seeking to avoid litigation, and how that agreement, along with the litigation that gave rise to it, similarly might affect the respondents. Moreover, the e-mail reveals nothing that suggests an intent to break the law. Indeed, we agree with the trial court's determination that the critical statements at issue are "not words of advocacy, but, rather, statements of fact or impression." Furthermore, to the extent that the e-mail refers to any action, it is the actions of others, and not of the respondents; it neither advocates that Kimber take any action of its own, nor that others take a particular action. The evidence does not support a conclusion that the respondents sent the e-mail with the intent to further a fraud or crime. Rather, as the trial court reasonably concluded, it was intended to keep Goldman informed so that he could provide them with sound legal advice. Accordingly, the injury that would inure to the relationship of Kimber and its attorneys by disclosure of the e-mail is greater than the benefit that would be gained by its disclosure to the petitioner.

Therefore, we conclude that the trial court properly concluded that the e-mail is not subject to disclosure under the crime-fraud exception to the attorney-client privilege.

## Confidentiality & Evidentiary Privileges Comparison

| **Scope of Protection** | **Duty of Confidentiality** | **Attorney-Client Communication** | **Attorney Work Product** |
|-----------------|-----------------|---------------------|-----------------|
| *What is protected* | Any information relating to the representation | Private communication between attorney & client (or their agents) | Attorney's mental impressions |
| *From what source* | Any source | Communication between attorney & client | Attorney |
| *In what form* | Any form | Communication (verbal or non-verbal) | Tangible (e.g. documents) or intangible (e.g. attorney's recollections) |
| *Made for what purpose* | Any purpose | Securing legal representation or advice | Preparing for litigation |
| *When made or acquired* | Any time | During representation (or consultation by prospective client) | In anticipation of litigation |
| *Effect of protection* | Attorney may not disclose or use for any purpose | No compelled testimony or disclosure by client or attorney | Protected against discovery |
| *Waiver* | Only client | Only client | Attorney or client |